// Journey copy catalogue (plan 03.1-10, D-08, D-33, D-52, D-58).
// EN is copied from the 03.1-UI-SPEC Copywriting Contract.
// AR (Gulf-friendly Modern Standard Arabic) and ES (neutral Latin American) are DRAFTS
// written from the EN strings, flagged for owner review at the canvas gate (D-08).
// Amounts and rates appear only as `AED [PRICE]`, `AED [AMOUNT]` and `[RATE]%` (D-52).
// Plural forms are keyed by Intl.PluralRules categories; `#` is the number, `{name}` is a slot.
// Filled by lib/journey-format.ts. Numbers are Western numerals in all three languages.

export type JourneyLocale = "en" | "ar" | "es";

export type PluralForms = {
  zero?: string;
  one?: string;
  two?: string;
  few?: string;
  many?: string;
  other: string;
};

const EN = {
  bar: {
    label: "Plan a journey",
    destination: { label: "Destination", empty: "Where to?" },
    dates: { label: "Dates", empty: "Add dates", partial: "{start} – Add date" },
    guests: { label: "Guests" },
    search: "Search",
    editSearch: "Edit search",
    error: {
      both: "Choose a destination and dates to search.",
      destination: "Choose a destination to search.",
      dates: "Choose arrival and departure to search.",
      phoneDestination: "Choose a destination.",
      phoneDates: "Choose arrival and departure.",
    },
  },
  menu: {
    label: "Choose a destination",
    head: "One destination per journey",
    empty: "No destinations to show.",
  },
  dates: {
    label: "Choose dates",
    prevMonth: "Previous month",
    nextMonth: "Next month",
    line: {
      none: "Choose your arrival date.",
      start: "Arrive {start}. Now choose your departure date.",
      range: "Arrive {start} · Leave {end} · {nights}",
    },
    nights: { one: "# night", other: "# nights" },
    day: {
      arrival: "arrival",
      departure: "departure",
      inRange: "in your stay",
      unavailable: "unavailable",
      today: "today",
    },
    clear: "Clear dates",
  },
  done: "Done",
  guests: {
    label: "Guests",
    adults: "Adults",
    adultsHint: "13+",
    children: "Children",
    childrenHint: "3–12",
    infants: "Infants",
    infantsHint: "0–2",
    floor: "At least 1 adult",
    add: "Add {group}",
    remove: "Remove {group}",
    group: { adult: "adult", child: "child", infant: "infant" },
    summary: {
      adults: { one: "# adult", other: "# adults" },
      children: { one: "# child", other: "# children" },
      infants: { one: "# infant", other: "# infants" },
    },
  },
  entry: { title: "Plan your journey", hint: "Where · When · Who" },
  sheet: {
    label: "Plan your journey",
    progress: "{n} of 3",
    back: "Back",
    close: "Close",
    where: "Where to?",
    when: "When?",
    who: "Who's coming?",
    summary: {
      where: "Choose one destination",
      whereHint: "Tap a place to continue",
      whenHint: "Pick arrival, then departure",
      whenStart: "Arrive {start} · pick departure",
    },
    warn: { where: "Choose a destination.", when: "Choose arrival and departure." },
    next: "Next",
  },
  steps: {
    label: "Booking steps",
    stay: "Stay",
    addons: "Add-ons",
    travelers: "Travelers",
    pay: "Pay",
    change: "Change",
    phone: "Step {n} of 4 · {name}",
  },
  addons: {
    title: "Shape your journey",
    intro:
      "Add as many as you like. You can also add experiences and services after you pay, from your account.",
    section: "Experiences and services in {destination}",
    count: "{shown} options · {added} added",
    listLabel: "Experiences and services, scrolls",
    filter: {
      label: "Filter",
      all: "All",
      experiences: "Experiences",
      services: "Services",
    },
    kind: { experience: "Experience", service: "Service", serviceUae: "Service · UAE" },
    unit: { person: "per person", night: "per night", trip: "per trip" },
    add: "Add",
    added: "Added",
    addName: "Add {name}",
    addOne: "Add one {name}",
    removeOne: "Remove one {name}",
    max: { person: "One per guest", night: "One per night" },
    empty: {
      all: "No experiences or services here yet.",
      experiences: "No experiences here yet.",
      services: "No services here yet.",
    },
    back: "Back to stay",
    continue: "Continue to travelers",
  },
  inclusions: { title: "Included in your journey", note: "No extra charge" },
  cart: {
    label: "Your journey",
    kicker: "Your journey · {destination}",
    stay: { one: "Stay · # night", other: "Stay · # nights" },
    addons: { one: "# add-on", other: "# add-ons" },
    empty: "Nothing added yet.",
    remove: "Remove {name}",
    inclusions: { one: "# inclusion", other: "# inclusions" },
    included: "Included",
    subtotal: "Subtotal",
    vat: "VAT [RATE]%",
    total: "Total",
    note: "Nothing is charged before Pay. At step 4 you choose a deposit or pay in full, in one checkout for the stay and every add-on.",
    phoneTotal: { one: "Total · stay + # add-on", other: "Total · stay + # add-ons" },
    continue: "Continue",
  },
  pay: {
    choice: { error: "Choose deposit or full payment to continue." },
    airport: { error: "Choose your UAE airport to continue." },
  },
  locale: { language: "Language: {name}", currency: "Currency: {code}" },
};

// Widen literal strings to string and plural-form objects (they have an `other` string) to PluralForms.
type Widen<T> = T extends string
  ? string
  : T extends { other: string }
    ? PluralForms
    : { [K in keyof T]: Widen<T[K]> };

export type JourneyCopy = Widen<typeof EN>;

const AR: JourneyCopy = {
  bar: {
    label: "خطّط لرحلتك",
    destination: { label: "الوجهة", empty: "إلى أين؟" },
    dates: { label: "التواريخ", empty: "أضف التواريخ", partial: "{start} – أضف التاريخ" },
    guests: { label: "الضيوف" },
    search: "بحث",
    editSearch: "تعديل البحث",
    error: {
      both: "اختر وجهة وتواريخ للبحث.",
      destination: "اختر وجهة للبحث.",
      dates: "اختر تاريخ الوصول والمغادرة للبحث.",
      phoneDestination: "اختر وجهة.",
      phoneDates: "اختر تاريخ الوصول والمغادرة.",
    },
  },
  menu: {
    label: "اختر وجهة",
    head: "وجهة واحدة لكل رحلة",
    empty: "لا توجد وجهات للعرض.",
  },
  dates: {
    label: "اختر التواريخ",
    prevMonth: "الشهر السابق",
    nextMonth: "الشهر التالي",
    line: {
      none: "اختر تاريخ وصولك.",
      start: "الوصول {start}. اختر الآن تاريخ المغادرة.",
      range: "الوصول {start} · المغادرة {end} · {nights}",
    },
    nights: {
      zero: "# ليلة",
      one: "ليلة واحدة",
      two: "ليلتان",
      few: "# ليالٍ",
      many: "# ليلة",
      other: "# ليلة",
    },
    day: {
      arrival: "الوصول",
      departure: "المغادرة",
      inRange: "ضمن إقامتك",
      unavailable: "غير متاح",
      today: "اليوم",
    },
    clear: "مسح التواريخ",
  },
  done: "تم",
  guests: {
    label: "الضيوف",
    adults: "البالغون",
    adultsHint: "13 سنة فأكثر",
    children: "الأطفال",
    childrenHint: "3–12",
    infants: "الرضّع",
    infantsHint: "0–2",
    floor: "بالغ واحد على الأقل",
    add: "إضافة {group}",
    remove: "إزالة {group}",
    group: { adult: "بالغ", child: "طفل", infant: "رضيع" },
    summary: {
      adults: {
        zero: "# بالغ",
        one: "بالغ واحد",
        two: "بالغان",
        few: "# بالغين",
        many: "# بالغًا",
        other: "# بالغ",
      },
      children: {
        zero: "# طفل",
        one: "طفل واحد",
        two: "طفلان",
        few: "# أطفال",
        many: "# طفلًا",
        other: "# طفل",
      },
      infants: {
        zero: "# رضيع",
        one: "رضيع واحد",
        two: "رضيعان",
        few: "# رضّع",
        many: "# رضيعًا",
        other: "# رضيع",
      },
    },
  },
  entry: { title: "خطّط لرحلتك", hint: "أين · متى · من" },
  sheet: {
    label: "خطّط لرحلتك",
    progress: "{n} من 3",
    back: "رجوع",
    close: "إغلاق",
    where: "إلى أين؟",
    when: "متى؟",
    who: "من سيأتي؟",
    summary: {
      where: "اختر وجهة واحدة",
      whereHint: "اضغط على مكان للمتابعة",
      whenHint: "اختر الوصول ثم المغادرة",
      whenStart: "الوصول {start} · اختر المغادرة",
    },
    warn: { where: "اختر وجهة.", when: "اختر تاريخ الوصول والمغادرة." },
    next: "التالي",
  },
  steps: {
    label: "خطوات الحجز",
    stay: "الإقامة",
    addons: "الإضافات",
    travelers: "المسافرون",
    pay: "الدفع",
    change: "تغيير",
    phone: "الخطوة {n} من 4 · {name}",
  },
  addons: {
    title: "صمّم رحلتك",
    intro:
      "أضف ما تشاء. يمكنك أيضًا إضافة التجارب والخدمات بعد الدفع من حسابك.",
    section: "التجارب والخدمات في {destination}",
    count: "{shown} خيارات · {added} مضافة",
    listLabel: "التجارب والخدمات، قائمة قابلة للتمرير",
    filter: {
      label: "تصفية",
      all: "الكل",
      experiences: "التجارب",
      services: "الخدمات",
    },
    kind: { experience: "تجربة", service: "خدمة", serviceUae: "خدمة · الإمارات" },
    unit: { person: "للشخص", night: "لليلة", trip: "للرحلة" },
    add: "أضف",
    added: "أُضيف",
    addName: "أضف {name}",
    addOne: "أضف واحدًا من {name}",
    removeOne: "أزل واحدًا من {name}",
    max: { person: "واحد لكل ضيف", night: "واحد لكل ليلة" },
    empty: {
      all: "لا توجد تجارب أو خدمات هنا بعد.",
      experiences: "لا توجد تجارب هنا بعد.",
      services: "لا توجد خدمات هنا بعد.",
    },
    back: "العودة إلى الإقامة",
    continue: "المتابعة إلى المسافرين",
  },
  inclusions: { title: "مشمول في رحلتك", note: "دون رسوم إضافية" },
  cart: {
    label: "رحلتك",
    kicker: "رحلتك · {destination}",
    stay: {
      zero: "الإقامة · # ليلة",
      one: "الإقامة · ليلة واحدة",
      two: "الإقامة · ليلتان",
      few: "الإقامة · # ليالٍ",
      many: "الإقامة · # ليلة",
      other: "الإقامة · # ليلة",
    },
    addons: {
      zero: "# إضافة",
      one: "إضافة واحدة",
      two: "إضافتان",
      few: "# إضافات",
      many: "# إضافة",
      other: "# إضافة",
    },
    empty: "لم تتم إضافة شيء بعد.",
    remove: "إزالة {name}",
    inclusions: {
      zero: "# ميزة مشمولة",
      one: "ميزة مشمولة واحدة",
      two: "ميزتان مشمولتان",
      few: "# مزايا مشمولة",
      many: "# ميزة مشمولة",
      other: "# ميزة مشمولة",
    },
    included: "مشمول",
    subtotal: "المجموع الفرعي",
    vat: "ضريبة القيمة المضافة [RATE]%",
    total: "الإجمالي",
    note: "لا يُخصم أي مبلغ قبل الدفع. في الخطوة 4 تختار دفع عربون أو الدفع الكامل، في عملية دفع واحدة للإقامة وكل الإضافات.",
    phoneTotal: {
      zero: "الإجمالي · الإقامة + # إضافة",
      one: "الإجمالي · الإقامة + إضافة واحدة",
      two: "الإجمالي · الإقامة + إضافتان",
      few: "الإجمالي · الإقامة + # إضافات",
      many: "الإجمالي · الإقامة + # إضافة",
      other: "الإجمالي · الإقامة + # إضافة",
    },
    continue: "متابعة",
  },
  pay: {
    choice: { error: "اختر دفع عربون أو الدفع الكامل للمتابعة." },
    airport: { error: "اختر مطارك في الإمارات للمتابعة." },
  },
  locale: { language: "اللغة: {name}", currency: "العملة: {code}" },
};

const ES: JourneyCopy = {
  bar: {
    label: "Planea un viaje",
    destination: { label: "Destino", empty: "¿A dónde?" },
    dates: { label: "Fechas", empty: "Agrega fechas", partial: "{start} – Agrega fecha" },
    guests: { label: "Huéspedes" },
    search: "Buscar",
    editSearch: "Editar búsqueda",
    error: {
      both: "Elige un destino y fechas para buscar.",
      destination: "Elige un destino para buscar.",
      dates: "Elige llegada y salida para buscar.",
      phoneDestination: "Elige un destino.",
      phoneDates: "Elige llegada y salida.",
    },
  },
  menu: {
    label: "Elige un destino",
    head: "Un destino por viaje",
    empty: "No hay destinos para mostrar.",
  },
  dates: {
    label: "Elige las fechas",
    prevMonth: "Mes anterior",
    nextMonth: "Mes siguiente",
    line: {
      none: "Elige tu fecha de llegada.",
      start: "Llegada {start}. Ahora elige tu fecha de salida.",
      range: "Llegada {start} · Salida {end} · {nights}",
    },
    nights: { one: "# noche", other: "# noches" },
    day: {
      arrival: "llegada",
      departure: "salida",
      inRange: "en tu estadía",
      unavailable: "no disponible",
      today: "hoy",
    },
    clear: "Borrar fechas",
  },
  done: "Listo",
  guests: {
    label: "Huéspedes",
    adults: "Adultos",
    adultsHint: "13 o más",
    children: "Niños",
    childrenHint: "3–12",
    infants: "Bebés",
    infantsHint: "0–2",
    floor: "Al menos 1 adulto",
    add: "Agregar {group}",
    remove: "Quitar {group}",
    group: { adult: "adulto", child: "niño", infant: "bebé" },
    summary: {
      adults: { one: "# adulto", other: "# adultos" },
      children: { one: "# niño", other: "# niños" },
      infants: { one: "# bebé", other: "# bebés" },
    },
  },
  entry: { title: "Planea tu viaje", hint: "Dónde · Cuándo · Quién" },
  sheet: {
    label: "Planea tu viaje",
    progress: "{n} de 3",
    back: "Atrás",
    close: "Cerrar",
    where: "¿A dónde?",
    when: "¿Cuándo?",
    who: "¿Quién viene?",
    summary: {
      where: "Elige un destino",
      whereHint: "Toca un lugar para continuar",
      whenHint: "Elige la llegada y luego la salida",
      whenStart: "Llegada {start} · elige la salida",
    },
    warn: { where: "Elige un destino.", when: "Elige llegada y salida." },
    next: "Siguiente",
  },
  steps: {
    label: "Pasos de la reserva",
    stay: "Estadía",
    addons: "Extras",
    travelers: "Viajeros",
    pay: "Pago",
    change: "Cambiar",
    phone: "Paso {n} de 4 · {name}",
  },
  addons: {
    title: "Da forma a tu viaje",
    intro:
      "Agrega todos los que quieras. También puedes agregar experiencias y servicios después de pagar, desde tu cuenta.",
    section: "Experiencias y servicios en {destination}",
    count: "{shown} opciones · {added} agregadas",
    listLabel: "Experiencias y servicios, con desplazamiento",
    filter: {
      label: "Filtrar",
      all: "Todos",
      experiences: "Experiencias",
      services: "Servicios",
    },
    kind: { experience: "Experiencia", service: "Servicio", serviceUae: "Servicio · EAU" },
    unit: { person: "por persona", night: "por noche", trip: "por viaje" },
    add: "Agregar",
    added: "Agregado",
    addName: "Agregar {name}",
    addOne: "Agregar uno de {name}",
    removeOne: "Quitar uno de {name}",
    max: { person: "Uno por huésped", night: "Uno por noche" },
    empty: {
      all: "Aún no hay experiencias ni servicios aquí.",
      experiences: "Aún no hay experiencias aquí.",
      services: "Aún no hay servicios aquí.",
    },
    back: "Volver a la estadía",
    continue: "Continuar a viajeros",
  },
  inclusions: { title: "Incluido en tu viaje", note: "Sin costo adicional" },
  cart: {
    label: "Tu viaje",
    kicker: "Tu viaje · {destination}",
    stay: { one: "Estadía · # noche", other: "Estadía · # noches" },
    addons: { one: "# extra", other: "# extras" },
    empty: "Aún no has agregado nada.",
    remove: "Quitar {name}",
    inclusions: { one: "# inclusión", other: "# inclusiones" },
    included: "Incluido",
    subtotal: "Subtotal",
    vat: "IVA [RATE]%",
    total: "Total",
    note: "No se cobra nada antes de Pagar. En el paso 4 eliges un depósito o pagas el total, en un solo pago para la estadía y todos los extras.",
    phoneTotal: { one: "Total · estadía + # extra", other: "Total · estadía + # extras" },
    continue: "Continuar",
  },
  pay: {
    choice: { error: "Elige depósito o pago total para continuar." },
    airport: { error: "Elige tu aeropuerto de EAU para continuar." },
  },
  locale: { language: "Idioma: {name}", currency: "Moneda: {code}" },
};

export const JOURNEY_COPY: Record<JourneyLocale, JourneyCopy> = {
  en: EN,
  ar: AR,
  es: ES,
};
