import { C, MONO, LOGO, icon, ICON_NAMES, code, cap, lab, body, h3, col, row, grid, panel, section, header } from './lib.mjs';

const FOCUS = `outline:2px solid ${C.teal};outline-offset:2px;`;
const UPPER = 'text-transform:{{tt}};letter-spacing:{{ls}};';
const SHADOW_LG = 'box-shadow:0 28px 56px -16px rgb(10 9 7 / 0.28), 0 10px 20px -10px rgb(10 9 7 / 0.12);';

export function surfacesBoard(k) {
  const chipD = (t, gold) => `<span style="display:inline-flex;align-items:center;height:24px;padding:0 8px;box-sizing:border-box;border:1px solid ${gold ? C.gold : C.ink};font-size:12px;color:${C.ink};background:${C.ivory};white-space:nowrap">${t}</span>`;
  const statuses = [
    ['Draft', k('Draft', 'مسودة', 'Borrador'), false], ['Deposit paid', k('Deposit paid', 'تم دفع المقدّم', 'Depósito pagado'), false], ['Confirmed', k('Confirmed', 'مؤكد', 'Confirmado'), true],
    ['In trip', k('In trip', 'في الرحلة', 'En viaje'), false], ['Completed', k('Completed', 'مكتمل', 'Completado'), false], ['Cancelled', k('Cancelled', 'ملغى', 'Cancelado'), false],
    ['Driver assigned', k('Driver assigned', 'تم تعيين السائق', 'Conductor asignado'), false], ['Flights booked', k('Flights booked', 'تم حجز الرحلات الجوية', 'Vuelos reservados'), false],
  ];
  const chips = panel(col(16, row(12, statuses.map(([, t, g]) => chipD(t, g)).join(''), 'flex-wrap:wrap') + cap(k('Ivory surface, charcoal text, 1px charcoal hairline. Confirmed has a gold hairline. The word carries the status, not the colour.', 'سطح عاجي ونص فحمي وخط رفيع ١ بكسل. «مؤكد» بخط ذهبي. الكلمة هي التي تحمل الحالة وليس اللون.', 'Superficie marfil, texto carbón, línea de 1 px. Confirmado lleva línea dorada. La palabra transmite el estado, no el color.'))));

  // Dialog + toast
  const closeBtn = `<span style="display:flex;align-items:center;justify-content:center;width:44px;height:44px;color:${C.teal}">${icon('x', 20, C.teal)}</span>`;
  const pbtn = (t, style) => `<span style="display:inline-flex;align-items:center;justify-content:center;height:44px;padding:0 24px;box-sizing:border-box;font-size:14px;${style}">${t}</span>`;
  const dialog = `<div style="background:rgba(38,38,38,0.4);padding:48px;display:flex;align-items:center;justify-content:center">
<div role="dialog" aria-label="${k('Sign out', 'تسجيل الخروج', 'Cerrar sesión')}" style="width:480px;max-width:100%;background:${C.surface};${SHADOW_LG}padding:24px;box-sizing:border-box;display:flex;flex-direction:column;gap:16px">
<div style="display:flex;align-items:flex-start;justify-content:space-between;gap:16px"><h3 style="margin:0;font-family:{{fd}};font-weight:400;font-size:20px;line-height:{{lhT}};color:${C.teal}">${k('Sign out of this account?', 'هل تريد تسجيل الخروج من هذا الحساب؟', '¿Cerrar sesión en esta cuenta?')}</h3>${closeBtn}</div>
<p style="margin:0;font-size:16px;line-height:{{lhB}};color:${C.ink}">${k('You will need to sign in again to open bookings.', 'ستحتاج إلى تسجيل الدخول مجددًا لفتح الحجوزات.', 'Tendrás que iniciar sesión de nuevo para abrir las reservas.')}</p>
<div style="display:flex;justify-content:flex-end;gap:16px">${pbtn(k('Cancel', 'إلغاء', 'Cancelar'), `color:${C.teal};`)}${pbtn(k('Sign out', 'تسجيل الخروج', 'Cerrar sesión'), `border:1px solid ${C.error};color:${C.ink};`)}</div></div></div>`;
  const toast = (ic, t, role) => `<div role="${role}" style="display:flex;align-items:center;gap:12px;background:${C.surface};${SHADOW_LG}padding:12px 8px 12px 16px;box-sizing:border-box;min-height:56px"><span style="display:flex">${ic}</span><span style="flex:1;font-size:14px;line-height:{{lhL}};color:${C.ink}">${t}</span>${closeBtn}</div>`;
  const overlays = grid(2, 24,
    col(12, cap(k('Dialog · scrim is charcoal at 40%. Confirm dialogs do not close on scrim or Escape.', 'حوار · الستار فحمي بنسبة ٤٠٪. حوارات التأكيد لا تُغلق بالنقر خارجها أو بمفتاح Escape.', 'Diálogo · el fondo es carbón al 40 %. Los de confirmación no se cierran con el fondo ni con Escape.')) + dialog) +
    col(16, cap(k('Toast · dismisses after 4 seconds, pauses on hover or focus, keeps a dismiss control.', 'إشعار · يختفي بعد ٤ ثوانٍ ويتوقف عند التمرير أو التركيز مع بقاء زر الإغلاق.', 'Aviso · se cierra a los 4 s, se pausa con hover o foco y conserva su botón de cierre.')) +
      toast(icon('check', 20, C.success), k('[Toast message]', '[نص الإشعار]', '[Mensaje del aviso]'), 'status') +
      toast(icon('alert-circle', 20, C.error), k('This page did not load. Try again.', 'تعذّر تحميل هذه الصفحة. حاول مرة أخرى.', 'Esta página no se cargó. Inténtalo de nuevo.'), 'alert')));

  // Nav
  const NAV = [k('Destinations', 'الوجهات', 'Destinos'), k('Experiences', 'التجارب', 'Experiencias'), k('About', 'من نحن', 'Nosotros'), k('Contact', 'اتصل بنا', 'Contacto')];
  const LOGIN = k('Login', 'تسجيل الدخول', 'Iniciar sesión');
  const trig = (c) => `<span style="display:inline-flex;align-items:center;gap:8px;height:44px;padding:0 16px;box-sizing:border-box;border:1px solid ${C.muted};color:${C.ink};font-size:12px;${UPPER}"><bdi>${c}</bdi>${icon('chevron-down', 12, 'currentColor')}</span>`;
  const navLink = (t, active) => `<span style="display:inline-flex;align-items:center;height:44px;font-size:12px;${UPPER}color:${C.teal};${active ? `border-bottom:2px solid ${C.gold};box-sizing:border-box;` : ''}">${t}</span>`;
  const logo = (w) => `<img src="${LOGO}" alt="ALMAR Private Journeys" style="width:${w}px;height:auto;display:block">`;
  const cartB = (n) => `<span role="img" aria-label="${k('Cart', 'السلة', 'Carrito')}" style="position:relative;display:inline-flex;align-items:center;justify-content:center;width:44px;height:44px;color:${C.teal}">${icon('cart', 24, C.teal)}${n ? `<span style="position:absolute;top:2px;inset-inline-end:0;min-width:20px;height:20px;padding:0 4px;box-sizing:border-box;background:${C.teal};color:${C.ivory};font-size:12px;line-height:20px;text-align:center;font-variant-numeric:tabular-nums">${n}</span>` : ''}</span>`;
  const acctB = (open) => `<span style="display:inline-flex;align-items:center;gap:8px;height:44px;padding:0 12px 0 16px;box-sizing:border-box;border:1px solid ${open ? C.ink : C.muted};font-size:14px;color:${C.ink}"><span>${k('[Guest name]', '[اسم الضيف]', '[Nombre del huésped]')}</span>${icon(open ? 'chevron-up' : 'chevron-down', 12, 'currentColor')}</span>`;
  const navBar = (right) => `<div style="display:flex;align-items:center;justify-content:space-between;gap:24px;background:${C.ivory};border-bottom:1px solid ${C.line};padding:16px 32px;box-sizing:border-box">
${logo(150)}<nav style="display:flex;align-items:center;gap:32px">${navLink(NAV[0], true)}${navLink(NAV[1])}${navLink(NAV[2])}${navLink(NAV[3])}</nav>
<div style="display:flex;align-items:center;gap:16px">${right}</div></div>`;
  const navDesktop = navBar(`${cartB(0)}${trig('AED')}${trig('EN')}${navLink(LOGIN)}`);
  const navIn = navBar(`${cartB(2)}${trig('AED')}${trig('EN')}${acctB(false)}`);
  const acctItems = [k('Bookings', 'الحجوزات', 'Reservas'), k('Profile', 'الملف الشخصي', 'Perfil'), k('Saved travelers', 'المسافرون المحفوظون', 'Viajeros guardados'), k('Saved stays', 'الإقامات المحفوظة', 'Estancias guardadas'), k('Preferences', 'التفضيلات', 'Preferencias')];
  const acctMenu = `<div role="menu" style="width:288px;background:${C.surface};box-shadow:0 28px 56px -16px rgb(10 9 7 / 0.28), 0 10px 20px -10px rgb(10 9 7 / 0.12);display:flex;flex-direction:column"><div style="display:flex;flex-direction:column;padding:16px;border-bottom:1px solid ${C.line}"><span style="font-size:14px;color:${C.ink}">${k('[Guest name]', '[اسم الضيف]', '[Nombre del huésped]')}</span><span style="font-size:12px;line-height:{{lhC}};color:${C.muted}"><bdi>${k('[Email]', '[البريد]', '[Correo]')}</bdi></span></div>${acctItems.map((t2, i) => `<span role="menuitem" style="display:flex;align-items:center;min-height:44px;padding:0 16px;font-size:14px;color:${C.ink};background:${i === 0 ? C.ivory : C.surface}">${t2}</span>`).join('')}<div style="border-top:1px solid ${C.line}"><span role="menuitem" style="display:flex;align-items:center;min-height:44px;padding:0 16px;font-size:14px;color:${C.ink}">${k('Need help?', 'تحتاج مساعدة؟', '¿Necesitas ayuda?')}</span><span role="menuitem" style="display:flex;align-items:center;min-height:44px;padding:0 16px;font-size:14px;color:${C.ink}">${k('Sign out', 'تسجيل الخروج', 'Cerrar sesión')}</span></div></div>`;
  const navOpen = `<div style="position:relative;height:420px">${navBar(`${cartB(2)}${trig('AED')}${trig('EN')}${acctB(true)}`)}<div style="position:absolute;top:80px;inset-inline-end:32px">${acctMenu}</div></div>`;
  const menuBtn = `<span style="display:inline-flex;align-items:center;height:44px;padding:0 16px;box-sizing:border-box;border:1px solid ${C.muted};font-size:14px;color:${C.ink}">${k('Menu', 'القائمة', 'Menú')}</span>`;
  const phoneClosed = `<div style="width:390px;box-sizing:border-box;background:${C.ivory};border:1px solid ${C.line}"><div style="display:flex;align-items:center;justify-content:space-between;padding:16px;border-bottom:1px solid ${C.line}">${logo(112)}<div style="display:flex;align-items:center;gap:8px">${cartB(0)}${menuBtn}</div></div>
<div style="height:120px;padding:16px;font-size:12px;color:${C.muted}">${cap(k('Wordmark at every width. Menu opens a full-screen list.', 'الشعار النصي بكل العروض. القائمة تفتح لائحة بملء الشاشة.', 'Logotipo en todos los anchos. Menú abre una lista a pantalla completa.'))}</div></div>`;
  const phoneOpen = `<div style="width:390px;box-sizing:border-box;background:${C.ivory};border:1px solid ${C.line}"><div style="display:flex;align-items:center;justify-content:space-between;padding:16px;border-bottom:1px solid ${C.line}">${logo(112)}${closeBtn}</div>
<div style="display:flex;flex-direction:column;padding:8px 16px 24px">${NAV.map((t) => `<span style="display:flex;align-items:center;min-height:56px;border-bottom:1px solid ${C.line};font-size:14px;${UPPER}color:${C.teal}">${t}</span>`).join('')}<div style="display:flex;gap:16px;padding-top:16px">${trig('AED')}${trig('EN')}</div></div></div>`;
  const nav = col(24, cap(k('Desktop. Active link has a 2px gold rule. The stacked charcoal lockup replaces this wordmark in the build (plan 06). The mark is never mirrored in Arabic.', 'سطح المكتب. الرابط النشط بخط ذهبي ٢ بكسل. الشعار المتراص الفحمي يحل محل هذا الشعار عند البناء (الخطة ٠٦). لا يُعكس الشعار في العربية.', 'Escritorio. El enlace activo lleva una regla dorada de 2 px. El logotipo apilado carbón sustituye a este en la compilación (plan 06). El logotipo no se refleja en árabe.')) + navDesktop +
    cap(k('Signed in: the account menu replaces Login. Cart shows a count.', 'بعد تسجيل الدخول: تحل قائمة الحساب محل «دخول». تعرض السلة العدد.', 'Con sesión: el menú de cuenta sustituye a Entrar. El carrito muestra el número.')) + navIn +
    cap(k('Signed in: account menu open.', 'بعد تسجيل الدخول: قائمة الحساب مفتوحة.', 'Con sesión: menú de cuenta abierto.')) + navOpen +
    row(48, `<div style="display:flex;flex-direction:column;gap:8px">${cap(k('Phone · closed', 'الهاتف · مغلق', 'Teléfono · cerrado'))}${phoneClosed}</div><div style="display:flex;flex-direction:column;gap:8px">${cap(k('Phone · menu open, teal X close', 'الهاتف · القائمة مفتوحة وزر إغلاق X أخضر مزرق', 'Teléfono · menú abierto, cierre X verde azulado'))}${phoneOpen}</div>`, 'align-items:flex-start'));

  // Footer
  const fld = `<span style="display:flex;align-items:center;flex:1;height:44px;padding:0 16px;box-sizing:border-box;background:${C.surface};border:1px solid ${C.ink};font-size:14px;color:${C.muted}">${k('Email', 'البريد الإلكتروني', 'Correo electrónico')}</span>`;
  const footer = `<div style="background:${C.ivory};border-top:1px solid ${C.line};border-bottom:1px solid ${C.line};padding:48px 32px;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:32px">
<div style="display:flex;flex-direction:column;gap:16px">${logo(150)}<a href="https://instagram.com/almarprivatejourney/" style="font-size:14px;color:${C.teal};min-height:44px;display:flex;align-items:center">Instagram</a></div>
<div style="display:flex;flex-direction:column">${NAV.map((t) => `<a href="#" style="display:flex;align-items:center;min-height:44px;font-size:12px;${UPPER}color:${C.teal};text-decoration:none">${t}</a>`).join('')}</div>
<div style="display:flex;flex-direction:column;gap:8px"><a href="#" style="display:flex;align-items:center;min-height:44px;font-size:14px;color:${C.teal};text-decoration:none">${k('List with us', 'أدرج معنا', 'Publica con nosotros')}</a><bdi style="font-size:14px;color:${C.ink}">inquiries@almarprivatejourney.com</bdi><bdi style="font-size:14px;color:${C.ink}">+971 56 388 3302</bdi></div>
<div style="display:flex;gap:8px;align-items:flex-start">${fld}<span style="display:inline-flex;align-items:center;justify-content:center;height:44px;padding:0 16px;box-sizing:border-box;border:1px solid ${C.teal};color:${C.teal};font-size:12px;${UPPER}">${k('Subscribe', 'اشترك', 'Suscribirse')}</span></div></div>`;

  // Sidebar + table + stat
  const rowItem = (t, s, extra = '', trail = '', as = 'div', attrs = '') => `<${as} ${attrs} style="display:flex;align-items:center;justify-content:space-between;gap:8px;min-height:44px;padding:0 8px;box-sizing:border-box;font-size:14px;width:100%;border:0;font-family:inherit;text-align:start;background:${s === 'sel' ? C.tealTint : s === 'hover' ? C.ivory : 'transparent'};color:${s === 'sel' || s === 'open' ? C.teal : C.ink};${s === 'focus' ? FOCUS : ''}${extra}"><span>${t}</span>${trail}</${as}>`;
  const HOME = k('Home', 'الرئيسية', 'Inicio'), BOOK = k('Bookings', 'الحجوزات', 'Reservas'), CAL = k('Calendar', 'التقويم', 'Calendario'), CAT = k('Catalog', 'الفهرس', 'Catálogo'), CONT = k('Content', 'المحتوى', 'Contenido'), CUST = k('Customers', 'العملاء', 'Clientes'), PROF = k('Profile', 'الملف الشخصي', 'Perfil'), SET = k('Settings', 'الإعدادات', 'Ajustes');
  const subs = [[k('Destinations', 'الوجهات', 'Destinos'), 'rest'], [k('Experiences', 'التجارب', 'Experiencias'), 'rest'], [k('Packages', 'الباقات', 'Paquetes'), 'rest'], [k('Stays', 'الإقامات', 'Estancias'), 'sel']];
  const catRow = (open, s) => rowItem(CAT, s, '', icon(open ? 'chevron-up' : 'chevron-down', 16, C.teal), 'button', `type="button" aria-expanded="${open}" aria-controls="catalog-sub"`);
  const subGroup = `<div id="catalog-sub" role="group" aria-label="${CAT}" style="display:flex;flex-direction:column;border-inline-start:1px solid ${C.line};margin-inline-start:16px">${subs.map(([t, s]) => rowItem(t, s, 'padding-inline-start:16px;')).join('')}</div>`;
  const others = (a2) => a2.map((t) => rowItem(t, 'rest')).join('');
  const sbox = (inner) => `<div style="width:240px;background:${C.surface};border:1px solid ${C.line};padding:8px 0;display:flex;flex-direction:column;box-sizing:border-box">${inner}</div>`;
  const sidebarClosed = col(8, cap(k('Catalog closed. The chevron points down.', 'الفهرس مغلق. السهم يشير للأسفل.', 'Catálogo cerrado. La flecha apunta abajo.')) +
    sbox(rowItem(HOME, 'rest') + rowItem(BOOK, 'sel') + rowItem(CAL, 'hover') + catRow(false, 'rest') + others([CONT, CUST, PROF, SET])));
  const sidebarOpen = col(8, cap(k('Catalog open. Its pages drop down below it. The current page is teal tint.', 'الفهرس مفتوح. صفحاته تنسدل تحته. الصفحة الحالية بلون أخضر مزرق فاتح.', 'Catálogo abierto. Sus páginas se despliegan debajo. La página actual va en tinte verde azulado.')) +
    sbox(rowItem(HOME, 'rest') + rowItem(BOOK, 'rest') + rowItem(CAL, 'rest') + catRow(true, 'open') + subGroup + others([CONT, CUST, PROF, SET])));
  const sidebar = row(24, sidebarClosed + sidebarOpen, 'align-items:flex-start');
  const trow = (h, hdr) => `<div style="display:grid;grid-template-columns:minmax(0,1.2fr) minmax(0,1.6fr) 150px 150px;align-items:center;column-gap:16px;height:${h}px;padding:0 16px;box-sizing:border-box;border-bottom:1px solid ${C.line};background:${C.surface};font-size:14px;${hdr ? `color:${C.muted};font-size:12px;${UPPER}` : ''}">
${hdr ? `<span>${k('Guest', 'الضيف', 'Huésped')}</span><span>${k('Dates', 'التواريخ', 'Fechas')}</span><span>${k('Status', 'الحالة', 'Estado')}</span><span>${k('Ref', 'المرجع', 'Ref.')}</span>` : `<span>${k('[Guest name]', '[اسم الضيف]', '[Nombre del huésped]')}</span><bdi style="font-variant-numeric:tabular-nums">12/10/2026 – 17/10/2026</bdi>${chipD(statuses[2][1], true)}<bdi style="font-variant-numeric:tabular-nums">ALMAR-000000</bdi>`}</div>`;
  const stat = (lab_) => `<div style="background:${C.surface};border:1px solid ${C.line};padding:16px;display:flex;flex-direction:column;gap:4px;min-width:200px"><span style="font-size:12px;line-height:{{lhC}};${UPPER}color:${C.muted}">${lab_}</span><span style="font-size:32px;line-height:1.2;font-variant-numeric:tabular-nums;color:${C.ink}">[00]</span></div>`;
  const dash = col(32, sidebar + col(24, row(16, stat(k('Bookings', 'الحجوزات', 'Reservas')) + stat(k('Customers', 'العملاء', 'Clientes'))) +
    col(8, cap(k('Table · comfortable 56px', 'جدول · مريح ٥٦ بكسل', 'Tabla · cómoda 56 px')) + `<div style="border-top:1px solid ${C.line}">${trow(44, true)}${trow(56)}${trow(56)}</div>` +
      cap(k('Table · dense 44px (still a 44px hit target)', 'جدول · كثيف ٤٤ بكسل (منطقة لمس ٤٤ بكسل)', 'Tabla · densa 44 px (área táctil de 44 px)')) + `<div style="border-top:1px solid ${C.line}">${trow(44)}${trow(44)}</div>`), 'min-width:0'));

  // Icons
  const acc = { search: 'Search', check: 'Check', plus: 'Add', minus: 'Remove', x: 'Close', 'chevron-right': 'Next', 'chevron-down': 'Open', 'chevron-up': 'Collapse', 'arrow-right': 'Continue', 'alert-circle': 'Alert', mail: 'Email', heart: 'Saved', eye: 'Show password', 'eye-off': 'Hide password', spinner: 'Busy' };
  const flips = new Set(['search', 'chevron-right', 'arrow-right']);
  const icons = grid(5, 16, ICON_NAMES.map((n) => `<div style="display:flex;flex-direction:column;gap:8px;align-items:flex-start;background:${C.surface};border:1px solid ${C.line};padding:16px;box-sizing:border-box"><span style="color:${n === 'alert-circle' ? C.error : C.teal};display:flex;gap:12px;align-items:center">${icon(n, 16)}${icon(n, 20, undefined, flips.has(n))}${icon(n, 24, undefined, false, n === 'heart' ? C.teal : 'none')}</span>${code(n, C.ink)}${flips.has(n) ? cap(k('Flips in RTL', 'ينعكس في العربية', 'Se invierte en RTL')) : cap(k('Does not flip', 'لا ينعكس', 'No se invierte'))}</div>`).join(''));
  const names = [['Close', 'إغلاق', 'Cerrar'], ['Previous month', 'الشهر السابق', 'Mes anterior'], ['Next month', 'الشهر التالي', 'Mes siguiente'], ['Add adult', 'إضافة بالغ', 'Añadir adulto'], ['Remove adult', 'إزالة بالغ', 'Quitar adulto'], ['Show password', 'إظهار كلمة المرور', 'Mostrar contraseña'], ['Hide password', 'إخفاء كلمة المرور', 'Ocultar contraseña']];
  const nameTable = panel(col(4, cap(k('Accessible names for icon-only controls', 'الأسماء الميسّرة لعناصر التحكم ذات الأيقونة فقط', 'Nombres accesibles de controles solo con icono')) + names.map(([en, ar, es]) => `<div style="font-size:14px;line-height:{{lhL}};color:${C.ink}">${k(en, ar, es)}</div>`).join('')) + cap(k('16px inline, 20px inside a button, 24px standing alone. currentColor. Decorative icons are aria-hidden.', '١٦ بكسل داخل النص و٢٠ داخل الزر و٢٤ بمفردها. currentColor. الأيقونات الزخرفية aria-hidden.', '16 px en línea, 20 px dentro de un botón, 24 px solo. currentColor. Los iconos decorativos son aria-hidden.')), 'margin-top:0');

  const bodyHtml = header(k,
    k('ALMAR design system · Components · 2 of 2', 'نظام تصميم ألمار · المكوّنات · ٢ من ٢', 'Sistema de diseño ALMAR · Componentes · 2 de 2'),
    k('Surfaces and navigation', 'الأسطح والتنقل', 'Superficies y navegación'),
    k('Status chips, dialog, toast, navigation, footer, and the dense dashboard pieces. All sample data uses brackets. No people, no invented amounts.', 'رقاقات الحالة والحوار والإشعار والتنقل والتذييل وعناصر لوحة التحكم الكثيفة. كل البيانات النموذجية بأقواس. لا أشخاص ولا مبالغ مخترعة.', 'Chips de estado, diálogo, aviso, navegación, pie y piezas densas del panel. Todos los datos de muestra van entre corchetes. Sin personas ni importes inventados.')) +
    section(k('Status chip', 'رقاقة الحالة', 'Chip de estado'), '', chips) +
    section(k('Dialog and toast', 'الحوار والإشعار', 'Diálogo y aviso'), '', overlays) +
    section(k('Navigation', 'التنقل', 'Navegación'), '', nav) +
    section(k('Footer', 'التذييل', 'Pie de página'), k('Contact stays inquiries@almarprivatejourney.com and +971 56 388 3302.', 'التواصل يبقى inquiries@almarprivatejourney.com و ‎+971 56 388 3302.', 'El contacto sigue siendo inquiries@almarprivatejourney.com y +971 56 388 3302.'), footer) +
    section(k('Dashboard: sidebar, stat, table row', 'لوحة التحكم: الشريط الجانبي والإحصاء وصف الجدول', 'Panel: barra lateral, cifra y fila de tabla'), '', dash) +
    section(k('Icons', 'الأيقونات', 'Iconos'), '', icons + nameTable);
  return { bodyHtml, w: 1440, h: 6700, title: 'Components · Surfaces' };
}
