import fs from 'node:fs';
import { C, icon, LOGO } from './lib.mjs';
import { B } from './public.mjs';

const UP = 'text-transform:{{tt}};letter-spacing:{{ls}};';
const LG = 'box-shadow:0 28px 56px -16px rgb(10 9 7 / 0.28), 0 10px 20px -10px rgb(10 9 7 / 0.12);';
const WD = { d: 1440, t: 834, p: 390 };

export function dashBoard(stem, k, DC) {
  const d = (path) => { const f = (l) => path.split('.').reduce((o, p) => o[p], DC[l]); return k(f('en'), f('ar'), f('es')); };
  const t = (en, ar, es) => k(en, ar ?? en, es ?? en);
  const bdiN = (s) => `<bdi style="font-variant-numeric:tabular-nums">${s}</bdi>`;
  const GUEST = t('[Guest name]', '[اسم الضيف]', '[Nombre del huésped]');
  const EM = t('[Email]', '[البريد]', '[Correo]');
  const PHONE = t('[Phone]', '[الهاتف]', '[Teléfono]');
  const NAME = t('[Name]', '[الاسم]', '[Nombre]');
  const STAYN = t('[Stay name]', '[اسم الإقامة]', '[Nombre de la estancia]');
  const DESTN = t('[Destination]', '[الوجهة]', '[Destino]');
  const AMT = bdiN('AED [AMOUNT]'), PRICE = bdiN('AED [PRICE]'), REF = bdiN('ALMAR-000000'), DT = bdiN('[DD/MM/YYYY]'), DTS = bdiN('[DD/MM/YYYY] – [DD/MM/YYYY]'), N = bdiN('[00]');
  const chip = (en, ar, es, gold) => `<span style="display:inline-flex;align-items:center;height:24px;padding:0 8px;box-sizing:border-box;border:1px solid ${gold ? C.gold : C.ink};font-size:12px;color:${C.ink};background:${C.ivory};white-space:nowrap">${t(en, ar, es)}</span>`;
  const ST = { conf: () => chip('Confirmed', 'مؤكد', 'Confirmado', true), dep: () => chip('Deposit paid', 'تم دفع المقدّم', 'Depósito pagado'), draft: () => chip('Draft', 'مسودة', 'Borrador'), req: () => chip('Cancellation requested', 'تم طلب الإلغاء', 'Cancelación solicitada'), done: () => chip('Completed', 'مكتمل', 'Completado'), pub: () => chip('Published', 'منشور', 'Publicado', true), cancelled: () => chip('Cancelled', 'ملغى', 'Cancelado'), soon: () => chip('Soon', 'قريبًا', 'Pronto'), ro: () => chip('Read-only', 'للقراءة فقط', 'Solo lectura'), exp: () => chip('Experience', 'تجربة', 'Experiencia'), svc: () => chip('Service', 'خدمة', 'Servicio') };
  const mix = (i) => [ST.conf, ST.dep, ST.req, ST.done, ST.draft][i % 5]();
  const btnP = (s, o = {}) => `<span style="display:inline-flex;align-items:center;justify-content:center;gap:8px;height:${o.h || 44}px;padding:0 24px;box-sizing:border-box;background:${C.teal};color:${C.ivory};font-size:14px;${UP}flex:none;${o.w ? `width:${o.w};` : ''}">${o.plus ? icon('plus', 16, C.ivory) : ''}${s}</span>`;
  const btnS = (s, o = {}) => `<span style="display:inline-flex;align-items:center;justify-content:center;gap:8px;height:44px;padding:0 24px;box-sizing:border-box;border:1px solid ${C.teal};color:${C.teal};font-size:14px;${UP}flex:none;${o.w ? `width:${o.w};` : ''}">${o.plus ? icon('plus', 16, C.teal) : ''}${s}</span>`;
  const btnG = (s, color) => `<span style="display:inline-flex;align-items:center;min-height:44px;padding:0 8px;font-size:14px;color:${color || C.teal};flex:none">${s}</span>`;
  const btnD = (s) => `<span style="display:inline-flex;align-items:center;justify-content:center;height:44px;padding:0 24px;box-sizing:border-box;border:1px solid ${C.error};color:${C.ink};font-size:14px;flex:none">${s}</span>`;
  const cap = (s, color) => `<span style="font-size:12px;line-height:{{lhC}};color:${color || C.muted}">${s}</span>`;
  const lab = (s) => `<span style="font-size:14px;line-height:{{lhL}};color:${C.ink}">${s}</span>`;
  const trig = (s, w) => `<span style="display:inline-flex;align-items:center;justify-content:space-between;gap:8px;height:44px;${w ? `width:${w};` : ''}padding:0 16px;box-sizing:border-box;border:1px solid ${C.muted};color:${C.ink};font-size:14px;background:${C.surface}"><span style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${s}</span>${icon('chevron-down', 12, 'currentColor')}</span>`;
  const field = (label, value, w, o = {}) => `<div style="display:flex;flex-direction:column;gap:8px;${w ? `width:${w}` : 'width:100%'};min-width:0"><span style="font-size:14px;line-height:{{lhL}};color:${C.ink}">${label}</span><span style="display:flex;align-items:${o.area ? 'flex-start' : 'center'};${o.area ? `height:${o.area}px;padding:12px 16px;` : 'height:44px;padding:0 16px;'}box-sizing:border-box;background:${o.ro ? C.ivory : C.surface};border:1px solid ${o.ro ? C.line : C.ink};font-size:14px;color:${value ? C.ink : C.muted}"><bdi>${value || ''}</bdi></span></div>`;
  const ro = (label, value) => `<div style="display:flex;flex-direction:column;gap:4px;min-width:0"><span style="font-size:12px;line-height:{{lhC}};${UP}color:${C.muted}">${label}</span><span style="font-size:14px;line-height:{{lhL}};color:${C.ink}">${value}</span></div>`;
  const search = (w, ph) => `<span style="display:flex;align-items:center;gap:8px;height:44px;${w ? `width:${w}px;` : 'width:100%;'}box-sizing:border-box;padding:0 16px;background:${C.surface};border:1px solid ${C.ink};font-size:14px;color:${C.muted};flex:none">${icon('search', 20, C.teal, true)}<span>${ph || t('Search', 'بحث', 'Buscar')}</span></span>`;
  const tab = (s, on, n) => `<span style="display:inline-flex;align-items:center;gap:8px;min-height:44px;padding:0 16px;font-size:14px;color:${on ? C.teal : C.muted};box-shadow:${on ? `inset 0 -3px 0 ${C.teal}` : 'none'};white-space:nowrap">${s}${n ? `<span style="min-width:20px;height:20px;padding:0 4px;box-sizing:border-box;background:${C.teal};color:${C.ivory};font-size:12px;line-height:20px;text-align:center">${n}</span>` : ''}</span>`;
  const tabs = (arr) => `<div role="tablist" style="display:flex;border-bottom:1px solid ${C.line};overflow:hidden;flex:none">${arr.map(([s, on, n]) => tab(s, on, n)).join('')}</div>`;
  const chipBtn = (s, on, i) => `<span style="display:inline-flex;align-items:center;height:40px;padding:0 16px;box-sizing:border-box;margin-inline-start:${i ? -1 : 0}px;background:${on ? C.teal : 'transparent'};color:${on ? C.ivory : C.ink};border:1px solid ${on ? C.teal : C.muted};font-size:14px;white-space:nowrap">${s}</span>`;
  const seg = (arr, compact) => `<div role="group" style="display:flex;flex:none">${arr.map(([s, on], i) => chipBtn(s, on, i).replace('padding:0 16px', compact ? 'padding:0 12px' : 'padding:0 16px')).join('')}</div>`;
  const range = (compact) => seg([[d('thisMonth'), true], [d('last30'), false], [d('custom'), false]], compact);
  const check = (on) => `<span style="display:flex;align-items:center;justify-content:center;width:20px;height:20px;box-sizing:border-box;background:${on ? C.teal : C.surface};border:1px solid ${on ? C.teal : C.ink};flex:none">${on ? icon('check', 16, C.ivory) : ''}</span>`;
  const sw = (on) => `<span style="display:flex;align-items:center;justify-content:${on ? 'flex-end' : 'flex-start'};width:44px;height:24px;padding:3px;box-sizing:border-box;background:${on ? C.teal : C.surface};border:1px solid ${on ? C.teal : C.ink};flex:none"><span style="width:16px;height:16px;background:${on ? C.ivory : C.ink};display:block"></span></span>`;
  const stat = (label, val, delta) => `<div style="background:${C.surface};border:1px solid ${C.line};padding:16px;display:flex;flex-direction:column;gap:4px;box-sizing:border-box;min-width:0"><span style="font-size:12px;line-height:{{lhC}};${UP}color:${C.muted}">${label}</span><span style="font-size:32px;line-height:1.2;font-variant-numeric:tabular-nums;color:${C.ink}">${val}</span>${delta ? cap(delta) : ''}</div>`;
  const card = (title, inner, o = {}) => `<section style="background:${C.surface};border:1px solid ${C.line};padding:24px;display:flex;flex-direction:column;gap:16px;box-sizing:border-box;min-width:0;${o.style || ''}"><div style="display:flex;align-items:center;justify-content:space-between;gap:12px"><h2 style="margin:0;font-family:{{fd}};font-weight:400;font-size:20px;line-height:{{lhT}};color:${C.teal}">${title}</h2>${o.action || ''}</div>${inner}</section>`;
  const grid = (n, gap, inner, extra = '') => `<div style="display:grid;grid-template-columns:repeat(${n},minmax(0,1fr));gap:${gap}px;${extra}">${inner}</div>`;
  const col = (gap, inner, extra = '') => `<div style="display:flex;flex-direction:column;gap:${gap}px;min-width:0;${extra}">${inner}</div>`;
  const row = (gap, inner, extra = '') => `<div style="display:flex;align-items:center;gap:${gap}px;${extra}">${inner}</div>`;
  const thumb = (src, w = 64, h = 48) => `<img src="${src}" alt="" style="width:${w}px;height:${h}px;object-fit:cover;display:block;flex:none">`;
  const IM = [B.stay, B.walled, B.heritage, B.rosario];
  const bgt = (n, s) => `<span style="min-width:20px;height:20px;padding:0 4px;box-sizing:border-box;background:${C.tealTint};color:${C.teal};font-size:12px;line-height:20px;text-align:center">${s}</span>`;

  // ---- data table with phone card fallback ----
  // cols: [{h, w, p:false (hide on phone), t:false (hide on tablet), title:true (phone title)}]
  const table = (cls, cols, rows, o = {}) => {
    const vis = cols.map((c2, i) => ({ ...c2, i })).filter((c2) => (cls === 'p' ? c2.p !== false : cls === 't' ? c2.t !== false : true));
    if (cls === 'p') {
      return `<div style="display:flex;flex-direction:column;gap:12px">${rows.map((r) => `<div style="background:${C.surface};border:1px solid ${C.line};padding:16px;display:flex;flex-direction:column;gap:8px;box-sizing:border-box"><div style="display:flex;align-items:center;justify-content:space-between;gap:12px;font-size:14px;color:${C.ink}">${vis.filter((c2) => c2.first).map((c2) => r[c2.i]).join('') || r[vis[0].i]}</div>${grid(2, 8, vis.filter((c2) => !c2.first && c2.i !== vis[0].i).map((c2) => `<div style="display:flex;flex-direction:column;gap:2px;min-width:0">${cap(c2.h)}<span style="font-size:14px;color:${C.ink};min-width:0">${r[c2.i]}</span></div>`).join(''), 'align-items:start')}</div>`).join('')}</div>`;
    }
    const tpl = vis.map((c2) => c2.w || 'minmax(0,1fr)').join(' ');
    const h = o.tall ? 64 : 44;
    return `<div style="border:1px solid ${C.line};background:${C.surface}"><div style="display:grid;grid-template-columns:${tpl};column-gap:16px;align-items:center;height:44px;padding:0 16px;border-bottom:1px solid ${C.line};font-size:12px;${UP}color:${C.muted}">${vis.map((c2) => `<span>${c2.h}</span>`).join('')}</div>${rows.map((r, ri) => `<div style="display:grid;grid-template-columns:${tpl};column-gap:16px;align-items:center;min-height:${h}px;padding:0 16px;border-bottom:1px solid ${C.line};font-size:14px;color:${C.ink};${o.sel === ri ? `background:${C.tealTint};` : ''}">${vis.map((c2) => `<span style="min-width:0;overflow:hidden;text-overflow:ellipsis">${r[c2.i]}</span>`).join('')}</div>`).join('')}</div>`;
  };
  const emptyState = (line, action, note) => `<div style="border:1px solid ${C.line};background:${C.surface};padding:48px 24px;display:flex;flex-direction:column;align-items:center;gap:16px;text-align:center"><span style="font-family:{{fd}};font-size:20px;line-height:{{lhT}};color:${C.teal}">${line}</span>${note ? cap(note) : ''}${action || ''}</div>`;
  const rowsN = (n, fn) => Array.from({ length: n }, (_, i) => fn(i));

  // ---- shell ----
  const NAVI = (active) => {
    const it = (s, on, sub, extra) => `<span style="display:flex;align-items:center;justify-content:space-between;min-height:44px;padding:0 ${sub ? 32 : 16}px;font-size:14px;background:${on ? C.tealTint : 'transparent'};color:${on ? C.teal : C.ink}"><span>${s}</span>${extra || ''}</span>`;
    const grp = (s, open, subs) => `<div style="display:flex;flex-direction:column"><span style="display:flex;align-items:center;justify-content:space-between;min-height:44px;padding:0 16px;font-size:14px;color:${open ? C.teal : C.ink}"><span>${s}</span>${icon(open ? 'chevron-up' : 'chevron-down', 16, C.teal)}</span>${open ? subs.map(([s2, a, x]) => it(s2, a === active, true, x)).join('') : ''}</div>`;
    const cat = ['destinations', 'stays', 'services', 'packages'].includes(active), con = ['content', 'pages', 'blog', 'team', 'legal', 'media', 'navigation'].includes(active);
    return `<nav aria-label="${d('menu')}" style="display:flex;flex-direction:column;padding:8px 0">${it(d('rail.home'), active === 'home')}${it(d('rail.bookings'), ['bookings', 'newBooking', 'bookingDetail'].includes(active))}${it(d('rail.customers'), ['customers', 'customer'].includes(active))}${it(d('rail.calendar'), active === 'calendar')}${grp(d('rail.catalog'), cat, [[d('rail.destinations'), 'destinations'], [d('rail.stays'), 'stays'], [t('Experiences and services', 'التجارب والخدمات', 'Experiencias y servicios'), 'services'], [d('rail.packages'), 'packages', ST.soon()]])}${grp(d('rail.content'), con, [[d('rail.pages'), 'pages', ST.soon()], [d('rail.blog'), 'blog', ST.soon()], [d('rail.team'), 'team'], [d('rail.legal'), 'legal'], [t('Media', 'الوسائط', 'Medios'), 'media'], [t('Navigation and footer', 'التنقل والتذييل', 'Navegación y pie'), 'navigation']])}${it(d('rail.settings'), active === 'settings')}</nav>`;
  };
  const logo = (w) => `<img src="${LOGO}" alt="ALMAR" style="width:${w}px;height:auto;display:block">`;
  const userBlock = () => `<div style="margin-top:auto;padding:16px;border-top:1px solid ${C.line};display:flex;flex-direction:column;gap:8px"><div style="display:flex;flex-direction:column"><span style="font-size:14px;color:${C.ink}">${GUEST}</span><span style="font-size:12px;line-height:{{lhC}};color:${C.muted}">${t('Owner', 'المالك', 'Propietario')}</span></div><span style="display:flex;align-items:center;min-height:44px;font-size:14px;color:${C.ink}">${d('signOut')}</span></div>`;
  const closeX = `<span style="display:flex;width:44px;height:44px;align-items:center;justify-content:center;color:${C.teal};flex:none">${icon('x', 20, C.teal)}</span>`;
  // drawer = {title, tabs, body, foot}
  const drawerHtml = (cls, dr) => {
    const inner = `<div style="min-height:72px;flex:none;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:0 8px 0 24px;border-bottom:1px solid ${C.line}"><div style="display:flex;flex-direction:column;min-width:0"><h2 style="margin:0;font-family:{{fd}};font-weight:400;font-size:20px;line-height:{{lhT}};color:${C.teal}">${dr.title}</h2>${dr.sub ? cap(dr.sub) : ''}</div>${closeX}</div>${dr.tabs ? `<div style="padding:0 24px;flex:none">${tabs(dr.tabs)}</div>` : ''}<div style="flex:1;min-height:0;overflow:hidden;padding:24px;display:flex;flex-direction:column;gap:16px">${dr.body}</div><div style="flex:none;min-height:80px;box-sizing:border-box;padding:16px 24px;display:flex;align-items:center;gap:12px;border-top:1px solid ${C.line}">${dr.foot || ''}</div>`;
    if (cls === 'p') return `<div style="position:absolute;inset:0;background:${C.surface};display:flex;flex-direction:column">${inner}</div>`;
    return `<div style="position:absolute;inset:0;background:rgba(38,38,38,0.4)"></div><div style="position:absolute;top:0;bottom:0;inset-inline-end:0;width:560px;max-width:100%;background:${C.surface};${LG}display:flex;flex-direction:column">${inner}</div>`;
  };
  const shell = (cls, active, title, actions, body, o = {}) => {
    const W = WD[cls], Hh = o.h;
    const sidebar = `<aside style="width:240px;flex:none;box-sizing:border-box;background:${C.surface};border-inline-end:1px solid ${C.line};display:flex;flex-direction:column"><div style="height:72px;display:flex;align-items:center;padding:0 16px;border-bottom:1px solid ${C.line}">${logo(120)}</div>${NAVI(active)}${userBlock()}</aside>`;
    const topbar = cls === 'd' ? '' : `<div style="height:72px;flex:none;display:flex;align-items:center;justify-content:space-between;padding:0 ${cls === 'p' ? 16 : 32}px;border-bottom:1px solid ${C.line};background:${C.surface}">${logo(cls === 'p' ? 96 : 120)}<span style="display:inline-flex;align-items:center;height:44px;padding:0 16px;box-sizing:border-box;border:1px solid ${C.muted};font-size:14px;color:${C.ink}">${d('menu')}</span></div>`;
    const pad = cls === 'p' ? 16 : 32;
    const head = o.noHead ? '' : `<div style="display:flex;align-items:${cls === 'p' ? 'flex-start' : 'center'};justify-content:space-between;gap:16px;${cls === 'p' ? 'flex-direction:column;' : 'flex-wrap:wrap;'}">${o.back ? `<div style="display:flex;flex-direction:column;gap:4px">${o.back}<h1 style="margin:0;font-family:{{fd}};font-weight:400;font-size:${cls === 'p' ? 24 : 32}px;line-height:{{lh2}};color:${C.teal}">${title}</h1>${o.sub || ''}</div>` : `<h1 style="margin:0;font-family:{{fd}};font-weight:400;font-size:${cls === 'p' ? 24 : 32}px;line-height:{{lh2}};color:${C.teal}">${title}</h1>`}<div style="display:flex;align-items:center;gap:12px;flex-wrap:wrap">${actions || ''}</div></div>`;
    const main = `<main style="flex:1;min-width:0;min-height:0;display:flex;flex-direction:column;overflow:hidden">${topbar}<div style="flex:1;min-height:0;padding:${pad}px;display:flex;flex-direction:column;gap:24px;overflow:hidden">${head}${body}</div></main>`;
    const railOpen = o.railOpen ? `<div style="position:absolute;inset:0;background:rgba(38,38,38,0.4)"></div><div style="position:absolute;top:0;bottom:0;inset-inline-end:0;width:300px;background:${C.surface};${LG}display:flex;flex-direction:column"><div style="height:72px;display:flex;align-items:center;justify-content:space-between;padding:0 8px 0 16px;border-bottom:1px solid ${C.line}">${logo(96)}${closeX}</div>${NAVI(active)}${userBlock()}</div>` : '';
    return `<div style="position:relative;width:${W}px;height:${Hh}px;box-sizing:border-box;background:${C.ivory};border:1px solid ${C.line};display:flex;overflow:hidden">${cls === 'd' ? sidebar : ''}${main}${o.drawer ? drawerHtml(cls, o.drawer) : ''}${railOpen}${o.dialog ? `<div style="position:absolute;inset:0;background:rgba(38,38,38,0.4);display:flex;align-items:center;justify-content:center;padding:16px">${o.dialog}</div>` : ''}</div>`;
  };
  const dlg = (title, inner, foot, w = 480) => `<div role="dialog" style="width:${w}px;max-width:100%;background:${C.surface};${LG}padding:24px;box-sizing:border-box;display:flex;flex-direction:column;gap:16px"><div style="display:flex;align-items:flex-start;justify-content:space-between;gap:16px"><h3 style="margin:0;font-family:{{fd}};font-weight:400;font-size:20px;line-height:{{lhT}};color:${C.teal}">${title}</h3><span style="display:flex;width:44px;height:44px;align-items:center;justify-content:center;color:${C.teal};margin:-8px -8px 0 0">${icon('x', 20, C.teal)}</span></div>${inner}<div style="display:flex;justify-content:flex-end;gap:12px;flex-wrap:wrap">${foot}</div></div>`;
  const calGrid = (cls, o = {}) => {
    const days = []; const blocked = o.blocked || {}; const bk = o.bookings || {};
    for (let i = 0; i < 3; i++) days.push('<span></span>');
    for (let n = 1; n <= 31; n++) { const b2 = blocked[n]; const has = bk[n]; days.push(`<div style="min-height:${cls === 'p' ? 52 : 92}px;box-sizing:border-box;padding:4px ${cls === 'p' ? 4 : 8}px;background:${b2 ? C.ivory : C.surface};border:1px solid ${C.line};display:flex;flex-direction:column;gap:4px;font-size:12px;font-variant-numeric:tabular-nums;color:${b2 ? C.muted : C.ink};overflow:hidden"><span>${n}</span>${b2 ? `<span style="height:20px;padding:0 6px;background:${C.ink};color:${C.ivory};font-size:12px;line-height:20px;overflow:hidden;white-space:nowrap">${cls === 'p' ? '' : b2}</span>` : has ? `<span style="height:20px;padding:0 6px;background:${C.tealTint};color:${C.teal};font-size:12px;line-height:20px;overflow:hidden;white-space:nowrap">${cls === 'p' ? '' : GUEST}</span>` : ''}</div>`); }
    const wd = [0, 1, 2, 3, 4, 5, 6].map((i) => `<span style="text-align:center;font-size:12px;line-height:{{lhC}};color:${C.muted}">${t(['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][i], ['إث', 'ث', 'أر', 'خ', 'ج', 'س', 'أح'][i], ['lun', 'mar', 'mié', 'jue', 'vie', 'sáb', 'dom'][i])}</span>`).join('');
    return `<div style="display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:4px">${wd}${days.join('')}</div>`;
  };
  const monthLbl = t('October 2026', 'أكتوبر 2026', 'octubre de 2026');
  const toggleCard = (title, detail, on) => `<div style="display:flex;align-items:flex-start;justify-content:space-between;gap:12px;min-height:44px;padding:16px;box-sizing:border-box;background:${C.surface};border:1px solid ${on ? C.teal : C.muted};${on ? `box-shadow:inset 0 0 0 2px ${C.teal};` : ''}"><span style="display:flex;flex-direction:column;gap:2px"><span style="font-family:{{fd}};font-size:16px;line-height:{{lhT}};color:${C.teal}">${title}</span>${detail ? cap(detail) : ''}</span>${on ? icon('check', 20, C.teal) : ''}</div>`;
  const stepper = (n) => `<span style="display:inline-flex;align-items:center;flex:none">${['minus', 'plus'].map((g, i) => `${i === 1 ? `<span style="width:28px;text-align:center;font-size:16px;font-weight:700;font-variant-numeric:tabular-nums;color:${C.ink}">${n}</span>` : ''}<span style="display:flex;align-items:center;justify-content:center;width:44px;height:44px;box-sizing:border-box;background:${C.surface};border:1px solid ${C.teal};color:${C.teal}">${icon(g, 16, 'currentColor')}</span>`).join('')}</span>`;
  const timeline = (items) => `<div style="display:flex;flex-direction:column">${items.map(([who, what, when, tone], i) => `<div style="display:flex;gap:12px;min-height:56px"><div style="display:flex;flex-direction:column;align-items:center;flex:none"><span style="width:12px;height:12px;background:${tone === 'good' ? C.teal : C.surface};border:2px solid ${C.teal};box-sizing:border-box;margin-top:6px;display:block"></span>${i < items.length - 1 ? `<span style="flex:1;width:2px;background:${C.tealTint};display:block"></span>` : ''}</div><div style="display:flex;flex-direction:column;padding-bottom:12px;min-width:0"><span style="font-size:14px;line-height:{{lhL}};color:${C.ink}">${what}</span><span style="font-size:12px;line-height:{{lhC}};color:${C.muted}">${who} · ${when}</span></div></div>`).join('')}</div>`;
  const ADMIN = t('[Admin name]', '[اسم المشرف]', '[Nombre del administrador]');
  const SYS = t('System', 'النظام', 'Sistema');
  const evt = {
    created: t('Booking created', 'أُنشئ الحجز', 'Reserva creada'), dep: t('Deposit received', 'استُلمت الدفعة المقدّمة', 'Depósito recibido'), conf: t('Status changed to Confirmed', 'تغيّرت الحالة إلى مؤكد', 'Estado cambiado a Confirmado'), mail: t('Confirmation email sent', 'أُرسل بريد التأكيد', 'Correo de confirmación enviado'), chg: t('Dates changed', 'تغيّرت التواريخ', 'Fechas modificadas'), add: t('Experience added', 'أُضيفت تجربة', 'Experiencia añadida'), note: t('Internal note added', 'أُضيفت ملاحظة داخلية', 'Nota interna añadida'), req: t('Cancellation requested by the guest', 'طلب الضيف الإلغاء', 'Cancelación solicitada por el huésped'),
  };
  const histItems = [[SYS, evt.created, DT, 'good'], [SYS, evt.dep, DT, 'good'], [ADMIN, evt.conf, DT, 'good'], [SYS, evt.mail, DT], [ADMIN, evt.chg, DT], [GUEST, evt.add, DT], [ADMIN, evt.note, DT]];

  const SCR = {};
  // ============ HOME ============
  SCR.home = (cls, st, o = {}) => {
    const f = st === 'filled';
    const kpi = grid(cls === 'p' ? 2 : 4, 16, `${stat(t('Revenue', 'الإيرادات', 'Ingresos'), f ? 'AED [AMOUNT]' : '0', f ? t('[±00]% vs last period', '[±00]٪ مقارنة بالفترة السابقة', '[±00] % vs periodo anterior') : '')}${stat(d('rail.bookings'), f ? '[00]' : '0')}${stat(t('Occupancy', 'الإشغال', 'Ocupación'), f ? '[00]%' : '—')}${stat(t('Balance due', 'الرصيد المستحق', 'Saldo pendiente'), f ? 'AED [AMOUNT]' : '—')}`);
    const attn = card(t('Needs attention', 'يحتاج إلى انتباه', 'Requiere atención'), col(0, [[t('Cancellation requests', 'طلبات الإلغاء', 'Solicitudes de cancelación'), '[00]'], [t('Payments overdue', 'مدفوعات متأخرة', 'Pagos vencidos'), '[00]'], [t('Arrivals in the next 7 days', 'وصول خلال ٧ أيام', 'Llegadas en 7 días'), '[00]']].map(([a, b]) => `<div style="display:flex;align-items:center;justify-content:space-between;gap:12px;min-height:52px;border-bottom:1px solid ${C.line};font-size:14px;color:${C.ink}"><span>${a}</span><span style="display:flex;align-items:center;gap:8px">${f ? bgt(0, b) : ''}${icon('chevron-right', 16, C.teal, true)}</span></div>`).join('')));
    const arr = card(t('Arrivals and departures', 'الوصول والمغادرة', 'Llegadas y salidas'), f ? col(0, rowsN(4, (i) => `<div style="display:flex;align-items:center;gap:12px;min-height:52px;border-bottom:1px solid ${C.line};font-size:14px;color:${C.ink}"><span style="width:96px;flex:none">${DT}</span><span style="flex:1;min-width:0">${GUEST} · ${STAYN}</span>${i % 2 ? chip('Departure', 'مغادرة', 'Salida') : chip('Arrival', 'وصول', 'Llegada', true)}</div>`).join('')) : cap(d('noRemindersYet')));
    const cols = [{ h: t('Ref', 'المرجع', 'Ref.'), w: '140px', first: true }, { h: t('Guest', 'الضيف', 'Huésped') }, { h: t('Status', 'الحالة', 'Estado'), w: '190px' }, { h: t('Total', 'الإجمالي', 'Total'), w: '120px' }];
    const recent = card(t('Recent bookings', 'الحجوزات الأخيرة', 'Reservas recientes'), f ? table(cls, cols, rowsN(5, (i) => [REF, GUEST, mix(i), AMT])) : cap(d('noBookingsYet')), { action: btnG(t('View all', 'عرض الكل', 'Ver todo')) });
    const act = card(t('Activity', 'النشاط', 'Actividad'), f ? timeline(histItems.slice(0, 5)) : cap(d('noRemindersYet')));
    const body = `${kpi}${cls === 'd' ? grid(2, 24, col(24, recent + arr) + col(24, attn + act), 'grid-template-columns:minmax(0,1.5fr) minmax(0,1fr);align-items:start') : col(24, attn + recent + arr + act)}`;
    return shell(cls, 'home', d('rail.home'), `${range()}${btnP(d('newBooking'), { plus: true })}`, body, { h: o.h, railOpen: o.railOpen });
  };
  // ============ BOOKINGS list ============
  const bCols = [{ h: t('Ref', 'المرجع', 'Ref.'), w: '130px', first: true }, { h: t('Guest', 'الضيف', 'Huésped') }, { h: t('Stay', 'الإقامة', 'Estancia'), t: false, p: false }, { h: t('Dates', 'التواريخ', 'Fechas'), w: '230px', p: false }, { h: t('Status', 'الحالة', 'Estado'), w: '190px' }, { h: t('Paid', 'المدفوع', 'المدفوع'), w: '110px', t: false, p: false }, { h: t('Total', 'الإجمالي', 'Total'), w: '110px' }];
  const tCols = [{ h: t('Ref', 'المرجع', 'Ref.'), w: '140px', first: true }, { h: t('Guest and dates', 'الضيف والتواريخ', 'Huésped y fechas') }, { h: t('Status', 'الحالة', 'Estado'), w: '190px' }, { h: t('Total', 'الإجمالي', 'Total'), w: '120px' }];
  const bookingPhoneCard = (i) => `<div style="background:${C.surface};border:1px solid ${C.line};padding:16px;display:flex;flex-direction:column;gap:8px;box-sizing:border-box"><div style="display:flex;align-items:center;justify-content:space-between;gap:8px"><span style="font-size:12px;color:${C.muted}">${REF}</span>${mix(i)}</div><span style="font-family:{{fd}};font-size:16px;line-height:{{lhT}};color:${C.teal}">${GUEST}</span><span style="font-size:14px;line-height:{{lhL}};color:${C.ink}">${DTS}</span><div style="display:flex;align-items:center;justify-content:space-between;gap:8px;padding-top:8px;border-top:1px solid ${C.line}"><span style="font-size:14px;color:${C.muted}">${STAYN}</span><span style="font-size:14px;color:${C.ink}">${AMT}</span></div></div>`;
  SCR.bookings = (cls, st, o = {}) => {
    const f = st === 'filled';
    const filters = cls === 'p' ? `${search(null)}<div style="display:flex;align-items:center;gap:8px;flex:none">${trig(t('Filters', 'تصفية', 'Filtros'), '100px')}${range(true)}</div>` : `<div style="display:flex;align-items:center;gap:12px;flex-wrap:wrap;flex:none">${search(280)}${trig(t('All statuses', 'كل الحالات', 'Todos los estados'), '180px')}${trig(t('All destinations', 'كل الوجهات', 'Todos los destinos'), '190px')}${trig(t('All stays', 'كل الإقامات', 'Todas las estancias'), '170px')}${range()}</div>`;
    const list = cls === 'd' ? table(cls, bCols, rowsN(7, (i) => [REF, GUEST, STAYN, DTS, mix(i), AMT, AMT])) : cls === 't' ? table(cls, tCols, rowsN(7, (i) => [REF, `<span style="display:flex;flex-direction:column;gap:2px">${GUEST}${cap(DTS)}</span>`, mix(i), AMT]), { tall: true }) : `<div style="display:flex;flex-direction:column;gap:12px">${rowsN(7, bookingPhoneCard).join('')}</div>`;
    return shell(cls, 'bookings', d('rail.bookings'), btnP(d('newBooking'), { plus: true }), `${tabs([[t('All', 'الكل', 'Todas'), true], [t('Upcoming', 'القادمة', 'Próximas')], [cls === 'p' ? t('Requests', 'الطلبات', 'Solicitudes') : t('Cancellation requests', 'طلبات الإلغاء', 'Solicitudes de cancelación'), false, f ? '1' : ''], [t('Completed', 'المكتملة', 'Completadas')]])}${filters}${f ? list : emptyState(d('noBookingsYet'), btnP(d('newBooking'), { plus: true }))}`, { h: o.h });
  };
  // ============ NEW BOOKING (page, 5 steps) ============
  const STEPS = [t('Guest', 'الضيف', 'Huésped'), t('Stay and dates', 'الإقامة والتواريخ', 'Estancia y fechas'), t('Extras', 'الإضافات', 'Extras'), t('Payment', 'الدفع', 'Pago'), t('Review', 'المراجعة', 'Revisión')];
  const stepRail = (cls, cur) => cls === 'p' ? col(8, `<div style="display:grid;grid-template-columns:repeat(5,1fr);gap:4px">${STEPS.map((_, i) => `<span style="height:3px;background:${i < cur ? C.teal : C.line};display:block"></span>`).join('')}</div>${cap(t('Step', 'الخطوة', 'Paso') + ' ' + cur + ' / 5 · ' + STEPS[cur - 1])}`) : `<ol style="margin:0;padding:0;list-style:none;display:grid;grid-template-columns:repeat(5,minmax(0,1fr));border-bottom:1px solid ${C.line}">${STEPS.map((s, i) => { const sx = i + 1 < cur ? 'done' : i + 1 === cur ? 'cur' : 'up'; return `<li style="display:flex;align-items:center;gap:12px;padding-bottom:16px;${sx === 'cur' ? `box-shadow:inset 0 -3px 0 ${C.teal};` : ''}"><span style="display:flex;align-items:center;justify-content:center;width:28px;height:28px;box-sizing:border-box;${sx === 'done' ? `background:${C.teal};color:${C.ivory}` : `border:1px solid ${sx === 'cur' ? C.teal : C.muted};color:${sx === 'cur' ? C.teal : C.muted}`};font-size:12px">${sx === 'done' ? icon('check', 14, C.ivory) : i + 1}</span><span style="font-size:14px;color:${sx === 'up' ? C.muted : C.teal}">${s}</span></li>`; }).join('')}</ol>`;
  const sumLine = (a, v, bold) => `<div style="display:flex;justify-content:space-between;gap:12px;font-size:${bold ? 20 : 14}px;line-height:{{lhL}};color:${C.ink}${bold ? ';font-weight:700' : ''}"><span>${a}</span><span>${v}</span></div>`;
  const summaryCard = (step) => card(t('Booking summary', 'ملخص الحجز', 'Resumen de la reserva'), `${ro(t('Guest', 'الضيف', 'Huésped'), step > 1 ? GUEST : '—')}${ro(t('Stay', 'الإقامة', 'Estancia'), step > 2 ? STAYN : '—')}${ro(t('Dates', 'التواريخ', 'Fechas'), step > 2 ? DTS : '—')}${step > 3 ? `<div style="display:flex;flex-direction:column;gap:8px;padding-top:12px;border-top:1px solid ${C.line}">${sumLine(t('Stay', 'الإقامة', 'Estancia'), AMT)}${sumLine(t('Extras', 'الإضافات', 'Extras'), AMT)}${sumLine(t('VAT [RATE]%', 'ضريبة القيمة المضافة [RATE]٪', 'IVA [RATE] %'), AMT)}${sumLine(t('Total', 'الإجمالي', 'Total'), AMT, true)}</div>` : ''}`, { style: 'position:sticky;top:0;' });
  const nbBody = (step, cls) => {
    const two = cls === 'd';
    let main;
    if (step === 1) main = card(t('Who is booking?', 'من يحجز؟', '¿Quién reserva?'), `${search(null, t('Search customers by name, email or phone', 'ابحث عن العملاء بالاسم أو البريد أو الهاتف', 'Buscar clientes por nombre, correo o teléfono'))}${col(0, rowsN(3, (i) => `<div style="display:flex;align-items:center;gap:12px;min-height:56px;border-bottom:1px solid ${C.line};${i === 0 ? `background:${C.tealTint};padding:0 12px;` : ''}font-size:14px;color:${C.ink}"><span style="flex:1;min-width:0">${GUEST}<br>${cap(EM)}</span>${i === 0 ? icon('check', 20, C.teal) : ''}</div>`).join(''))}<div style="display:flex;align-items:center;gap:12px;color:${C.muted};font-size:12px"><span style="flex:1;height:1px;background:${C.line}"></span>${t('or create a customer', 'أو أنشئ عميلًا', 'o crea un cliente')}<span style="flex:1;height:1px;background:${C.line}"></span></div>${grid(two ? 2 : 1, 16, `${field(t('Name', 'الاسم', 'Nombre'), '')}${field(t('Email', 'البريد الإلكتروني', 'Correo electrónico'), '')}${field(t('Phone', 'الهاتف', 'Teléfono'), '')}${field(t('Language', 'اللغة', 'Idioma'), 'EN')}`)}`);
    else if (step === 2) main = `${card(t('Stay', 'الإقامة', 'Estancia'), `${grid(two ? 2 : 1, 16, `${col(8, lab(d('rail.destinations')) + trig(DESTN, '100%'))}${col(8, lab(d('rail.stays')) + trig(STAYN, '100%'))}`)}${grid(two ? 3 : 1, 16, `${field(t('Arrive', 'وصول', 'Llegada'), '[DD/MM/YYYY]')}${field(t('Leave', 'مغادرة', 'Salida'), '[DD/MM/YYYY]')}${col(8, lab(t('Booking source', 'مصدر الحجز', 'Origen de la reserva')) + trig(t('Direct', 'مباشر', 'Directo'), '100%'))}`)}<div style="display:flex;align-items:center;gap:8px;font-size:14px;color:${C.success}">${icon('check', 20, C.success)}<span>${t('Available for these dates', 'متاح في هذه التواريخ', 'Disponible en estas fechas')}</span></div>`)}${card(t('Availability', 'التوافر', 'Disponibilidad'), `${calGrid(cls === 'p' ? 'p' : 'd', { blocked: { 5: t('Blocked', 'محجوب', 'Bloqueado'), 6: t('Blocked', 'محجوب', 'Bloqueado'), 19: t('Booked', 'محجوز', 'Reservado'), 20: t('Booked', 'محجوز', 'Reservado') } }).replaceAll('min-height:92px', 'min-height:56px')}`)}${card(t('Guests', 'الضيوف', 'Huéspedes'), `${['Adults', 'Children', 'Infants'].map((g, i) => `<div style="display:flex;align-items:center;justify-content:space-between;gap:12px;min-height:56px;border-bottom:1px solid ${C.line}">${lab(t(g, ['البالغون', 'الأطفال', 'الرضّع'][i], ['Adultos', 'Niños', 'Bebés'][i]))}${stepper(i === 0 ? 2 : 0)}</div>`).join('')}`)}`;
    else if (step === 3) main = card(t('Experiences and services', 'التجارب والخدمات', 'Experiencias y servicios'), `${row(12, search(two ? 280 : null) + (cls === 'p' ? '' : seg([[t('All', 'الكل', 'Todo'), true], [t('Experiences', 'التجارب', 'Experiencias')], [t('Services', 'الخدمات', 'Servicios')]])), 'flex-wrap:wrap')}${col(0, rowsN(4, (i) => `<div style="display:flex;align-items:center;gap:12px;min-height:72px;border-bottom:1px solid ${C.line}">${thumb(IM[i], 72, 54)}<div style="flex:1;min-width:0;display:flex;flex-direction:column;gap:2px">${i % 2 ? ST.svc() : ST.exp()}<span style="font-family:{{fd}};font-size:16px;color:${C.teal}">${NAME}</span>${cap(PRICE)}</div>${i === 1 ? stepper(2) : btnS(t('Add', 'أضف', 'Añadir'))}</div>`).join(''))}`);
    else if (step === 4) main = `${card(t('Payment plan', 'خطة الدفع', 'Plan de pago'), `${toggleCard(t('Deposit', 'دفعة مقدّمة', 'Depósito'), `${t('Deposit', 'دفعة مقدّمة', 'Depósito')} AED [AMOUNT] · ${t('balance due by', 'الرصيد مستحق قبل', 'saldo antes del')} [DD/MM/YYYY]`, true)}${toggleCard(t('Full payment', 'دفع كامل', 'Pago completo'), 'AED [AMOUNT]', false)}${toggleCard(t('Pay later', 'الدفع لاحقًا', 'Pagar después'), t('Booking stays a Draft until paid', 'يبقى الحجز مسودة حتى الدفع', 'La reserva queda en borrador hasta el pago'), false)}`)}${card(t('Collect the payment', 'تحصيل الدفعة', 'Cobrar el pago'), `${toggleCard(t('Send a payment link to the guest', 'أرسل رابط دفع إلى الضيف', 'Enviar un enlace de pago al huésped'), EM, true)}${toggleCard(t('Record a payment received offline', 'سجّل دفعة استُلمت خارج الموقع', 'Registrar un pago recibido fuera de línea'), t('Bank transfer, cash or other', 'تحويل مصرفي أو نقد أو غيره', 'Transferencia, efectivo u otro'), false)}`)}${card(t('Internal note', 'ملاحظة داخلية', 'Nota interna'), field(t('Only staff see this', 'يراها الموظفون فقط', 'Solo el personal lo ve'), '', null, { area: 88 }))}`;
    else main = `${card(t('Review', 'المراجعة', 'Revisión'), `${[[t('Guest', 'الضيف', 'Huésped'), `${GUEST} · ${EM}`], [t('Stay', 'الإقامة', 'Estancia'), `${STAYN} · ${DESTN}`], [t('Dates', 'التواريخ', 'Fechas'), DTS], [t('Guests', 'الضيوف', 'Huéspedes'), t('2 adults', 'بالغان', '2 adultos')], [t('Extras', 'الإضافات', 'Extras'), `${NAME} × 2`], [t('Payment', 'الدفع', 'Pago'), t('Deposit, payment link sent by email', 'دفعة مقدّمة، رابط الدفع بالبريد', 'Depósito, enlace de pago por correo')]].map(([a, v]) => `<div style="display:flex;align-items:center;justify-content:space-between;gap:12px;min-height:52px;border-bottom:1px solid ${C.line}"><div style="display:flex;flex-direction:column;min-width:0">${cap(a)}<span style="font-size:14px;color:${C.ink}">${v}</span></div>${btnG(t('Edit', 'تعديل', 'Editar'))}</div>`).join('')}`)}${card(t('Notify', 'الإشعار', 'Notificar'), `<div style="display:flex;align-items:center;justify-content:space-between;gap:12px;font-size:14px;color:${C.ink}"><span>${t('Email the guest a confirmation', 'أرسل إلى الضيف بريد تأكيد', 'Enviar al huésped un correo de confirmación')}</span>${sw(true)}</div>`)}`;
    const foot = `<div style="display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap">${step > 1 ? btnG(t('Back', 'رجوع', 'Atrás')) : btnG(d('close'))}<div style="display:flex;gap:12px">${step === 5 ? btnS(t('Save as draft', 'حفظ كمسودة', 'Guardar borrador')) + btnP(t('Create booking', 'إنشاء الحجز', 'Crear reserva')) : btnP(t('Continue', 'متابعة', 'Continuar'))}</div></div>`;
    return two ? `<div style="display:grid;grid-template-columns:minmax(0,1fr) 360px;gap:24px;align-items:start"><div style="display:flex;flex-direction:column;gap:24px">${main}${foot}</div>${summaryCard(step)}</div>` : `<div style="display:flex;flex-direction:column;gap:24px">${main}${cls === 'p' ? `<div style="display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 16px;background:${C.surface};border:1px solid ${C.line}"><div style="display:flex;flex-direction:column">${cap(t('Total', 'الإجمالي', 'Total'))}<span style="font-size:16px;font-weight:700;color:${C.ink}">${AMT}</span></div>${step === 5 ? btnP(t('Create booking', 'إنشاء الحجز', 'Crear reserva')) : btnP(t('Continue', 'متابعة', 'Continuar'))}</div>` : summaryCard(step)}${cls === 'p' ? '' : foot}</div>`;
  };
  SCR.newBooking = (cls, step, o = {}) => shell(cls, 'newBooking', d('newBooking'), btnG(d('close')), `${stepRail(cls, step)}${nbBody(step, cls)}`, { h: o.h, back: `<span style="font-size:14px;color:${C.teal};min-height:44px;display:inline-flex;align-items:center">‹ ${d('rail.bookings')}</span>` });
  // ============ BOOKING DETAIL ============
  const bdTabs = (on) => tabs(['Overview', 'Itinerary', 'Payments', 'History', 'Notes'].map((s, i) => [t(s, ['نظرة عامة', 'البرنامج', 'المدفوعات', 'السجل', 'الملاحظات'][i], ['Resumen', 'Itinerario', 'Pagos', 'Historial', 'Notas'][i]), i === on, i === 3 ? '7' : '']));
  const bdHead = (cls, chips) => ({ back: `<span style="font-size:14px;color:${C.teal};min-height:44px;display:inline-flex;align-items:center">‹ ${d('rail.bookings')}</span>`, sub: `<div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap">${chips}${REF}</div>` });
  const bdActions = (cls) => cls === 'p' ? `${btnP(t('Record payment', 'تسجيل دفعة', 'Registrar pago'))}${trig(t('More', 'المزيد', 'Más'), '120px')}` : `${btnP(t('Record payment', 'تسجيل دفعة', 'Registrar pago'))}${btnS(t('Edit booking', 'تعديل الحجز', 'Editar reserva'))}${trig(t('More', 'المزيد', 'Más'), '120px')}`;
  const guestCard = card(t('Guest', 'الضيف', 'Huésped'), `${GUEST}${cap(EM)}${cap(PHONE)}${btnG(t('Open customer profile', 'فتح ملف العميل', 'Abrir perfil del cliente'))}`);
  const stayCard = (cls) => card(t('Stay', 'الإقامة', 'Estancia'), `<img src="${B.stay}" alt="" style="width:100%;height:${cls === 'p' ? 160 : 220}px;object-fit:cover;display:block">${grid(2, 16, ro(d('rail.destinations'), DESTN) + ro(d('rail.stays'), STAYN) + ro(t('Arrive', 'وصول', 'Llegada'), DT) + ro(t('Leave', 'مغادرة', 'Salida'), DT) + ro(t('Nights', 'الليالي', 'Noches'), N) + ro(t('Guests', 'الضيوف', 'Huéspedes'), t('2 adults', 'بالغان', '2 adultos')))}`);
  const extrasCard = card(t('Experiences and services', 'التجارب والخدمات', 'Experiencias y servicios'), col(0, rowsN(3, (i) => `<div style="display:flex;align-items:center;gap:12px;min-height:64px;border-bottom:1px solid ${C.line}">${thumb(IM[i + 1], 56, 42)}<span style="flex:1;min-width:0;font-size:14px;color:${C.ink}">${NAME} × 2</span>${AMT}</div>`).join('')));
  const moneyCard = card(t('Payment', 'الدفع', 'Pago'), `${sumLine(t('Subtotal', 'المجموع الفرعي', 'Subtotal'), AMT)}${sumLine(t('VAT [RATE]%', 'ضريبة القيمة المضافة [RATE]٪', 'IVA [RATE] %'), AMT)}${sumLine(t('Total', 'الإجمالي', 'Total'), AMT, true)}${sumLine(t('Paid', 'المدفوع', 'Pagado'), AMT)}${sumLine(t('Balance due', 'الرصيد المستحق', 'Saldo pendiente'), AMT)}${cap(t('Balance due by', 'الرصيد مستحق قبل', 'Saldo pendiente antes del') + ' ' + '[DD/MM/YYYY]')}`);
  SCR.bookingDetail = (cls, tabKey, o = {}) => {
    const hd = bdHead(cls, `${ST.conf()}${ST.dep()}`);
    let body;
    if (tabKey === 'overview') body = cls === 'd' ? `<div style="display:grid;grid-template-columns:minmax(0,1fr) 380px;gap:24px;align-items:start">${col(24, stayCard(cls) + extrasCard)}${col(24, moneyCard + guestCard + card(t('Latest notes', 'آخر الملاحظات', 'Últimas notas'), `<span style="font-size:14px;color:${C.ink}">${t('[Internal note]', '[ملاحظة داخلية]', '[Nota interna]')}</span>${cap(ADMIN + ' · [DD/MM/YYYY]')}`))}</div>` : col(24, moneyCard + guestCard + stayCard(cls) + extrasCard);
    else if (tabKey === 'payments') body = `${card(t('Transactions', 'المعاملات', 'Transacciones'), table(cls, [{ h: t('Date', 'التاريخ', 'Fecha'), w: '120px', first: true }, { h: t('Method', 'الطريقة', 'Método') }, { h: t('Amount', 'المبلغ', 'Importe'), w: '130px' }, { h: t('Status', 'الحالة', 'Estado'), w: '140px' }, { h: t('Reference', 'المرجع', 'Referencia'), w: '160px', p: false }], [[DT, t('Card', 'بطاقة', 'Tarjeta'), AMT, chip('Paid', 'مدفوع', 'Pagado'), bdiN('[Reference]')], [DT, t('Bank transfer', 'تحويل مصرفي', 'Transferencia'), AMT, chip('Pending', 'قيد الانتظار', 'Pendiente'), bdiN('[Reference]')]]), { action: btnS(t('Record payment', 'تسجيل دفعة', 'Registrar pago')) })}${cls === 'd' ? grid(2, 24, moneyCard + card(t('Refunds', 'الاستردادات', 'Reembolsos'), `${cap(t('No refunds yet', 'لا استردادات بعد', 'Aún no hay reembolsos'))}${btnD(t('Refund a payment', 'استرداد دفعة', 'Reembolsar un pago'))}`), 'align-items:start') : moneyCard + card(t('Refunds', 'الاستردادات', 'Reembolsos'), `${cap(t('No refunds yet', 'لا استردادات بعد', 'Aún no hay reembolsos'))}${btnD(t('Refund a payment', 'استرداد دفعة', 'Reembolsar un pago'))}`)}`;
    else if (tabKey === 'history') body = card(t('History', 'السجل', 'Historial'), `${row(8, seg([[t('All', 'الكل', 'Todo'), true], [t('Status', 'الحالة', 'Estado')], [t('Payments', 'المدفوعات', 'Pagos')], [t('Emails', 'الرسائل', 'Correos')], [t('Changes', 'التغييرات', 'Cambios')]]), 'overflow:hidden')}${timeline([...histItems, [GUEST, evt.req, DT]])}`);
    else if (tabKey === 'cancel') body = `<div style="background:${C.surface};border:1px solid ${C.error};padding:24px;display:flex;flex-direction:column;gap:12px"><div style="display:flex;align-items:center;gap:8px">${ST.req()}<span style="font-size:14px;color:${C.ink}">${t('Requested by the guest on', 'طلب الضيف الإلغاء في', 'Solicitado por el huésped el')} ${DT}</span></div>${grid(cls === 'p' ? 1 : 3, 12, ro(t('Paid', 'المدفوع', 'Pagado'), AMT) + ro(t('Refundable under the policy', 'قابل للاسترداد وفق السياسة', 'Reembolsable según la política'), AMT) + ro(t('Guest reason', 'سبب الضيف', 'Motivo del huésped'), t('[Reason]', '[السبب]', '[Motivo]')))}${field(t('Refund amount', 'مبلغ الاسترداد', 'Importe del reembolso'), 'AED [AMOUNT]')}${field(t('Note to guest (optional)', 'ملاحظة للضيف (اختياري)', 'Nota al huésped (opcional)'), '', null, { area: 72 })}<div style="display:flex;gap:12px;flex-wrap:wrap">${btnP(t('Approve refund', 'الموافقة على الاسترداد', 'Aprobar reembolso'))}${btnD(t('Decline', 'رفض', 'Rechazar'))}</div></div>${cls === 'd' ? grid(2, 24, moneyCard + card(t('History', 'السجل', 'Historial'), timeline([[GUEST, evt.req, DT], [SYS, evt.dep, DT, 'good']])), 'align-items:start') : moneyCard}`;
    else body = card(t('Itinerary', 'البرنامج', 'Itinerario'), col(0, [1, 2, 3].map((n) => `<div style="display:${cls === 'p' ? 'flex;flex-direction:column;gap:8px' : 'grid;grid-template-columns:140px minmax(0,1fr);column-gap:24px'};padding:16px 0;border-top:1px solid ${C.line}"><div style="display:flex;flex-direction:column"><span style="font-family:{{fd}};font-size:20px;color:${C.teal}">${t('Day ' + n, 'اليوم ' + n, 'Día ' + n)}</span>${cap(DT)}</div><div style="display:flex;flex-direction:column;gap:8px"><span style="font-size:14px;color:${C.ink}">${bdiN('[Time]')} · ${NAME}</span>${btnG(t('Add item', 'أضف بندًا', 'Añadir elemento'))}</div></div>`).join('')));
    return shell(cls, 'bookingDetail', GUEST + ' · ' + t('[Trip name]', '[اسم الرحلة]', '[Nombre del viaje]'), bdActions(cls), `${bdTabs({ overview: 0, itinerary: 1, payments: 2, history: 3, notes: 4, cancel: 0 }[tabKey])}${body}`, { h: o.h, ...hd });
  };
  // ============ CUSTOMERS ============
  SCR.customers = (cls, st, o = {}) => {
    const f = st === 'filled';
    const cols = [{ h: t('Name', 'الاسم', 'Nombre'), first: true }, { h: t('Email', 'البريد الإلكتروني', 'Correo electrónico'), p: false }, { h: t('Phone', 'الهاتف', 'Teléfono'), w: '150px', t: false, p: false }, { h: d('rail.bookings'), w: '100px' }, { h: t('Total spent', 'إجمالي الإنفاق', 'Total gastado'), w: '140px', t: false }, { h: t('Last booking', 'آخر حجز', 'Última reserva'), w: '140px', t: false, p: false }];
    return shell(cls, 'customers', d('rail.customers'), btnP(d('newCustomer'), { plus: true }), `<div style="display:flex;align-items:center;gap:12px;flex-wrap:wrap">${search(cls === 'p' ? null : 320)}${cls === 'p' ? '' : trig(t('All customers', 'كل العملاء', 'Todos los clientes'), '190px')}</div>${f ? table(cls, cols, rowsN(8, () => [GUEST, EM, PHONE, N, AMT, DT])) : emptyState(d('noCustomersYet'), btnP(d('newCustomer'), { plus: true }))}`, { h: o.h });
  };
  SCR.customer = (cls, tabKey, o = {}) => {
    const cTabs = tabs([[t('Details', 'التفاصيل', 'Detalles'), tabKey === 'details'], [d('rail.bookings'), tabKey === 'bookings', '2'], [t('Logs', 'السجلات', 'Registros'), tabKey === 'logs']]);
    const banner = `<div style="display:flex;align-items:center;gap:12px;padding:12px 16px;background:${C.tealTint};font-size:14px;line-height:{{lhL}};color:${C.teal}">${icon('lock', 16, C.teal)}<span>${t('Customer details are changed by the customer. You can view them here.', 'يغيّر العميل بياناته بنفسه. يمكنك عرضها هنا.', 'El cliente cambia sus datos. Aquí solo puedes verlos.')}</span></div>`;
    let body;
    if (tabKey === 'details') body = `${banner}${cls === 'd' ? grid(2, 24, col(24, card(t('Profile', 'الملف الشخصي', 'Perfil'), grid(2, 16, ro(t('Name', 'الاسم', 'Nombre'), GUEST) + ro(t('Email', 'البريد الإلكتروني', 'Correo electrónico'), EM) + ro(t('Phone', 'الهاتف', 'Teléfono'), PHONE) + ro(t('Language', 'اللغة', 'Idioma'), 'EN') + ro(t('Currency', 'العملة', 'Moneda'), 'AED') + ro(t('Customer since', 'عميل منذ', 'Cliente desde'), DT))) + card(t('Saved travelers', 'المسافرون المحفوظون', 'Viajeros guardados'), col(0, rowsN(2, (i) => `<div style="display:flex;justify-content:space-between;min-height:48px;align-items:center;border-bottom:1px solid ${C.line};font-size:14px;color:${C.ink}"><span>${NAME}</span>${cap(i ? t('Child', 'طفل', 'Niño') : t('Adult', 'بالغ', 'Adulto'))}</div>`).join('')))) + col(24, card(t('Preferences', 'التفضيلات', 'Preferencias'), grid(1, 12, ro(t('Booking updates', 'تحديثات الحجز', 'Novedades de la reserva'), t('On', 'مفعّل', 'Activado')) + ro(t('Offers and stories', 'العروض والقصص', 'Ofertas e historias'), t('Off', 'متوقف', 'Desactivado')))) + card(t('Saved stays', 'الإقامات المحفوظة', 'Estancias guardadas'), col(8, rowsN(2, (i) => `<div style="display:flex;align-items:center;gap:12px">${thumb(IM[i], 72, 54)}<span style="font-family:{{fd}};font-size:16px;color:${C.teal}">${STAYN}</span></div>`).join(''))) + card(t('Lifetime', 'الإجمالي', 'Total histórico'), grid(2, 12, ro(d('rail.bookings'), N) + ro(t('Total spent', 'إجمالي الإنفاق', 'Total gastado'), AMT)))), 'align-items:start') : col(24, card(t('Profile', 'الملف الشخصي', 'Perfil'), grid(1, 16, ro(t('Name', 'الاسم', 'Nombre'), GUEST) + ro(t('Email', 'البريد الإلكتروني', 'Correo electrónico'), EM) + ro(t('Phone', 'الهاتف', 'Teléfono'), PHONE) + ro(t('Language', 'اللغة', 'Idioma'), 'EN') + ro(t('Customer since', 'عميل منذ', 'Cliente desde'), DT))) + card(t('Saved travelers', 'المسافرون المحفوظون', 'Viajeros guardados'), cap(NAME + ' · ' + t('Adult', 'بالغ', 'Adulto'))))}`;
    else if (tabKey === 'bookings') body = `${grid(cls === 'p' ? 2 : 3, 16, stat(d('rail.bookings'), '[00]') + stat(t('Total spent', 'إجمالي الإنفاق', 'Total gastado'), 'AED [AMOUNT]') + (cls === 'p' ? '' : stat(t('Next departure', 'المغادرة القادمة', 'Próxima salida'), '[DD/MM/YYYY]')))}${cls === 'd' ? table(cls, bCols, rowsN(4, (i) => [REF, GUEST, STAYN, DTS, mix(i), AMT, AMT])) : cls === 't' ? table(cls, tCols, rowsN(4, (i) => [REF, `<span style="display:flex;flex-direction:column;gap:2px">${GUEST}${cap(DTS)}</span>`, mix(i), AMT]), { tall: true }) : `<div style="display:flex;flex-direction:column;gap:12px">${rowsN(4, bookingPhoneCard).join('')}</div>`}`;
    else body = card(t('Activity log', 'سجل النشاط', 'Registro de actividad'), `${row(8, seg([[t('All', 'الكل', 'Todo'), true], [t('Sign-ins', 'تسجيلات الدخول', 'Accesos')], [d('rail.bookings')], [t('Emails', 'الرسائل', 'Correos')]]), 'overflow:hidden')}${timeline([[GUEST, t('Signed in with a magic link', 'سجّل الدخول برابط سحري', 'Accedió con enlace mágico'), DT], [GUEST, t('Saved a stay', 'حفظ إقامة', 'Guardó una estancia'), DT], [SYS, t('Booking confirmation email sent', 'أُرسل بريد تأكيد الحجز', 'Correo de confirmación enviado'), DT], [GUEST, t('Requested a cancellation', 'طلب الإلغاء', 'Solicitó una cancelación'), DT], [GUEST, t('Updated their phone number', 'حدّث رقم هاتفه', 'Actualizó su teléfono'), DT]])}`);
    return shell(cls, 'customer', GUEST, `${ST.ro()}`, `${cTabs}${body}`, { h: o.h, back: `<span style="font-size:14px;color:${C.teal};min-height:44px;display:inline-flex;align-items:center">‹ ${d('rail.customers')}</span>`, sub: cap(EM) });
  };
  // ============ CALENDAR ============
  const scopeBadge = { all: t('All', 'الكل', 'Todo'), dest: DESTN, stay: STAYN };
  SCR.calendar = (cls, st, o = {}) => {
    const f = st === 'filled';
    const bl = { 5: scopeBadge.all, 6: scopeBadge.all, 19: scopeBadge.dest, 20: scopeBadge.dest, 21: scopeBadge.dest, 27: scopeBadge.stay };
    const bk = f ? { 12: 1, 13: 1, 14: 1, 15: 1, 16: 1, 23: 1, 24: 1 } : {};
    const filt = `<div style="display:flex;align-items:center;gap:12px;flex-wrap:wrap">${trig(t('All destinations and stays', 'كل الوجهات والإقامات', 'Todos los destinos y estancias'), cls === 'p' ? '100%' : '260px')}${cls === 'p' ? '' : range()}<span style="margin-inline-start:${cls === 'p' ? 0 : 'auto'};font-family:{{fd}};font-size:20px;color:${C.teal}">${monthLbl}</span></div>`;
    const blocks = card(t('Blocked dates', 'التواريخ المحجوبة', 'Fechas bloqueadas'), col(0, [[scopeBadge.all, '[DD/MM/YYYY] – [DD/MM/YYYY]'], [scopeBadge.dest, '[DD/MM/YYYY] – [DD/MM/YYYY]'], [scopeBadge.stay, '[DD/MM/YYYY]']].map(([a, b2]) => `<div style="display:flex;align-items:center;gap:12px;min-height:56px;border-bottom:1px solid ${C.line};font-size:14px;color:${C.ink}"><div style="flex:1;min-width:0;display:flex;flex-direction:column">${a}${cap(bdiN(b2))}</div>${btnG(t('Edit', 'تعديل', 'Editar'))}</div>`).join('')));
    const main = cls === 'd' ? `<div style="display:grid;grid-template-columns:minmax(0,1fr) 320px;gap:24px;align-items:start">${col(16, calGrid(cls, { blocked: bl, bookings: bk }))}${blocks}</div>` : `${calGrid(cls, { blocked: bl, bookings: bk })}${cls === 't' ? blocks : ''}`;
    return shell(cls, 'calendar', d('rail.calendar'), `${btnS(t('Block dates', 'حجب التواريخ', 'Bloquear fechas'))}${btnP(d('newBooking'), { plus: true })}`, `${filt}${main}`, { h: o.h });
  };
  const blockDrawer = (variant) => {
    const scope = variant === 'all' ? 0 : variant === 'dest' ? 1 : 2;
    const conflict = variant === 'stay';
    return { title: t('Block dates', 'حجب التواريخ', 'Bloquear fechas'), sub: t('Blocked dates cannot be booked or picked in the booking bar.', 'لا يمكن حجز التواريخ المحجوبة أو اختيارها في شريط الحجز.', 'Las fechas bloqueadas no se pueden reservar ni elegir en la barra de reserva.'),
      body: `${lab(t('What to block', 'ما الذي يُحجب', 'Qué bloquear'))}${toggleCard(t('Everything', 'كل شيء', 'Todo'), t('Every destination and stay, the full day', 'كل الوجهات والإقامات، اليوم كاملًا', 'Todos los destinos y estancias, el día completo'), scope === 0)}${toggleCard(t('One destination', 'وجهة واحدة', 'Un destino'), t('All stays connected to it', 'كل الإقامات المرتبطة بها', 'Todas las estancias conectadas'), scope === 1)}${toggleCard(t('One stay', 'إقامة واحدة', 'Una estancia'), '', scope === 2)}${scope === 1 ? col(8, lab(d('rail.destinations')) + trig(DESTN, '100%')) : ''}${scope === 2 ? col(8, lab(d('rail.stays')) + trig(STAYN, '100%')) : ''}${grid(2, 12, field(t('From', 'من', 'Desde'), '[DD/MM/YYYY]') + field(t('To', 'إلى', 'Hasta'), '[DD/MM/YYYY]'))}${cap(t('Choose the same date twice to block one day. Blocks always cover the full day.', 'اختر التاريخ نفسه مرتين لحجب يوم واحد. الحجب يشمل اليوم كاملًا دائمًا.', 'Elige la misma fecha dos veces para bloquear un día. El bloqueo cubre siempre el día completo.'))}${field(t('Reason (optional)', 'السبب (اختياري)', 'Motivo (opcional)'), '')}${conflict ? `<div role="alert" style="display:flex;gap:8px;padding:12px 16px;background:${C.ivory};border:1px solid ${C.error};font-size:14px;line-height:{{lhL}};color:${C.error}">${icon('alert-circle', 20, C.error)}<span>${t('2 bookings overlap these dates. Blocking does not cancel them.', 'يتداخل حجزان مع هذه التواريخ. الحجب لا يلغيهما.', '2 reservas coinciden con estas fechas. Bloquear no las cancela.')}</span></div>` : ''}`,
      foot: `${btnG(d('close'))}<span style="flex:1"></span>${btnP(t('Block dates', 'حجب التواريخ', 'Bloquear fechas'))}` };
  };
  // ============ CATALOG: connection lists ============
  const connRow = (name, sub, img, extra) => `<div style="display:flex;align-items:center;gap:12px;min-height:64px;border-bottom:1px solid ${C.line}">${img ? thumb(img, 56, 42) : ''}<div style="flex:1;min-width:0;display:flex;flex-direction:column"><span style="font-size:14px;color:${C.ink}">${name}</span>${sub ? cap(sub) : ''}</div>${extra || btnG(t('Remove', 'إزالة', 'Quitar'), C.muted)}</div>`;
  const picker = (title, items) => `<div style="border:1px solid ${C.ink};background:${C.surface};display:flex;flex-direction:column">${search(null, title)}${items.map(([n, on]) => `<div style="display:flex;align-items:center;gap:12px;min-height:48px;padding:0 16px;border-top:1px solid ${C.line};font-size:14px;color:${C.ink}">${check(on)}<span>${n}</span></div>`).join('')}<div style="display:flex;justify-content:space-between;align-items:center;padding:12px 16px;border-top:1px solid ${C.line}">${cap(t('2 selected', 'تم اختيار 2', '2 seleccionados'))}${btnP(t('Connect selected', 'ربط المحدد', 'Conectar seleccionados'))}</div></div>`;
  const delFoot = (delLabel) => `${btnD(delLabel)}<span style="flex:1"></span>${btnG(d('close'))}${btnP(d('save'))}`;
  const langTabs = () => seg([['EN', true], ['AR'], ['ES']]);
  // Destinations
  const destCols = [{ h: t('Name', 'الاسم', 'Nombre'), first: true }, { h: d('rail.stays'), w: '120px' }, { h: t('Experiences and services', 'التجارب والخدمات', 'Experiencias y servicios'), w: '200px', p: false, t: false }, { h: t('Status', 'الحالة', 'Estado'), w: '150px' }];
  SCR.destinations = (cls, st, o = {}) => shell(cls, 'destinations', d('rail.destinations'), btnP(d('newDestination'), { plus: true }), st === 'filled' ? `${search(cls === 'p' ? null : 320)}${table(cls, destCols, rowsN(6, (i) => [NAME, N, N, i % 2 ? ST.draft() : ST.pub()]), { sel: o.sel })}` : emptyState(d('noDestinationsYet'), btnP(d('newDestination'), { plus: true })), { h: o.h, drawer: o.drawer, dialog: o.dialog });
  const destDrawer = (tabKey) => {
    const tb = [[t('Details', 'التفاصيل', 'Detalles'), tabKey === 'details'], [d('rail.stays'), tabKey === 'stays', '3'], [t('Experiences and services', 'التجارب والخدمات', 'Experiencias y servicios'), tabKey === 'all', '9']];
    let body;
    if (tabKey === 'details') body = `${langTabs()}${field(t('Name', 'الاسم', 'Nombre'), NAME)}${field(t('Short line', 'سطر قصير', 'Línea breve'), t('[Short line]', '[سطر قصير]', '[Línea breve]'))}${field(t('Description', 'الوصف', 'Descripción'), t('[Body text]', '[نص المحتوى]', '[Texto]'), null, { area: 88 })}${col(8, lab(t('Photo', 'الصورة', 'Foto')) + `<img src="${B.walled}" alt="" style="width:100%;height:120px;object-fit:cover;display:block">`)}`;
    else if (tabKey === 'stays') body = `${col(0, rowsN(3, (i) => connRow(STAYN, ST.pub() && t('Published', 'منشور', 'Publicado'), IM[i])).join(''))}${picker(t('Search stays to connect', 'ابحث عن إقامات للربط', 'Buscar estancias para conectar'), [[STAYN, true], [STAYN, true], [STAYN, false]])}`;
    else body = `${seg([[t('All', 'الكل', 'Todo'), true], [t('Destination-level', 'على مستوى الوجهة', 'Del destino')], [t('By stay', 'حسب الإقامة', 'Por estancia')]])}${cap(t('Everything guests can add for this destination: items connected to the destination and to each of its stays.', 'كل ما يمكن للضيوف إضافته لهذه الوجهة: البنود المرتبطة بالوجهة وبكل إقامة فيها.', 'Todo lo que los huéspedes pueden añadir en este destino: elementos del destino y de cada estancia.'))}${[[t('Destination-level', 'على مستوى الوجهة', 'Del destino'), 3], [STAYN + ' A', 2], [STAYN + ' B', 4]].map(([g, n], gi) => `<div style="display:flex;flex-direction:column"><div style="display:flex;align-items:center;justify-content:space-between;min-height:44px;background:${C.ivory};padding:0 12px;font-size:14px;color:${C.teal}"><span>${g}</span>${bgt(0, '[0' + n + ']')}</div>${rowsN(Math.min(n, 2), (i) => connRow(NAME, (i % 2 ? t('Service', 'خدمة', 'Servicio') : t('Experience', 'تجربة', 'Experiencia')) + ' · ' + 'AED [PRICE]', null, btnG(gi === 0 ? t('Remove', 'إزالة', 'Quitar') : t('From the stay', 'من الإقامة', 'De la estancia'), C.muted))).join('')}</div>`).join('')}${btnS(t('Connect experiences and services', 'ربط تجارب وخدمات', 'Conectar experiencias y servicios'), { plus: true })}`;
    return { title: NAME, sub: ST.pub() && t('Destination', 'وجهة', 'Destino'), tabs: tb, body, foot: delFoot(t('Delete destination', 'حذف الوجهة', 'Eliminar destino')) };
  };
  const delDialog = (what) => dlg(t('Delete ' + what + '?', 'حذف ' + what + '؟', '¿Eliminar ' + what + '?'), `<p style="margin:0;font-size:14px;line-height:{{lhL}};color:${C.ink}">${t('The 3 connected stays stay in the catalog but lose this connection. Existing bookings are not changed.', 'تبقى الإقامات الثلاث المرتبطة في الفهرس لكنها تفقد هذا الارتباط. لا تتغير الحجوزات القائمة.', 'Las 3 estancias conectadas siguen en el catálogo pero pierden esta conexión. Las reservas existentes no cambian.')}</p>`, `${btnG(t('Cancel', 'إلغاء', 'Cancelar'))}${btnD(t('Delete', 'حذف', 'Eliminar'))}`);
  // Stays
  const stayCols = [{ h: '', w: '72px', p: false }, { h: t('Name', 'الاسم', 'Nombre'), first: true }, { h: d('rail.destinations'), w: '170px' }, { h: t('Experiences and services', 'التجارب والخدمات', 'Experiencias y servicios'), w: '200px', p: false, t: false }, { h: t('Status', 'الحالة', 'Estado'), w: '150px' }];
  SCR.stays = (cls, st, o = {}) => shell(cls, 'stays', d('rail.stays'), btnP(d('newStay'), { plus: true }), st === 'filled' ? `<div style="display:flex;align-items:center;gap:12px;flex-wrap:wrap">${search(cls === 'p' ? null : 320)}${cls === 'p' ? '' : trig(t('All destinations', 'كل الوجهات', 'Todos los destinos'), '200px')}</div>${table(cls, stayCols, rowsN(6, (i) => [thumb(IM[i % 4]), NAME, DESTN, N, i % 2 ? ST.draft() : ST.pub()]), { tall: true, sel: o.sel })}` : emptyState(d('noStaysYet'), btnP(d('newStay'), { plus: true })), { h: o.h, drawer: o.drawer });
  const stayDrawer = (tabKey) => {
    const tb = [[t('Details', 'التفاصيل', 'Detalles'), tabKey === 'details'], [t('Experiences and services', 'التجارب والخدمات', 'Experiencias y servicios'), tabKey === 'ex', '4'], [t('Availability', 'التوافر', 'Disponibilidad'), tabKey === 'av']];
    let body;
    if (tabKey === 'details') body = `${langTabs()}${field(t('Name', 'الاسم', 'Nombre'), NAME)}${col(8, lab(d('rail.destinations')) + trig(DESTN, '100%'))}${grid(2, 12, field(t('Capacity', 'السعة', 'Capacidad'), '[00]') + field(t('Price per night', 'السعر لكل ليلة', 'Precio por noche'), 'AED [PRICE]'))}${field(t('Description', 'الوصف', 'Descripción'), t('[Body text]', '[نص المحتوى]', '[Texto]'), null, { area: 72 })}<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px">${[B.stay, B.walled, B.heritage].map((s) => `<img src="${s}" alt="" style="width:100%;height:72px;object-fit:cover;display:block">`).join('')}</div>`;
    else if (tabKey === 'ex') body = `${cap(t('Guests can add these to a booking of this stay. Items connected to the destination appear too.', 'يمكن للضيوف إضافتها إلى حجز هذه الإقامة. تظهر أيضًا البنود المرتبطة بالوجهة.', 'Los huéspedes pueden añadirlos a una reserva de esta estancia. También aparecen los del destino.'))}${col(0, rowsN(4, (i) => connRow(NAME, (i % 2 ? t('Service', 'خدمة', 'Servicio') : t('Experience', 'تجربة', 'Experiencia')) + ' · AED [PRICE]', IM[i], i === 3 ? btnG(t('From the destination', 'من الوجهة', 'Del destino'), C.muted) : undefined)).join(''))}${picker(t('Search experiences and services', 'ابحث في التجارب والخدمات', 'Buscar experiencias y servicios'), [[NAME, true], [NAME, false], [NAME, true]])}`;
    else body = `${cap(t('Blocked and booked dates for this stay. Blocks are set in the Calendar.', 'التواريخ المحجوبة والمحجوزة لهذه الإقامة. تُضبط الحجوزات المحجوبة من التقويم.', 'Fechas bloqueadas y reservadas de esta estancia. Los bloqueos se definen en el Calendario.'))}<span style="font-family:{{fd}};font-size:20px;color:${C.teal}">${monthLbl}</span>${calGrid('p', { blocked: { 5: t('Blocked', 'محجوب', 'Bloqueado'), 6: t('Blocked', 'محجوب', 'Bloqueado'), 19: t('Booked', 'محجوز', 'Reservado'), 20: t('Booked', 'محجوز', 'Reservado') } })}${btnS(t('Block dates for this stay', 'حجب تواريخ لهذه الإقامة', 'Bloquear fechas de esta estancia'))}`;
    return { title: NAME, sub: ST.pub() && DESTN, tabs: tb, body, foot: delFoot(t('Delete stay', 'حذف الإقامة', 'Eliminar estancia')) };
  };
  // Services and experiences
  const svcCols = [{ h: '', w: '72px', p: false }, { h: t('Name', 'الاسم', 'Nombre'), first: true }, { h: t('Type', 'النوع', 'Tipo'), w: '130px' }, { h: t('Unit', 'الوحدة', 'Unidad'), w: '130px', p: false, t: false }, { h: t('Price', 'السعر', 'Precio'), w: '130px' }, { h: t('Connected to', 'مرتبط بـ', 'Conectado a'), w: '170px', p: false, t: false }, { h: t('Status', 'الحالة', 'Estado'), w: '140px', t: false, p: false }];
  SCR.services = (cls, st, o = {}) => shell(cls, 'services', t('Experiences and services', 'التجارب والخدمات', 'Experiencias y servicios'), btnP(d('newExperience'), { plus: true }), st === 'filled' ? `<div style="display:flex;align-items:center;gap:12px;flex-wrap:wrap">${search(cls === 'p' ? null : 300, t('Search experiences and services', 'ابحث في التجارب والخدمات', 'Buscar experiencias y servicios'))}${seg([[t('All', 'الكل', 'Todo'), true], [t('Experiences', 'التجارب', 'Experiencias')], [t('Services', 'الخدمات', 'Servicios')]])}${cls === 'p' ? '' : `${trig(t('All destinations', 'كل الوجهات', 'Todos los destinos'), '190px')}${trig(t('All stays', 'كل الإقامات', 'Todas las estancias'), '170px')}`}</div>${table(cls, svcCols, rowsN(6, (i) => [thumb(IM[i % 4]), NAME, i % 2 ? ST.svc() : ST.exp(), [t('per person', 'للشخص', 'por persona'), t('per night', 'لكل ليلة', 'por noche'), t('per trip', 'للرحلة', 'por viaje')][i % 3], PRICE, t('[00] destinations, [00] stays', '[00] وجهات، [00] إقامات', '[00] destinos, [00] estancias'), i % 2 ? ST.draft() : ST.pub()]), { tall: true, sel: o.sel })}` : emptyState(d('noExperiencesYet'), btnP(d('newExperience'), { plus: true })), { h: o.h, drawer: o.drawer });
  const svcDrawer = (tabKey) => {
    const tb = [[t('Details', 'التفاصيل', 'Detalles'), tabKey === 'details'], [t('Connections', 'الارتباطات', 'Conexiones'), tabKey === 'conn', '5']];
    const body = tabKey === 'details' ? `${langTabs()}${field(t('Name', 'الاسم', 'Nombre'), NAME)}${seg([[t('Experience', 'تجربة', 'Experiencia'), true], [t('Service', 'خدمة', 'Servicio')]])}${grid(2, 12, col(8, lab(t('Unit', 'الوحدة', 'Unidad')) + trig(t('per person', 'للشخص', 'por persona'), '100%')) + field(t('Price', 'السعر', 'Precio'), 'AED [PRICE]'))}${field(t('Description', 'الوصف', 'Descripción'), t('[Body text]', '[نص المحتوى]', '[Texto]'), null, { area: 72 })}<img src="${B.heritage}" alt="" style="width:100%;height:96px;object-fit:cover;display:block">` : `${cap(t('Choose where guests can add this item. It can be connected to whole destinations, to single stays, or both.', 'اختر أين يمكن للضيوف إضافة هذا البند. يمكن ربطه بوجهات كاملة أو بإقامات محددة أو بكليهما.', 'Elige dónde pueden añadir los huéspedes este elemento: destinos completos, estancias concretas o ambos.'))}${picker(t('Search destinations', 'ابحث في الوجهات', 'Buscar destinos'), [[DESTN, true], [DESTN, false]])}${picker(t('Search stays', 'ابحث في الإقامات', 'Buscar estancias'), [[STAYN, true], [STAYN, true], [STAYN, false]])}`;
    return { title: NAME, sub: ST.pub() && t('Experience', 'تجربة', 'Experiencia'), tabs: tb, body, foot: delFoot(t('Delete', 'حذف', 'Eliminar')) };
  };
  // Coming soon (Packages, Pages, Blog)
  const comingSoon = (cls, active, title, headline, intro, bullets, o = {}) => shell(cls, active, title, '', `<div style="border:1px solid ${C.line};background:${C.surface};padding:${cls === 'p' ? 24 : 48}px;display:flex;flex-direction:column;gap:24px;align-items:flex-start"><div style="display:flex;align-items:center;gap:12px">${ST.soon()}</div><h2 style="margin:0;font-family:{{fd}};font-weight:400;font-size:${cls === 'p' ? 24 : 32}px;line-height:{{lh2}};color:${C.teal}">${headline}</h2><p style="margin:0;font-size:16px;line-height:{{lhB}};color:${C.ink};max-width:65ch">${intro}</p>${grid(cls === 'p' ? 1 : 2, 12, bullets.map((b2) => `<div style="display:flex;align-items:center;gap:12px;min-height:44px;font-size:14px;color:${C.ink}">${icon('check', 16, C.muted)}<span>${b2}</span></div>`).join(''))}</div>`, { h: o.h });
  SCR.packages = (cls, o = {}) => comingSoon(cls, 'packages', d('rail.packages'), t('Packages are coming soon', 'الباقات قريبًا', 'Los paquetes llegan pronto'), t('Packages bundle a journey. They need more setup than the rest of the catalog, so they arrive in a later phase.', 'الباقات تجمع رحلة كاملة. تحتاج إعدادًا أكبر من بقية الفهرس، لذا تصل في مرحلة لاحقة.', 'Los paquetes agrupan un viaje. Necesitan más configuración que el resto del catálogo, por eso llegan en una fase posterior.'), [t('Connect several stays', 'ربط عدة إقامات', 'Conectar varias estancias'), t('Connect several destinations', 'ربط عدة وجهات', 'Conectar varios destinos'), t('Include experiences and services', 'تضمين تجارب وخدمات', 'Incluir experiencias y servicios'), t('Set package prices and rules', 'ضبط أسعار الباقات وقواعدها', 'Definir precios y reglas'), t('Set availability and minimum stays', 'ضبط التوافر والحد الأدنى للإقامة', 'Definir disponibilidad y estancia mínima'), t('Publish on the public site', 'النشر على الموقع العام', 'Publicar en el sitio público')], o);
  SCR.pagesSoon = (cls, o = {}) => comingSoon(cls, 'pages', d('rail.pages'), t('Page editing is coming soon', 'تحرير الصفحات قريبًا', 'La edición de páginas llega pronto'), t('For now the public pages are edited outside the dashboard. Editing every page here arrives in a later phase.', 'تُحرَّر الصفحات العامة حاليًا خارج لوحة التحكم. يصل تحرير كل صفحة هنا في مرحلة لاحقة.', 'Por ahora las páginas públicas se editan fuera del panel. Editar cada página aquí llega en una fase posterior.'), [t('Edit text and images on every page', 'تحرير النصوص والصور في كل صفحة', 'Editar textos e imágenes de cada página'), t('Reorder and switch sections on and off', 'إعادة ترتيب الأقسام وتشغيلها وإيقافها', 'Reordenar y activar o desactivar secciones'), t('English, Arabic and Spanish for every field', 'الإنجليزية والعربية والإسبانية لكل حقل', 'Inglés, árabe y español en cada campo'), t('Search title and description per page', 'عنوان ووصف البحث لكل صفحة', 'Título y descripción de búsqueda por página'), t('Preview before publishing', 'المعاينة قبل النشر', 'Vista previa antes de publicar'), t('Add new pages', 'إضافة صفحات جديدة', 'Añadir páginas nuevas')], o);
  SCR.blogSoon = (cls, o = {}) => comingSoon(cls, 'blog', d('rail.blog'), t('The blog editor is coming soon', 'محرر المدونة قريبًا', 'El editor del blog llega pronto'), t('Writing and publishing posts from the dashboard arrives in a later phase.', 'كتابة المقالات ونشرها من لوحة التحكم تصل في مرحلة لاحقة.', 'Escribir y publicar entradas desde el panel llega en una fase posterior.'), [t('Rich text editor in three languages', 'محرر نصوص غني بثلاث لغات', 'Editor de texto enriquecido en tres idiomas'), t('Cover image and alt text', 'صورة الغلاف والنص البديل', 'Imagen de portada y texto alternativo'), t('Destination tag and reading time', 'وسم الوجهة ووقت القراءة', 'Etiqueta de destino y tiempo de lectura'), t('Featured stay and experience cards', 'بطاقات إقامة وتجربة مميزتين', 'Tarjetas de estancia y experiencia destacadas'), t('Schedule or publish', 'الجدولة أو النشر', 'Programar o publicar'), t('Search title and description', 'عنوان ووصف البحث', 'Título y descripción de búsqueda')], o);
  // ============ CONTENT ============
  const cHub = (cls, o = {}) => shell(cls, 'content', d('rail.content'), '', `${cap(t('Everything on the public site can be edited here, in English, Arabic and Spanish.', 'يمكن تعديل كل ما في الموقع العام هنا، بالإنجليزية والعربية والإسبانية.', 'Todo lo del sitio público se edita aquí, en inglés, árabe y español.'))}${grid(cls === 'd' ? 3 : cls === 't' ? 2 : 1, 16, [[d('rail.pages'), t('Edit the text, images and sections of every page.', 'عدّل النصوص والصور والأقسام في كل صفحة.', 'Edita textos, imágenes y secciones de cada página.'), 'soon'], [d('rail.blog'), t('Write, schedule and publish posts.', 'اكتب المقالات وجدولها وانشرها.', 'Escribe, programa y publica entradas.'), 'soon'], [d('rail.team'), t('Members shown on the public site.', 'الأعضاء المعروضون في الموقع العام.', 'Miembros mostrados en el sitio público.'), '[00]'], [d('rail.legal'), t('Terms, privacy and policies, with versions.', 'الشروط والخصوصية والسياسات مع الإصدارات.', 'Términos, privacidad y políticas, con versiones.'), '[00]'], [t('Media', 'الوسائط', 'Medios'), t('Every image and video, with alt text in three languages.', 'كل الصور والفيديوهات مع نص بديل بثلاث لغات.', 'Todas las imágenes y vídeos, con texto alternativo en tres idiomas.'), '[00]'], [t('Navigation and footer', 'التنقل والتذييل', 'Navegación y pie'), t('Menus, footer links and contact details.', 'القوائم وروابط التذييل وبيانات التواصل.', 'Menús, enlaces del pie y datos de contacto.'), '']].map(([a, b, n]) => `<div style="background:${C.surface};border:1px solid ${C.line};padding:24px;display:flex;flex-direction:column;gap:12px;min-width:0"><div style="display:flex;align-items:center;justify-content:space-between"><span style="font-family:{{fd}};font-size:20px;color:${n === 'soon' ? C.muted : C.teal}">${a}</span>${n === 'soon' ? ST.soon() : n ? `<span style="font-size:14px;color:${C.muted}">${bdiN(n)}</span>` : ''}</div><span style="font-size:14px;line-height:{{lhL}};color:${n === 'soon' ? C.muted : C.ink}">${b}</span>${n === 'soon' ? '' : btnS(t('Open', 'فتح', 'Abrir'))}</div>`).join(''))}`, { h: o.h });
  const PAGES_L = ['Home', 'About', 'Contact', 'Destinations', 'Experiences and services', 'Private stays', 'Blog'];
  const pageEditor = (cls, o = {}) => {
    const list = card(d('rail.pages'), col(0, PAGES_L.map((p, i) => `<div style="display:flex;align-items:center;justify-content:space-between;gap:8px;min-height:48px;padding:0 ${i === 0 ? 12 : 0}px;border-bottom:1px solid ${C.line};font-size:14px;color:${i === 0 ? C.teal : C.ink};background:${i === 0 ? C.tealTint : 'transparent'}"><span>${t(p, ['الرئيسية', 'من نحن', 'اتصل بنا', 'الوجهات', 'التجارب والخدمات', 'الإقامات الخاصة', 'المدونة'][i], ['Inicio', 'Nosotros', 'Contacto', 'Destinos', 'Experiencias y servicios', 'Estancias privadas', 'Blog'][i])}</span>${i % 3 ? '' : ST.pub()}</div>`).join('')));
    const blocks = ['Hero', 'Text', 'Cards', 'Gallery', 'Call to action', 'Team'].map((b2, i) => `<div style="display:flex;align-items:center;gap:12px;min-height:64px;padding:0 16px;background:${C.surface};border:1px solid ${i === 1 ? C.teal : C.line};${i === 1 ? `box-shadow:inset 0 0 0 1px ${C.teal};` : ''}"><span style="color:${C.muted};font-size:16px">⋮⋮</span><span style="flex:1;min-width:0;display:flex;flex-direction:column"><span style="font-size:14px;color:${C.ink}">${t(b2, ['الغلاف', 'نص', 'بطاقات', 'معرض', 'دعوة لاتخاذ إجراء', 'الفريق'][i], ['Portada', 'Texto', 'Tarjetas', 'Galería', 'Llamada a la acción', 'Equipo'][i])}</span>${cap(t('[Section title]', '[عنوان القسم]', '[Título de sección]'))}</span>${sw(i !== 5)}${btnG(t('Edit', 'تعديل', 'Editar'))}</div>`).join('');
    const editor = card(t('Home', 'الرئيسية', 'Inicio'), `${tabs([[t('Sections', 'الأقسام', 'Secciones'), true], [t('SEO', 'تحسين البحث', 'SEO')], [t('Settings', 'الإعدادات', 'Ajustes')]])}${col(8, blocks)}${btnS(t('Add section', 'إضافة قسم', 'Añadir sección'), { plus: true })}`, { action: seg([['EN', true], ['AR'], ['ES']]) });
    const blockEd = card(t('Text section', 'قسم نص', 'Sección de texto'), `${field(t('Title', 'العنوان', 'Título'), t('[Section title]', '[عنوان القسم]', '[Título de sección]'))}${field(t('Body', 'المحتوى', 'Contenido'), t('[Body text]', '[نص المحتوى]', '[Texto]'), null, { area: 96 })}${col(8, lab(t('Image', 'الصورة', 'Imagen')) + `<img src="${B.walled}" alt="" style="width:100%;height:96px;object-fit:cover;display:block">`)}${field(t('Alt text', 'النص البديل', 'Texto alternativo'), t('[Alt text]', '[النص البديل]', '[Texto alternativo]'))}${cap(t('Change text and images in each language with the EN, AR and ES switch above.', 'غيّر النصوص والصور لكل لغة بمفتاح EN وAR وES أعلاه.', 'Cambia textos e imágenes en cada idioma con el selector EN, AR y ES de arriba.'))}`);
    const body = cls === 'd' ? `<div style="display:grid;grid-template-columns:240px minmax(0,1fr) 380px;gap:24px;align-items:start">${list}${editor}${blockEd}</div>` : col(24, editor + blockEd);
    return shell(cls, 'pages', d('rail.pages'), `${btnG(t('Preview', 'معاينة', 'Vista previa'))}${btnS(d('save'))}${btnP(d('publish'))}`, body, { h: o.h });
  };
  const listContent = (active, title, newLabel, emptyLine, cls, st, o = {}) => shell(cls, active, title, btnP(newLabel, { plus: true }), st === 'filled' ? `${search(cls === 'p' ? null : 320)}${table(cls, [{ h: t('Title', 'العنوان', 'Título'), first: true }, { h: t('Languages', 'اللغات', 'Idiomas'), w: '130px', p: false }, { h: t('Status', 'الحالة', 'Estado'), w: '150px' }, { h: t('Updated', 'آخر تحديث', 'Actualizado'), w: '140px', t: false }], rowsN(6, (i) => [NAME, 'EN · AR · ES', i % 2 ? ST.draft() : ST.pub(), DT]))}` : emptyState(emptyLine, btnP(newLabel, { plus: true })), { h: o.h, drawer: o.drawer });
  const postEditor = (cls, o = {}) => shell(cls, 'blog', d('rail.blog'), `${btnG(t('Preview', 'معاينة', 'Vista previa'))}${btnS(t('Schedule', 'جدولة', 'Programar'))}${btnP(d('publish'))}`, `<div style="display:grid;grid-template-columns:${cls === 'd' ? 'minmax(0,1fr) 340px' : '1fr'};gap:24px;align-items:start">${card(t('Post', 'المقال', 'Entrada'), `${seg([['EN', true], ['AR'], ['ES']])}${field(t('Title', 'العنوان', 'Título'), t('[Post title]', '[عنوان المقال]', '[Título de la entrada]'))}<div style="border:1px solid ${C.ink};background:${C.surface}"><div style="display:flex;gap:4px;padding:8px;border-bottom:1px solid ${C.line};font-size:14px;color:${C.teal};flex-wrap:wrap">${['B', 'I', 'H2', '“ ”', '•', '1.', '🔗'.replace('🔗', 'Link'), t('Image', 'صورة', 'Imagen'), t('Featured stay', 'إقامة مميزة', 'Estancia destacada'), t('Featured experience', 'تجربة مميزة', 'Experiencia destacada')].map((b2) => `<span style="display:inline-flex;align-items:center;min-height:36px;padding:0 10px;border:1px solid ${C.line}">${b2}</span>`).join('')}</div><div style="min-height:${cls === 'p' ? 200 : 300}px;padding:16px;font-size:14px;line-height:{{lhL}};color:${C.muted}">${t('[Body text]', '[نص المحتوى]', '[Texto]')}</div></div>`)}${col(24, card(t('Publishing', 'النشر', 'Publicación'), `${ST.draft()}${col(8, lab(t('Destination tag', 'وسم الوجهة', 'Etiqueta de destino')) + trig(DESTN, '100%'))}${col(8, lab(t('Reading time', 'وقت القراءة', 'Tiempo de lectura')) + cap(t('Calculated from the text', 'يُحسب من النص', 'Calculado del texto')))}`) + card(t('Cover image', 'صورة الغلاف', 'Imagen de portada'), `<img src="${B.heritage}" alt="" style="width:100%;height:140px;object-fit:cover;display:block">${field(t('Alt text', 'النص البديل', 'Texto alternativo'), t('[Alt text]', '[النص البديل]', '[Texto alternativo]'))}`) + card(t('SEO', 'تحسين البحث', 'SEO'), `${field(t('Search title', 'عنوان البحث', 'Título de búsqueda'), '')}${field(t('Search description', 'وصف البحث', 'Descripción de búsqueda'), '', null, { area: 64 })}`))}</div>`, { h: o.h, back: `<span style="font-size:14px;color:${C.teal};min-height:44px;display:inline-flex;align-items:center">‹ ${d('rail.blog')}</span>` });
  const teamDrawer = () => ({ title: t('Team member', 'عضو الفريق', 'Miembro del equipo'), body: `${langTabs()}${grid(2, 12, `<div style="display:flex;flex-direction:column;gap:8px">${lab(t('Photo', 'الصورة', 'Foto'))}<span style="display:flex;align-items:center;justify-content:center;height:120px;background:${C.tealTint};color:${C.teal};font-size:14px">${t('Upload', 'رفع', 'Subir')}</span></div>${col(12, field(t('Name', 'الاسم', 'Nombre'), NAME) + field(t('Role', 'المنصب', 'Cargo'), t('[Role]', '[المنصب]', '[Cargo]')))}`)}${field(t('Email (optional)', 'البريد الإلكتروني (اختياري)', 'Correo (opcional)'), '')}${col(8, lab(t('Social media', 'وسائل التواصل الاجتماعي', 'Redes sociales')) + ['Instagram', 'LinkedIn', 'Facebook', 'X'].map((n, i) => `<div style="display:flex;align-items:center;gap:8px"><span style="width:104px;flex:none;font-size:14px;color:${C.ink}">${n}</span>${field('', i < 2 ? 'https://' : '', null).replace('display:flex;flex-direction:column;gap:8px;', 'display:flex;flex-direction:column;gap:0;').replace('<span style="font-size:14px;line-height:{{lhL}};color:' + C.ink + '"></span>', '')}${btnG(t('Remove', 'إزالة', 'Quitar'), C.muted)}</div>`).join('') + btnS(t('Add a link', 'إضافة رابط', 'Añadir enlace'), { plus: true }) + cap(t('Shown as icons on the member\'s card on the public Team section.', 'تظهر كأيقونات على بطاقة العضو في قسم الفريق العام.', 'Se muestran como iconos en la tarjeta del miembro en la sección Equipo pública.')))}<div style="display:flex;align-items:center;justify-content:space-between;font-size:14px;color:${C.ink}"><span>${t('Show on the public site', 'إظهار في الموقع العام', 'Mostrar en el sitio público')}</span>${sw(true)}</div>${cap(t('Drag members in the list to change their order on the site.', 'اسحب الأعضاء في القائمة لتغيير ترتيبهم في الموقع.', 'Arrastra los miembros de la lista para cambiar su orden en el sitio.'))}`, foot: delFoot(t('Delete member', 'حذف العضو', 'Eliminar miembro')) });
  const legalDrawer = () => ({ title: t('Legal page', 'صفحة قانونية', 'Página legal'), sub: t('Version [00]', 'الإصدار [00]', 'Versión [00]'), tabs: [[t('Edit', 'تعديل', 'Editar'), true], [t('Versions', 'الإصدارات', 'Versiones'), false, '3']], body: `${langTabs()}${field(t('Title', 'العنوان', 'Título'), NAME)}${field(t('Text', 'النص', 'Texto'), t('[Body text]', '[نص المحتوى]', '[Texto]'), null, { area: 200 })}${cap(t('Saving creates a new version. Earlier versions stay in Versions.', 'يُنشئ الحفظ إصدارًا جديدًا. تبقى الإصدارات السابقة في الإصدارات.', 'Al guardar se crea una versión nueva. Las anteriores quedan en Versiones.'))}`, foot: delFoot(t('Delete page', 'حذف الصفحة', 'Eliminar página')) });
  const mediaScreen = (cls, o = {}) => shell(cls, 'media', t('Media', 'الوسائط', 'Medios'), btnP(t('Upload', 'رفع', 'Subir'), { plus: true }), `<div style="display:flex;align-items:center;gap:12px;flex-wrap:wrap">${search(cls === 'p' ? null : 320)}${seg([[t('All', 'الكل', 'Todo'), true], [t('Images', 'الصور', 'Imágenes')], [t('Video', 'فيديو', 'Vídeo')]])}</div>${grid(cls === 'd' ? 5 : cls === 't' ? 3 : 2, 12, rowsN(cls === 'p' ? 6 : 10, (i) => `<div style="background:${C.surface};border:1px solid ${C.line};display:flex;flex-direction:column"><img src="${IM[i % 4]}" alt="" style="width:100%;height:${cls === 'p' ? 96 : 120}px;object-fit:cover;display:block"><div style="padding:8px 12px;display:flex;flex-direction:column;gap:2px">${cap(t('[File name]', '[اسم الملف]', '[Nombre del archivo]'))}${cap(t('Alt text: EN AR ES', 'النص البديل: EN AR ES', 'Texto alt.: EN AR ES'))}</div></div>`).join(''))}`, { h: o.h, drawer: o.drawer });
  const mediaDrawer = () => ({ title: t('[File name]', '[اسم الملف]', '[Nombre del archivo]'), body: `<img src="${B.walled}" alt="" style="width:100%;height:180px;object-fit:cover;display:block">${langTabs()}${field(t('Alt text', 'النص البديل', 'Texto alternativo'), t('[Alt text]', '[النص البديل]', '[Texto alternativo]'))}${cap(t('Used in: [00] pages, [00] stays', 'مستخدمة في: [00] صفحات، [00] إقامات', 'Usada en: [00] páginas, [00] estancias'))}`, foot: delFoot(t('Delete image', 'حذف الصورة', 'Eliminar imagen')) });
  const navScreen = (cls, o = {}) => shell(cls, 'navigation', t('Navigation and footer', 'التنقل والتذييل', 'Navegación y pie'), `${btnS(d('save'))}${btnP(d('publish'))}`, `${grid(cls === 'd' ? 2 : 1, 24, `${card(t('Header menu', 'قائمة الرأس', 'Menú de cabecera'), col(8, ['Destinations', 'Experiences', 'About', 'Contact'].map((n, i) => `<div style="display:flex;align-items:center;gap:12px;min-height:48px;padding:0 12px;background:${C.ivory};font-size:14px;color:${C.ink}"><span style="color:${C.muted}">⋮⋮</span><span style="flex:1">${t(n, ['الوجهات', 'التجارب', 'من نحن', 'اتصل بنا'][i], ['Destinos', 'Experiencias', 'Nosotros', 'Contacto'][i])}</span>${sw(true)}</div>`).join('') + btnS(t('Add link', 'إضافة رابط', 'Añadir enlace'), { plus: true })))}${card(t('Footer', 'التذييل', 'Pie de página'), col(12, field(t('Email', 'البريد الإلكتروني', 'Correo electrónico'), 'inquiries@almarprivatejourney.com') + field(t('Phone', 'الهاتف', 'Teléfono'), '+971 56 388 3302') + field('Instagram', 'https://instagram.com/almarprivatejourney/') + field('WhatsApp', 'https://wa.me/971563883302')))}`)}`, { h: o.h });
  // ============ SETTINGS (merged with Profile) ============
  const setNav = (cur) => col(0, ['My profile', 'Business', 'Payments and taxes', 'Team and roles', 'Security and logs'].map((n, i) => `<span style="display:flex;align-items:center;min-height:44px;padding:0 16px;font-size:14px;background:${i === cur ? C.tealTint : 'transparent'};color:${i === cur ? C.teal : C.ink}">${t(n, ['ملفي الشخصي', 'النشاط التجاري', 'المدفوعات والضرائب', 'الفريق والأدوار', 'الأمان والسجلات'][i], ['Mi perfil', 'Negocio', 'Pagos e impuestos', 'Equipo y roles', 'Seguridad y registros'][i])}</span>`).join(''), `background:${C.surface};border:1px solid ${C.line};padding:8px 0;`);
  const setPane = (cur, cls) => {
    const two = cls !== 'p';
    if (cur === 0) return col(24, card(t('My profile', 'ملفي الشخصي', 'Mi perfil'), `${grid(two ? 2 : 1, 16, field(t('Name', 'الاسم', 'Nombre'), GUEST) + field(t('Email', 'البريد الإلكتروني', 'Correo electrónico'), EM) + field(t('Phone', 'الهاتف', 'Teléfono'), PHONE) + col(8, lab(t('Language', 'اللغة', 'Idioma')) + trig('EN', '100%')))}`) + card(t('Sign-in', 'تسجيل الدخول', 'Acceso'), `<div style="display:flex;align-items:center;justify-content:space-between;gap:12px;font-size:14px;color:${C.ink}"><span>${d('staySignedIn')}</span>${sw(true)}</div><div style="display:flex;gap:12px;flex-wrap:wrap">${btnS(d('signOutOfThisSite'))}${btnD(d('signOutEverywhere'))}</div>`));
    if (cur === 1) return col(24, card(t('Business', 'النشاط التجاري', 'Negocio'), grid(two ? 2 : 1, 16, field(t('Business name', 'اسم النشاط', 'Nombre del negocio'), 'ALMAR Private Journeys') + field(t('Email', 'البريد الإلكتروني', 'Correo electrónico'), 'inquiries@almarprivatejourney.com') + field(t('Phone', 'الهاتف', 'Teléfono'), '+971 56 388 3302') + field('WhatsApp', 'https://wa.me/971563883302') + field(t('Address', 'العنوان', 'Dirección'), t('[Address]', '[العنوان]', '[Dirección]')) + col(8, lab(t('Default language', 'اللغة الافتراضية', 'Idioma predeterminado')) + trig('EN', '100%')))) + card(t('Brand', 'الهوية', 'Marca'), `<div style="display:flex;gap:8px;flex-wrap:wrap">${[C.teal, C.tealTint, C.ivory, C.ink, C.gold].map((c2) => `<span style="width:56px;height:56px;background:${c2};border:1px solid ${C.line};display:block"></span>`).join('')}</div>${cap(t('Colours and type are read-only for now. Editing brand settings arrives in Phase 5.', 'الألوان والخطوط للقراءة فقط حاليًا. تحرير إعدادات الهوية يصل في المرحلة ٥.', 'Los colores y la tipografía son de solo lectura por ahora. Editar la marca llega en la Fase 5.'))}`));
    if (cur === 2) return col(24, card(t('Currency', 'العملة', 'Moneda'), `${seg(['aed', 'usd', 'eur'].map((c2, i) => [d('currencies.' + c2), i === 0]))}${cap(t('Amounts show in the currency a guest picks. Prices are stored in AED.', 'تُعرض المبالغ بالعملة التي يختارها الضيف. تُخزَّن الأسعار بالدرهم.', 'Los importes se muestran en la moneda que elige el huésped. Los precios se guardan en AED.'))}`) + card(t('Taxes and deposits', 'الضرائب والدفعات المقدّمة', 'Impuestos y depósitos'), grid(two ? 2 : 1, 16, field(t('VAT rate', 'نسبة ضريبة القيمة المضافة', 'Tasa de IVA'), '[RATE]%') + field(t('Deposit', 'الدفعة المقدّمة', 'Depósito'), '[00]%') + field(t('Balance due', 'موعد الرصيد', 'Saldo pendiente'), t('[00] days before arrival', '[00] أيام قبل الوصول', '[00] días antes de la llegada')) + field(t('Refund policy', 'سياسة الاسترداد', 'Política de reembolso'), t('[Refund policy]', '[سياسة الاسترداد]', '[Política de reembolso]')))) + card(t('Payments', 'المدفوعات', 'Pagos'), `<div style="display:flex;align-items:center;justify-content:space-between;gap:12px;font-size:14px;color:${C.ink}"><span>Stripe</span>${chip('Connected', 'متصل', 'Conectado', true)}</div>`));
    if (cur === 3) return card(t('Team and roles', 'الفريق والأدوار', 'Equipo y roles'), `${table(cls, [{ h: t('Name', 'الاسم', 'Nombre'), first: true }, { h: t('Role', 'الدور', 'Rol'), w: '150px' }, { h: t('Last sign-in', 'آخر دخول', 'Último acceso'), w: '150px', p: false }], [[GUEST, t('Owner', 'المالك', 'Propietario'), DT], [GUEST, t('Manager', 'مدير', 'Gerente'), DT], [GUEST, t('Editor', 'محرر', 'Editor'), DT]])}${btnS(t('Invite a user', 'دعوة مستخدم', 'Invitar a un usuario'), { plus: true })}${cap(t('Owner: everything. Manager: bookings, customers, calendar and catalog. Editor: content only.', 'المالك: كل شيء. المدير: الحجوزات والعملاء والتقويم والفهرس. المحرر: المحتوى فقط.', 'Propietario: todo. Gerente: reservas, clientes, calendario y catálogo. Editor: solo contenido.'))}`, { action: '' });
    return col(24, card(t('Notifications to staff', 'إشعارات الموظفين', 'Avisos al personal'), ['New booking', 'Cancellation request', 'Payment received'].map((n, i) => `<div style="display:flex;align-items:center;justify-content:space-between;min-height:48px;font-size:14px;color:${C.ink}"><span>${t(n, ['حجز جديد', 'طلب إلغاء', 'دفعة مستلمة'][i], ['Nueva reserva', 'Solicitud de cancelación', 'Pago recibido'][i])}</span>${sw(i < 2)}</div>`).join('')) + card(t('Audit log', 'سجل التدقيق', 'Registro de auditoría'), `${timeline([[ADMIN, t('Changed the VAT rate', 'غيّر نسبة ضريبة القيمة المضافة', 'Cambió la tasa de IVA'), DT], [ADMIN, t('Blocked dates for [Destination]', 'حجب تواريخ لـ [الوجهة]', 'Bloqueó fechas de [Destino]'), DT], [ADMIN, t('Published a page', 'نشر صفحة', 'Publicó una página'), DT], [ADMIN, t('Invited a user', 'دعا مستخدمًا', 'Invitó a un usuario'), DT]])}`));
  };
  SCR.settings = (cls, cur, o = {}) => shell(cls, 'settings', d('rail.settings'), `${btnP(d('save'))}`, cls === 'd' ? `<div style="display:grid;grid-template-columns:240px minmax(0,1fr);gap:24px;align-items:start">${setNav(cur)}${setPane(cur, cls)}</div>` : `<div style="display:flex;gap:8px;overflow:hidden;flex:none">${['My profile', 'Business', 'Payments and taxes', 'Team and roles', 'Security and logs'].map((n, i) => `<span style="display:inline-flex;align-items:center;height:40px;padding:0 16px;box-sizing:border-box;white-space:nowrap;border:1px solid ${i === cur ? C.teal : C.muted};background:${i === cur ? C.teal : 'transparent'};color:${i === cur ? C.ivory : C.ink};font-size:14px">${t(n, ['ملفي الشخصي', 'النشاط التجاري', 'المدفوعات والضرائب', 'الفريق والأدوار', 'الأمان والسجلات'][i], ['Mi perfil', 'Negocio', 'Pagos e impuestos', 'Equipo y roles', 'Seguridad y registros'][i])}</span>`).join('')}</div>${setPane(cur, cls)}`, { h: o.h });

  // ============ boards ============
  const H = (a, b2, c2) => ({ d: a, t: b2, p: c2 });
  const F = (fn, label, hs, widths = ['d', 't', 'p']) => ({ fn, label, hs, widths });
  const ALL = {
    DashHome: [F((c, h) => SCR.home(c, 'filled', { h, railOpen: false }), 'Filled', H(1100, 1500, 1700)), F((c, h) => SCR.home(c, 'empty', { h }), 'Empty', H(800, 900, 900)), F((c, h) => SCR.home(c, 'filled', { h, railOpen: true }), 'Phone rail open', H(0, 0, 900), ['p'])],
    DashBookings: [F((c, h) => SCR.bookings(c, 'filled', { h }), 'Bookings, filled', H(900, 1000, 1500)), F((c, h) => SCR.bookings(c, 'empty', { h }), 'Bookings, empty', H(700, 800, 800))],
    DashNewBooking: [1, 2, 3, 4, 5].map((s) => F((c, h) => SCR.newBooking(c, s, { h }), `New booking · step ${s}`, s === 2 ? H(1500, 1700, 2200) : H(1100, 1300, 1700), s === 2 ? ['d', 't', 'p'] : ['d', 'p'])),
    DashBookingDetail: [F((c, h) => SCR.bookingDetail(c, 'overview', { h }), 'Booking · Overview', H(1300, 1700, 2500)), F((c, h) => SCR.bookingDetail(c, 'payments', { h }), 'Booking · Payments', H(1000, 1000, 1500), ['d', 'p']), F((c, h) => SCR.bookingDetail(c, 'history', { h }), 'Booking · History', H(1100, 1100, 1500), ['d', 'p']), F((c, h) => SCR.bookingDetail(c, 'cancel', { h }), 'Booking · Cancellation request', H(1200, 1200, 1900), ['d', 'p'])],
    DashCustomers: [F((c, h) => SCR.customers(c, 'filled', { h }), 'Customers, filled', H(900, 1000, 1400)), F((c, h) => SCR.customers(c, 'empty', { h }), 'Customers, empty', H(700, 800, 800), ['d', 'p']), F((c, h) => SCR.customer(c, 'details', { h }), 'Customer profile · Details (read-only)', H(1000, 1500, 1700)), F((c, h) => SCR.customer(c, 'bookings', { h }), 'Customer profile · Bookings', H(900, 900, 1500), ['d', 'p']), F((c, h) => SCR.customer(c, 'logs', { h }), 'Customer profile · Logs', H(900, 900, 1200), ['d', 'p'])],
    DashCalendar: [F((c, h) => SCR.calendar(c, 'filled', { h }), 'Calendar, filled', H(1150, 1300, 1000)), F((c, h) => shell(c, 'calendar', d('rail.calendar'), '', calGrid(c, {}), { h, drawer: blockDrawer('all') }), 'Block dates · everything', H(900, 900, 1000), ['d', 'p']), F((c, h) => shell(c, 'calendar', d('rail.calendar'), '', calGrid(c, {}), { h, drawer: blockDrawer('dest') }), 'Block dates · one destination', H(900, 900, 1000), ['d', 'p']), F((c, h) => shell(c, 'calendar', d('rail.calendar'), '', calGrid(c, {}), { h, drawer: blockDrawer('stay') }), 'Block dates · one stay, with a conflict warning', H(900, 900, 1100), ['d', 'p'])],
    DashDestinations: [F((c, h) => SCR.destinations(c, 'filled', { h }), 'Destinations, filled', H(800, 900, 1200)), F((c, h) => SCR.destinations(c, 'filled', { h, sel: 0, drawer: destDrawer('details') }), 'Destination panel · Details', H(900, 900, 1000), ['d', 'p']), F((c, h) => SCR.destinations(c, 'filled', { h, sel: 0, drawer: destDrawer('stays') }), 'Destination panel · Stays (connect several)', H(1000, 1000, 1200), ['d', 'p']), F((c, h) => SCR.destinations(c, 'filled', { h, sel: 0, drawer: destDrawer('all') }), 'Destination panel · All experiences and services (destination and every stay)', H(1000, 1000, 1200), ['d', 'p']), F((c, h) => SCR.destinations(c, 'filled', { h, sel: 0, dialog: delDialog(t('this destination', 'هذه الوجهة', 'este destino')) }), 'Delete destination', H(700, 700, 800), ['d', 'p']), F((c, h) => SCR.destinations(c, 'empty', { h }), 'Destinations, empty', H(700, 800, 800), ['d', 'p'])],
    DashStays: [F((c, h) => SCR.stays(c, 'filled', { h }), 'Stays, filled', H(900, 1000, 1500)), F((c, h) => SCR.stays(c, 'filled', { h, sel: 0, drawer: stayDrawer('details') }), 'Stay panel · Details', H(1000, 1000, 1200), ['d', 'p']), F((c, h) => SCR.stays(c, 'filled', { h, sel: 0, drawer: stayDrawer('ex') }), 'Stay panel · Experiences and services (connect more)', H(1100, 1100, 1300), ['d', 'p']), F((c, h) => SCR.stays(c, 'filled', { h, sel: 0, drawer: stayDrawer('av') }), 'Stay panel · Availability', H(1000, 1000, 1200), ['d', 'p']), F((c, h) => SCR.stays(c, 'empty', { h }), 'Stays, empty', H(700, 800, 800), ['d', 'p'])],
    DashServices: [F((c, h) => SCR.services(c, 'filled', { h }), 'Experiences and services, filled (filter and search)', H(900, 1000, 1500)), F((c, h) => SCR.services(c, 'filled', { h, sel: 0, drawer: svcDrawer('details') }), 'Item panel · Details', H(1000, 1000, 1100), ['d', 'p']), F((c, h) => SCR.services(c, 'filled', { h, sel: 0, drawer: svcDrawer('conn') }), 'Item panel · Connections (destinations and stays)', H(1100, 1100, 1300), ['d', 'p']), F((c, h) => SCR.services(c, 'empty', { h }), 'Experiences and services, empty', H(700, 800, 800), ['d', 'p'])],
    DashPackages: [F((c, h) => SCR.packages(c, { h }), 'Packages · Coming soon', H(700, 800, 900))],
    DashContent: [F((c, h) => cHub(c, { h }), 'Content hub', H(800, 1000, 1200)), F((c, h) => SCR.pagesSoon(c, { h }), 'Pages · Coming soon', H(700, 800, 900))],
    DashPosts: [F((c, h) => SCR.blogSoon(c, { h }), 'Blog · Coming soon', H(700, 800, 900))],
    DashTeamLegal: [F((c, h) => shell(c, 'team', d('rail.team'), btnP(d('newMember'), { plus: true }), emptyState(d('noTeamMembersYet'), btnP(d('newMember'), { plus: true }), t('Only members published here appear on the public site.', 'يظهر في الموقع العام فقط الأعضاء المنشورون هنا.', 'Solo los miembros publicados aquí aparecen en el sitio público.')), { h }), 'Team, empty', H(700, 800, 800)), F((c, h) => shell(c, 'team', d('rail.team'), btnP(d('newMember'), { plus: true }), table(c, [{ h: t('Name', 'الاسم', 'Nombre'), first: true }, { h: t('Role', 'المنصب', 'Cargo') }, { h: t('Shown', 'الظهور', 'Visible'), w: '100px' }], rowsN(4, () => [NAME, t('[Role]', '[المنصب]', '[Cargo]'), sw(true)])), { h, drawer: teamDrawer() }), 'Team member panel', H(800, 800, 1000), ['d', 'p']), F((c, h) => listContent('legal', d('rail.legal'), d('newLegalPage'), d('noLegalPagesYet'), c, 'filled', { h, drawer: legalDrawer() }), 'Legal page panel with versions', H(900, 900, 1100), ['d', 'p']), F((c, h) => listContent('legal', d('rail.legal'), d('newLegalPage'), d('noLegalPagesYet'), c, 'empty', { h }), 'Legal, empty', H(700, 800, 800), ['d', 'p'])],
    DashMediaNav: [F((c, h) => mediaScreen(c, { h }), 'Media library', H(900, 1000, 1200)), F((c, h) => mediaScreen(c, { h, drawer: mediaDrawer() }), 'Media item panel (alt text in three languages)', H(900, 900, 1000), ['d', 'p']), F((c, h) => navScreen(c, { h }), 'Navigation and footer', H(800, 1000, 1300))],
    DashSettings: [0, 1, 2, 3, 4].map((s) => F((c, h) => SCR.settings(c, s, { h }), ['My profile', 'Business and brand', 'Payments and taxes', 'Team and roles', 'Security and logs'][s], s === 3 ? H(700, 800, 800) : H(900, 1000, 1200), ['d', 't', 'p'])),
  };
  const SPLIT = { DashNewBookingA: ALL.DashNewBooking.slice(0, 3), DashNewBookingB: ALL.DashNewBooking.slice(3), DashBookingDetailA: ALL.DashBookingDetail.slice(0, 2), DashBookingDetailB: ALL.DashBookingDetail.slice(2), DashCustomers: ALL.DashCustomers.slice(0, 2), DashCustomerProfile: ALL.DashCustomers.slice(2), DashSettingsA: ALL.DashSettings.slice(0, 3), DashSettingsB: ALL.DashSettings.slice(3) };
  const BOARDS = SPLIT[stem] || ALL[stem];
  let total = 0;
  let OVR = {};
  try { OVR = JSON.parse(fs.readFileSync('/private/tmp/claude-501/-Users-koss-Developer-almarprod-Website-Code/314e86c7-e446-4af1-86cd-2b34d8c37426/scratchpad/gen/heights.json', 'utf8')); } catch (e) { OVR = {}; }
  const CN = { d: 'Desktop 1440', t: 'Tablet 834', p: 'Phone 390' };
  const hOf = (b2, cls) => (OVR[b2.label + ' · ' + CN[cls]] ?? b2.hs[cls]);
  const rowsHtml = BOARDS.map((b2) => {
    const frames = b2.widths.map((cls) => `<div style="display:flex;flex-direction:column;gap:12px;flex:none"><span style="font-size:12px;line-height:1.5;color:${C.muted}"><bdi>${b2.label} · ${CN[cls]}</bdi></span>${b2.fn(cls, hOf(b2, cls))}</div>`).join('');
    total += Math.max(...b2.widths.map((c2) => hOf(b2, c2))) + 42 + 48;
    return `<div style="display:flex;align-items:flex-start;gap:80px">${frames}</div>`;
  });
  return { framesHtml: `<div style="display:flex;flex-direction:column;gap:48px">${rowsHtml.join('')}</div>`, maxH: total };
}
