import { C, icon, LOGO } from './lib.mjs';
import { makeCtx, acctTrigger, siteHeader, inset, WIDTHS, B, primaryBtn } from './public.mjs';

const UP = 'text-transform:{{tt}};letter-spacing:{{ls}};';
const FOCUS = `outline:2px solid ${C.teal};outline-offset:2px;`;
const LG = 'box-shadow:0 28px 56px -16px rgb(10 9 7 / 0.28), 0 10px 20px -10px rgb(10 9 7 / 0.12);';

export function guestBoard(stem, k, H, G) {
  const cx = makeCtx(k, H);
  cx.cartCount = 0;
  cx.signedIn = stem !== 'GuestLogin';
  const g = (key) => k(G.en[key], G.ar[key], G.es[key]);
  const h3 = (get) => k(get(H.en), get(H.ar), get(H.es));
  const T = cx.T;
  const logo = (w) => `<img src="${LOGO}" alt="ALMAR Private Journeys" style="width:${w}px;height:auto;display:block">`;
  const logoW = `<img src="${LOGO}" alt="ALMAR Private Journeys" style="width:150px;height:auto;display:block;filter:invert(1) brightness(2)">`;
  const trig = (c, w = 'auto') => `<span style="display:inline-flex;align-items:center;justify-content:space-between;gap:8px;height:44px;width:${w};padding:0 16px;box-sizing:border-box;border:1px solid ${C.muted};color:${C.ink};font-size:12px;${UP}"><bdi>${c}</bdi>${icon('chevron-down', 12, 'currentColor')}</span>`;
  const field = (label, value, o = {}) => `<div style="display:flex;flex-direction:column;gap:8px;width:100%"><span style="font-size:14px;line-height:{{lhL}};color:${C.ink}">${label}</span><span style="display:flex;align-items:center;height:44px;box-sizing:border-box;padding:0 16px;background:${C.surface};border:1px solid ${o.err ? C.error : C.ink};font-size:16px;color:${value ? C.ink : C.muted};${o.focus ? `border-color:${C.teal};box-shadow:inset 0 0 0 1px ${C.teal};` : ''}"><bdi>${value || ''}</bdi></span>${o.err ? `<div role="alert" style="display:flex;align-items:center;gap:8px;color:${C.error};font-size:14px;line-height:{{lhL}}">${icon('alert-circle', 20, C.error)}<span>${o.err}</span></div>` : ''}</div>`;
  const EM = k('[Email]', '[البريد]', '[Correo]');
  const GUEST = k('[Guest name]', '[اسم الضيف]', '[Nombre del huésped]');
  const PH = k('[Phone]', '[الهاتف]', '[Teléfono]');
  const secBtn = (t, w) => `<span style="display:inline-flex;align-items:center;justify-content:center;height:44px;${w ? `width:${w};` : ''}padding:0 24px;box-sizing:border-box;border:1px solid ${C.teal};color:${C.teal};font-size:14px;${UP}">${t}</span>`;
  const chipD = (txt, gold) => `<span style="display:inline-flex;align-items:center;height:24px;padding:0 8px;box-sizing:border-box;border:1px solid ${gold ? C.gold : C.ink};font-size:12px;color:${C.ink};background:${C.ivory};white-space:nowrap">${txt}</span>`;
  const heroTitle = h3((h) => h.heroTitle);
  const kickerL = (t, color) => `<span style="font-size:12px;line-height:{{lhC}};${UP}color:${color}">${t}</span>`;

  // ---------- LOGIN (sign in or create, one page) ----------
  const TITLE = k('Sign in or create an account', 'سجّل الدخول أو أنشئ حسابًا', 'Inicia sesión o crea una cuenta');
  const HELP = k('We email you a one-time link. No password to remember.', 'نرسل إليك رابطًا لمرة واحدة. لا كلمة مرور لتتذكرها.', 'Te enviamos un enlace de un solo uso. Sin contraseña que recordar.');
  const NEW = k('New here? Your account is created the first time you use the link.', 'جديد هنا؟ يُنشأ حسابك عند أول استخدام للرابط.', '¿Primera vez? Tu cuenta se crea la primera vez que usas el enlace.');
  const LEGAL = k('[Terms and privacy line]', '[سطر الشروط والخصوصية]', '[Línea de términos y privacidad]');
  const SENT_T = k('Check your email', 'تحقق من بريدك', 'Revisa tu correo');
  const SENT_B = k('We sent a sign-in link to', 'أرسلنا رابط تسجيل الدخول إلى', 'Enviamos un enlace de acceso a');
  const OTHER = k('Use a different email', 'استخدم بريدًا آخر', 'Usar otro correo');
  const formBlock = (cls, st) => {
    const ts = cls === 'p' ? 24 : 32;
    const title = `<h1 style="margin:0;font-family:{{fd}};font-weight:400;font-size:${ts}px;line-height:{{lh2}};letter-spacing:{{tk}};color:${C.teal}">${st === 'sent' ? SENT_T : TITLE}</h1>`;
    if (st === 'sent') return `<div style="display:flex;flex-direction:column;gap:24px;width:100%;max-width:432px"><span style="display:flex;align-items:center;justify-content:center;width:56px;height:56px;background:${C.tealTint}">${icon('mail', 24, C.teal)}</span>${title}<p style="margin:0;font-size:16px;line-height:{{lhB}};color:${C.ink}">${SENT_B} <bdi style="color:${C.teal}">${EM}</bdi></p>${secBtn(OTHER)}</div>`;
    return `<div style="display:flex;flex-direction:column;gap:24px;width:100%;max-width:432px">${title}<p style="margin:0;font-size:16px;line-height:{{lhB}};color:${C.muted}">${HELP}</p>${field(g('email'), st === 'typed' || st === 'focus' ? EM : '', st === 'error' ? { err: g('enterEmail') } : st === 'focus' || st === 'typed' ? { focus: true } : {})}${primaryBtn(g('accessWithMagicLink'), 'height:56px;width:100%;box-sizing:border-box;')}<div style="display:flex;flex-direction:column;gap:12px;padding-top:24px;border-top:1px solid ${C.line}"><span style="font-size:14px;line-height:{{lhL}};color:${C.ink}">${NEW}</span><span style="font-size:12px;line-height:{{lhC}};color:${C.muted}">${LEGAL}</span></div></div>`;
  };
  const photo = (w, h, inner) => `<div style="position:relative;width:${w}px;height:${h}px;overflow:hidden;background:${C.teal};flex:none"><img src="${B.hero}" alt="${h3((x) => x.heroImageAlt)}" style="position:absolute;inset:0;width:100%;height:100%;object-fit:cover;display:block"><div style="position:absolute;inset:0;background:rgba(38,38,38,0.32)"></div>${inner}</div>`;
  const photoText = (sz, pad) => `<div style="position:absolute;left:${pad}px;right:${pad}px;bottom:${pad}px;display:flex;flex-direction:column;gap:12px">${kickerL('ALMAR Private Journeys', C.ivory)}<span style="font-family:{{fd}};font-size:${sz}px;line-height:{{lh1}};letter-spacing:{{tk}};color:${C.ivory}">${heroTitle}</span></div>`;
  const loginFrame = (cls, st) => {
    if (cls === 'd') return `<div style="width:1440px;height:900px;box-sizing:border-box;background:${C.ivory};border:1px solid ${C.line};display:flex;overflow:hidden"><div style="width:560px;flex:none;box-sizing:border-box;padding:32px 64px;display:flex;flex-direction:column;justify-content:space-between"><div style="display:flex;align-items:center;justify-content:space-between">${logo(150)}${trig('EN')}</div>${formBlock('d', st)}<span style="font-size:12px;line-height:{{lhC}};color:${C.muted}"><bdi>inquiries@almarprivatejourney.com</bdi></span></div><div style="flex:1;padding:16px;box-sizing:border-box">${photo(848, 866, photoText(48, 48))}</div></div>`;
    if (cls === 't') return `<div style="width:834px;height:1000px;box-sizing:border-box;background:${C.ivory};border:1px solid ${C.line};display:flex;flex-direction:column;overflow:hidden">${photo(832, 340, `<div style="position:absolute;left:32px;right:32px;top:24px;display:flex;align-items:center;justify-content:space-between">${logoW}${trig('EN').replace(C.muted, 'rgba(255,250,240,0.7)').replace(`color:${C.ink}`, `color:${C.ivory}`)}</div>${photoText(48, 32)}`)}<div style="flex:1;padding:48px 32px 0;display:flex;justify-content:center;box-sizing:border-box">${formBlock('t', st)}</div></div>`;
    return `<div style="width:390px;height:844px;box-sizing:border-box;background:${C.ivory};border:1px solid ${C.line};display:flex;flex-direction:column;overflow:hidden">${photo(388, 260, `<div style="position:absolute;left:16px;right:16px;top:16px;display:flex;align-items:center;justify-content:space-between">${logoW.replace('width:150px', 'width:112px')}${trig('EN').replace(C.muted, 'rgba(255,250,240,0.7)').replace(`color:${C.ink}`, `color:${C.ivory}`)}</div>${photoText(32, 16)}`)}<div style="flex:1;padding:24px 16px 0;box-sizing:border-box">${formBlock('p', st)}</div></div>`;
  };

  // ---------- shared bits for the richer account, bookings and trip pages ----------
  const chipS = (en, ar, es, gold) => chipD(k(en, ar, es), gold);
  const st = {
    confirmed: () => chipS('Confirmed', 'مؤكد', 'Confirmado', true), deposit: () => chipS('Deposit paid', 'تم دفع المقدّم', 'Depósito pagado', false),
    done: () => chipS('Completed', 'مكتمل', 'Completado', false), driver: () => chipS('Driver assigned', 'تم تعيين السائق', 'Conductor asignado', false), flights: () => chipS('Flights booked', 'تم حجز الرحلات الجوية', 'Vuelos reservados', false),
  };
  const bdiN = (t) => `<bdi style="font-variant-numeric:tabular-nums">${t}</bdi>`;
  const DATES = bdiN('[DD/MM/YYYY] – [DD/MM/YYYY]'), AMT = bdiN('AED [AMOUNT]');
  const TRIP = k('[Trip name]', '[اسم الرحلة]', '[Nombre del viaje]');
  const ADULTS = k('2 adults', 'بالغان', '2 adultos');
  const ghost = (t) => `<span style="display:inline-flex;align-items:center;min-height:44px;padding:0 8px;font-size:14px;color:${C.teal}">${t}</span>`;
  const card = (title, inner, extra = '') => `<section style="background:${C.surface};border:1px solid ${C.line};padding:24px;display:flex;flex-direction:column;gap:16px;box-sizing:border-box;${extra}"><h2 style="margin:0;font-family:{{fd}};font-weight:400;font-size:20px;line-height:{{lhT}};color:${C.teal}">${title}</h2>${inner}</section>`;
  const page = (cls, W, Hh, title, body, sub) => { const hd = siteHeader(cx, W, cls); return `<div style="width:${W}px;height:${Hh}px;box-sizing:border-box;background:${C.ivory};border:1px solid ${C.line};overflow:hidden;display:flex;flex-direction:column">${hd.html}<main style="flex:1;min-height:0;padding:32px ${inset(cls)}px 0;display:flex;flex-direction:column;gap:24px"><div style="display:flex;flex-direction:column;gap:8px">${sub || ''}<h1 style="margin:0;font-family:{{fd}};font-weight:400;font-size:${cls === 'p' ? 32 : 48}px;line-height:{{lh1}};letter-spacing:{{tk}};color:${C.teal}">${title}</h1></div>${body}</main></div>`; };
  const SIZE = { d: [1440, 1440], t: [834, 2500], p: [390, 3300] };
  const empty1 = (t) => `<span style="font-size:14px;line-height:{{lhL}};color:${C.muted}">${t}</span>`;

  // ---------- ACCOUNT (organized: grouped rail with help, sectioned content) ----------
  const G_PERS = k('Personal', 'شخصي', 'Personal'), G_SET = k('Settings', 'الإعدادات', 'Ajustes');
  const PERS = k('Profile', 'الملف الشخصي', 'Perfil'), TRAV = k('Saved travelers', 'المسافرون المحفوظون', 'Viajeros guardados'), SAVED = k('Saved stays', 'الإقامات المحفوظة', 'Estancias guardadas'), PREF = k('Preferences', 'التفضيلات', 'Preferencias'), NOTI = k('Email notifications', 'إشعارات البريد', 'Notificaciones por correo'), SEC = k('Sign-in and security', 'تسجيل الدخول والأمان', 'Acceso y seguridad'), HELPQ = k('Need help?', 'تحتاج مساعدة؟', '¿Necesitas ayuda?'), CUR = k('Currency', 'العملة', 'Moneda');
  const DEL = k('Delete account', 'حذف الحساب', 'Eliminar cuenta');
  const wa = `<a href="https://wa.me/971563883302" style="display:inline-flex;align-items:center;gap:12px;align-self:flex-start;min-height:44px;padding:0 16px;box-sizing:border-box;background:${C.whatsapp};color:${C.ink};font-size:14px;text-decoration:none"><bdi>WhatsApp</bdi><bdi style="font-size:12px">wa.me/971563883302</bdi></a>`;
  const swt = (label, on) => `<div style="display:flex;align-items:center;justify-content:space-between;gap:16px;min-height:44px;font-size:14px;line-height:{{lhL}};color:${C.ink}"><span>${label}</span><span style="display:flex;align-items:center;justify-content:${on ? 'flex-end' : 'flex-start'};width:44px;height:24px;padding:3px;box-sizing:border-box;background:${on ? C.teal : C.surface};border:1px solid ${on ? C.teal : C.ink};flex:none"><span style="width:16px;height:16px;background:${on ? C.ivory : C.ink};display:block"></span></span></div>`;
  const groupHead = (t, sub) => `<div style="display:flex;flex-direction:column;gap:4px;padding-top:24px;border-top:2px solid ${C.gold}"><h2 style="margin:0;font-family:{{fd}};font-weight:400;font-size:32px;line-height:{{lh2}};color:${C.teal}">${t}</h2>${sub ? `<span style="font-size:14px;line-height:{{lhL}};color:${C.muted}">${sub}</span>` : ''}</div>`;
  const helpCard = () => card(HELPQ, `<span style="font-size:14px;line-height:{{lhL}};color:${C.ink}">${k('Message your concierge on WhatsApp.', 'راسل الكونسيرج عبر واتساب.', 'Escribe a tu conserje por WhatsApp.')}</span>${wa}<bdi style="font-size:14px;color:${C.ink}">inquiries@almarprivatejourney.com</bdi>`);
  const railNav = (cls, cur) => {
    const grp = (label, items) => `<div style="display:flex;flex-direction:column"><span style="padding:12px 16px 4px;font-size:12px;line-height:{{lhC}};${UP}color:${C.muted}">${label}</span>${items.map((n) => `<span style="display:flex;align-items:center;min-height:44px;padding:0 16px;font-size:14px;background:${n === cur ? C.tealTint : 'transparent'};color:${n === cur ? C.teal : C.ink}">${n}</span>`).join('')}</div>`;
    return `<nav aria-label="${g('account')}" style="display:flex;flex-direction:column;background:${C.surface};border:1px solid ${C.line};padding:8px 0;box-sizing:border-box">${grp(G_PERS, [PERS, TRAV, SAVED])}${grp(G_SET, [PREF, NOTI, SEC])}<span style="display:flex;align-items:center;min-height:44px;padding:0 16px;margin-top:8px;border-top:1px solid ${C.line};font-size:14px;color:${C.error}">${DEL}</span></nav>`;
  };
  const accountFrame = (cls, state) => {
    const [W] = SIZE[cls]; const Hh = { d: 1900, t: 2500, p: 2700 }[cls]; const filled = state === 'filled';
    const two = cls === 'd';
    const trav = filled ? ['Adult', 'Child'].map((r, i) => `<div style="display:flex;align-items:center;justify-content:space-between;gap:12px;min-height:56px;border-bottom:1px solid ${C.line}"><div style="display:flex;flex-direction:column"><span style="font-size:14px;color:${C.ink}">${T('[Name]')}</span><span style="font-size:12px;line-height:{{lhC}};color:${C.muted}">${i === 0 ? k('Adult', 'بالغ', 'Adulto') : k('Child', 'طفل', 'Niño')}</span></div>${ghost(k('Edit', 'تعديل', 'Editar'))}</div>`).join('') : empty1(k('No travelers saved yet', 'لا مسافرين محفوظين بعد', 'Aún no hay viajeros guardados'));
    const saved = filled ? H.en.stays.slice(0, 2).map((x, i) => `<div style="display:flex;align-items:center;gap:12px;min-height:72px"><img src="${i === 0 ? B.stay : B.walled}" alt="${k(x.name, H.ar.stays[i].name, H.es.stays[i].name)}" style="width:96px;height:72px;object-fit:cover;display:block;flex:none"><span style="flex:1;min-width:0;font-family:{{fd}};font-size:16px;line-height:{{lhT}};color:${C.teal}">${k(x.name, H.ar.stays[i].name, H.es.stays[i].name)}</span><span style="display:flex;width:44px;height:44px;align-items:center;justify-content:center">${icon('heart', 20, C.teal, false, C.teal)}</span></div>`).join('') : empty1(k('No saved stays yet', 'لا إقامات محفوظة بعد', 'Aún no hay estancias guardadas'));
    const prof = card(PERS, `<div style="display:grid;grid-template-columns:repeat(${two ? 3 : 1},minmax(0,1fr));gap:16px">${field(g('name'), filled ? GUEST : '')}${field(g('email'), filled ? EM : '')}${field(g('phone'), filled ? PH : '')}</div>`);
    const travC = card(TRAV, `<div style="display:flex;flex-direction:column">${trav}</div><span style="display:inline-flex;align-items:center;height:44px;padding:0 24px;box-sizing:border-box;border:1px solid ${C.teal};color:${C.teal};font-size:14px;align-self:flex-start;${UP}">${k('Add a traveler', 'أضف مسافرًا', 'Añadir viajero')}</span>`);
    const savedC = card(SAVED, `<div style="display:flex;flex-direction:column;gap:8px">${saved}</div>`);
    const prefC = card(PREF, `<div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px"><div style="display:flex;flex-direction:column;gap:8px"><span style="font-size:14px;color:${C.ink}">${g('language')}</span>${trig('EN', '100%')}</div><div style="display:flex;flex-direction:column;gap:8px"><span style="font-size:14px;color:${C.ink}">${CUR}</span>${trig('AED', '100%')}</div></div>`);
    const notiC = card(NOTI, `<div style="display:flex;flex-direction:column">${swt(k('Booking updates', 'تحديثات الحجز', 'Novedades de la reserva'), true)}${swt(k('Offers and stories', 'العروض والقصص', 'Ofertas e historias'), false)}</div>`);
    const secC = card(SEC, `<span style="font-size:14px;line-height:{{lhL}};color:${C.ink}">${k('Signed in as', 'مسجّل الدخول باسم', 'Sesión iniciada como')} <bdi style="color:${C.teal}">${filled ? EM : ''}</bdi></span><span style="font-size:12px;line-height:{{lhC}};color:${C.muted}">${k('You sign in with a one-time link sent to this email.', 'تسجّل الدخول برابط لمرة واحدة يُرسل إلى هذا البريد.', 'Accedes con un enlace de un solo uso enviado a este correo.')}</span><span style="display:inline-flex;align-items:center;height:44px;padding:0 24px;box-sizing:border-box;border:1px solid ${C.muted};color:${C.ink};font-size:14px;align-self:flex-start">${g('signOut')}</span>`);
    const delC = `<section style="background:${C.surface};border:1px solid ${C.error};padding:24px;display:flex;flex-direction:${two ? 'row' : 'column'};align-items:${two ? 'center' : 'flex-start'};justify-content:space-between;gap:16px;box-sizing:border-box"><div style="display:flex;flex-direction:column;gap:4px"><h2 style="margin:0;font-family:{{fd}};font-weight:400;font-size:20px;line-height:{{lhT}};color:${C.error}">${DEL}</h2><span style="font-size:14px;line-height:{{lhL}};color:${C.ink}">${k('Removes your profile, saved travelers and saved stays for good.', 'يحذف ملفك الشخصي والمسافرين والإقامات المحفوظة نهائيًا.', 'Elimina tu perfil, viajeros y estancias guardadas para siempre.')}</span></div><span style="display:inline-flex;align-items:center;height:44px;padding:0 24px;box-sizing:border-box;border:1px solid ${C.error};color:${C.ink};font-size:14px;flex:none">${DEL}</span></section>`;
    const g2 = (a, b2) => `<div style="display:grid;grid-template-columns:repeat(${two ? 2 : 1},minmax(0,1fr));gap:24px;align-items:start">${a}${b2}</div>`;
    const content = `<div style="display:flex;flex-direction:column;gap:24px;flex:1;min-width:0">${groupHead(G_PERS, k('Who you are and who travels with you.', 'من أنت ومن يسافر معك.', 'Quién eres y quién viaja contigo.'))}${prof}${g2(travC, savedC)}${groupHead(G_SET, k('Language, updates and how you sign in.', 'اللغة والتحديثات وطريقة الدخول.', 'Idioma, avisos y cómo accedes.'))}${g2(prefC, notiC)}${secC}${delC}</div>`;
    const rail = `<div style="width:${two ? 280 : 0}px;flex:none;display:flex;flex-direction:column;gap:24px;${two ? 'position:relative;' : ''}">${railNav(cls, PERS)}${helpCard()}</div>`;
    const summary = `<div style="display:flex;align-items:center;gap:16px"><span style="display:flex;align-items:center;justify-content:center;width:64px;height:64px;background:${C.tealTint};flex:none"><img src="${B.mono}" alt="" style="width:36px;height:auto;display:block"></span><div style="display:flex;flex-direction:column;gap:2px;min-width:0"><span style="font-family:{{fd}};font-size:20px;line-height:{{lhT}};color:${C.teal}">${filled ? GUEST : g('account')}</span><span style="font-size:14px;color:${C.muted}"><bdi>${filled ? EM : ''}</bdi></span></div></div>`;
    const chips = `<nav style="display:flex;gap:8px;overflow:hidden">${[PERS, TRAV, SAVED, PREF, NOTI, SEC].map((n, i) => `<span style="display:inline-flex;align-items:center;height:40px;padding:0 16px;box-sizing:border-box;white-space:nowrap;border:1px solid ${i === 0 ? C.teal : C.muted};background:${i === 0 ? C.teal : 'transparent'};color:${i === 0 ? C.ivory : C.ink};font-size:14px">${n}</span>`).join('')}</nav>`;
    const body = two ? `<div style="display:flex;gap:32px;align-items:flex-start">${rail}${content}</div>` : `<div style="display:flex;flex-direction:column;gap:16px">${summary}${chips}${content}${helpCard()}</div>`;
    return page(cls, W, Hh, g('account'), body);
  };

  // ---------- BOOKINGS ----------
  const tile = (label, value) => `<div style="background:${C.surface};border:1px solid ${C.line};padding:16px;display:flex;flex-direction:column;gap:4px;box-sizing:border-box"><span style="font-size:12px;line-height:{{lhC}};${UP}color:${C.muted}">${label}</span><span style="font-size:32px;line-height:1.2;font-variant-numeric:tabular-nums;color:${C.ink}">${value}</span></div>`;
  const progress = `<div style="display:flex;flex-direction:column;gap:8px"><div style="display:flex;align-items:center;justify-content:space-between;gap:12px;font-size:14px;line-height:{{lhL}};color:${C.ink}"><span>${k('Paid', 'المدفوع', 'Pagado')} ${AMT}</span><span style="color:${C.muted}">${AMT}</span></div><div style="height:4px;background:${C.line};display:block"><div style="width:30%;height:4px;background:${C.teal}"></div></div><span style="font-size:12px;line-height:{{lhC}};color:${C.muted}">${k('Balance due by', 'الرصيد مستحق قبل', 'Saldo pendiente antes del')} ${bdiN('[DD/MM/YYYY]')}</span></div>`;
  const chipReq = () => chipS('Cancellation requested', 'تم طلب الإلغاء', 'Cancelación solicitada', false);
  const CANCEL_A = k('Request cancellation', 'اطلب الإلغاء', 'Solicitar cancelación');
  const bookingCard = (cls, i) => `<article style="display:flex;flex-direction:${cls === 'd' ? 'row' : 'column'};background:${C.surface};border:1px solid ${C.line};box-sizing:border-box"><img src="${i === 0 ? B.stay : B.walled}" alt="${TRIP}" style="width:${cls === 'd' ? '280px' : '100%'};height:${cls === 'd' ? 340 : 200}px;object-fit:cover;display:block;flex:none"><div style="flex:1;min-width:0;min-height:${cls === 'd' ? 340 : 0}px;box-sizing:border-box;padding:24px;display:flex;flex-direction:column;gap:16px"><div style="display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap"><div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap">${i === 0 ? st.confirmed() : chipReq()}${i === 0 ? st.driver() : ''}</div><bdi style="font-size:12px;font-variant-numeric:tabular-nums;color:${C.muted}">ALMAR-000000</bdi></div><div style="display:flex;flex-direction:column;gap:4px"><span style="font-family:{{fd}};font-size:20px;line-height:{{lhT}};color:${C.teal}">${TRIP}</span><span style="font-size:14px;line-height:{{lhL}};color:${C.ink}">${DATES} · ${ADULTS}</span><span style="font-size:14px;line-height:{{lhL}};color:${C.teal}">${k('In [n] days', 'خلال [n] أيام', 'En [n] días')}</span></div>${progress}<div style="display:flex;align-items:center;gap:12px;flex-wrap:wrap">${i === 0 ? primaryBtn(k('Pay balance', 'ادفع الرصيد', 'Pagar saldo')) + secBtn(k('Add experiences and services', 'أضف تجارب وخدمات', 'Añadir experiencias y servicios')) + ghost(k('View trip', 'عرض الرحلة', 'Ver viaje')) + `<span style="display:inline-flex;align-items:center;min-height:44px;padding:0 8px;font-size:14px;color:${C.error}">${CANCEL_A}</span>` : secBtn(k('View request', 'عرض الطلب', 'Ver solicitud')) + ghost(k('View trip', 'عرض الرحلة', 'Ver viaje'))}</div></div></article>`;
  const bookingsFrame = (cls, state) => {
    const [W, Hh0] = SIZE[cls]; const Hh = { d: 1240, t: 1800, p: 2400 }[cls]; const filled = state === 'filled';
    const tiles = `<div style="display:grid;grid-template-columns:repeat(${cls === 'p' ? 1 : 3},minmax(0,1fr));gap:16px">${tile(k('Upcoming trips', 'الرحلات القادمة', 'Próximos viajes'), filled ? '[2]' : '[0]')}${tile(k('Balance due', 'الرصيد المستحق', 'Saldo pendiente'), filled ? 'AED [AMOUNT]' : '—')}${tile(k('Next departure', 'المغادرة القادمة', 'Próxima salida'), filled ? '[DD/MM/YYYY]' : '—')}</div>`;
    const tab = (t, on) => `<span style="display:inline-flex;align-items:center;min-height:44px;padding:0 16px;font-size:14px;color:${on ? C.teal : C.muted};box-shadow:${on ? `inset 0 -3px 0 ${C.teal}` : 'none'}">${t}</span>`;
    const tools = `<div style="display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap;border-bottom:1px solid ${C.line}"><div role="tablist" style="display:flex">${tab(k('Upcoming', 'القادمة', 'Próximos'), true)}${tab(k('Past', 'السابقة', 'Pasados'))}${tab(g('cancelledTab') || k('Cancelled', 'الملغاة', 'Cancelados'))}</div>${cls === 'p' ? '' : fieldBox2(icon('search', 20, C.teal, true), k('Search by reference or trip', 'ابحث بالمرجع أو الرحلة', 'Buscar por referencia o viaje'), 320)}</div>`;
    const empty = `<div style="display:flex;flex-direction:${cls === 'd' ? 'row' : 'column'};background:${C.surface};border:1px solid ${C.line};box-sizing:border-box"><img src="${B.walled}" alt="" style="width:${cls === 'd' ? '50%' : '100%'};height:${cls === 'd' ? 380 : 220}px;object-fit:cover;display:block;flex:none"><div style="flex:1;padding:${cls === 'd' ? 48 : 24}px;display:flex;flex-direction:column;justify-content:center;gap:16px;align-items:flex-start"><span style="font-family:{{fd}};font-size:${cls === 'p' ? 24 : 32}px;line-height:{{lh2}};color:${C.teal}">${g('noBookingsYet')}</span>${primaryBtn(g('startATrip'))}</div></div>`;
    const list = filled ? `<div style="display:flex;flex-direction:column;gap:24px">${bookingCard(cls, 0)}${bookingCard(cls, 1)}</div>` : empty;
    return page(cls, W, Hh, g('bookings'), `${tiles}${tools}${list}`);
  };
  function fieldBox2(ic, txt, w) { return `<span style="display:flex;align-items:center;gap:8px;height:44px;width:${w}px;box-sizing:border-box;padding:0 16px;background:${C.surface};border:1px solid ${C.ink};font-size:14px;color:${C.muted}">${ic}<span>${txt}</span></span>`; }

  // ---------- TRIP DETAIL (reimagined: manage menu, status rail, stay, day-by-day itinerary, sticky payment) ----------
  const tripFrame = (cls) => {
    const [W] = SIZE[cls]; const Hh = { d: 1760, t: 2500, p: 2900 }[cls]; const hd = siteHeader(cx, W, cls); const i0 = inset(cls); const cw = W - 2 * i0;
    const colW = cls === 'd' ? cw - 400 - 32 : cw;
    const bdiT = (t2) => `<bdi style="font-variant-numeric:tabular-nums">${t2}</bdi>`;
    const manage = `<span style="display:inline-flex;align-items:center;gap:8px;height:44px;padding:0 16px;box-sizing:border-box;border:1px solid ${C.teal};color:${C.teal};font-size:14px;${UP}">${k('Manage booking', 'إدارة الحجز', 'Gestionar reserva')}${icon('chevron-down', 12, 'currentColor')}</span>`;
    const mi = (t2, color) => `<span role="menuitem" style="display:flex;align-items:center;min-height:44px;padding:0 16px;font-size:14px;color:${color || C.ink}">${t2}</span>`;
    const manageMenu = `<div role="menu" style="position:absolute;top:52px;inset-inline-end:0;width:288px;background:${C.surface};box-shadow:0 28px 56px -16px rgb(10 9 7 / 0.28), 0 10px 20px -10px rgb(10 9 7 / 0.12);z-index:2">${mi(k('Add experiences and services', 'أضف تجارب وخدمات', 'Añadir experiencias y servicios'))}${mi(k('Message your concierge', 'راسل الكونسيرج', 'Escribe a tu conserje'))}<div style="border-top:1px solid ${C.line}">${mi(k('Request cancellation and refund', 'اطلب الإلغاء والاسترداد', 'Solicitar cancelación y reembolso'), C.error)}</div></div>`;
    const top = `<div style="display:flex;flex-direction:column;gap:12px"><span style="display:inline-flex;align-items:center;min-height:44px;font-size:14px;color:${C.teal}">‹ ${g('bookings')}</span><div style="display:flex;align-items:flex-start;justify-content:space-between;gap:24px;flex-wrap:wrap"><div style="display:flex;flex-direction:column;gap:12px;min-width:0"><div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap">${st.confirmed()}${st.driver()}<bdi style="font-size:12px;font-variant-numeric:tabular-nums;color:${C.muted}">ALMAR-000000</bdi></div><h1 style="margin:0;font-family:{{fd}};font-weight:400;font-size:${cls === 'p' ? 32 : 48}px;line-height:{{lh1}};letter-spacing:{{tk}};color:${C.teal}">${TRIP}</h1><span style="font-size:16px;line-height:{{lhB}};color:${C.ink}">${DATES} · ${ADULTS}</span></div><div style="position:relative;flex:none">${manage}${cls === 'd' ? manageMenu : ''}</div></div></div>`;
    const steps = [['Deposit paid', 'تم دفع المقدّم', 'Depósito pagado', 'done'], ['Confirmed', 'مؤكد', 'Confirmado', 'cur'], ['In trip', 'في الرحلة', 'En viaje', 'up'], ['Completed', 'مكتمل', 'Completado', 'up']];
    const rail = cls === 'p' ? `<div style="display:flex;flex-direction:column;gap:8px"><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:4px">${steps.map(([, , , sx]) => `<span style="height:3px;background:${sx === 'up' ? C.line : C.teal};display:block"></span>`).join('')}</div><span style="font-size:12px;line-height:{{lhC}};color:${C.muted}">${k('Confirmed', 'مؤكد', 'Confirmado')} · ${k('In [n] days', 'خلال [n] أيام', 'En [n] días')}</span></div>` : `<ol style="margin:0;padding:0;list-style:none;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));border-bottom:1px solid ${C.line}">${steps.map(([a2, b2, c2, sx], i) => `<li style="display:flex;align-items:center;gap:12px;padding-bottom:16px;${sx === 'cur' ? `box-shadow:inset 0 -3px 0 ${C.teal};` : ''}"><span style="display:flex;align-items:center;justify-content:center;width:28px;height:28px;box-sizing:border-box;${sx === 'done' ? `background:${C.teal};color:${C.ivory}` : `border:1px solid ${sx === 'cur' ? C.teal : C.muted};color:${sx === 'cur' ? C.teal : C.muted}`};font-size:12px">${sx === 'done' ? icon('check', 14, C.ivory) : i + 1}</span><span style="font-size:14px;line-height:{{lhL}};color:${sx === 'up' ? C.muted : C.teal}">${k(a2, b2, c2)}</span></li>`).join('')}</ol>`;
    const stayC = `<section style="background:${C.surface};border:1px solid ${C.line};box-sizing:border-box"><img src="${B.stay}" alt="${TRIP}" style="width:100%;height:${cls === 'p' ? 200 : 300}px;object-fit:cover;display:block"><div style="padding:24px;display:flex;flex-direction:column;gap:12px"><span style="font-size:12px;line-height:{{lhC}};${UP}color:${C.muted}">${k('Your stay', 'إقامتك', 'Tu estancia')}</span><span style="font-family:{{fd}};font-size:20px;line-height:{{lhT}};color:${C.teal}">${k(H.en.stays[0].name, H.ar.stays[0].name, H.es.stays[0].name)}</span><span style="font-size:14px;line-height:{{lhL}};color:${C.muted}">${k('Exact address after confirmation.', 'العنوان الدقيق بعد التأكيد.', 'Dirección exacta tras la confirmación.')}</span><div style="display:flex;gap:8px;flex-wrap:wrap">${st.driver()}${st.flights()}</div></div></section>`;
    const item = (kind, name, img, added) => `<div style="display:flex;align-items:center;gap:12px;min-height:64px"><span style="width:64px;flex:none;font-size:14px;line-height:{{lhL}};color:${C.muted}">${bdiT(k('[Time]', '[الوقت]', '[Hora]'))}</span>${img ? `<img src="${img}" alt="${name}" style="width:64px;height:48px;object-fit:cover;display:block;flex:none">` : `<span style="width:64px;height:48px;background:${C.tealTint};display:block;flex:none"></span>`}<div style="flex:1;min-width:0;display:flex;flex-direction:column"><span style="font-size:12px;line-height:{{lhC}};${UP}color:${C.muted}">${kind}</span><span style="font-family:{{fd}};font-size:16px;line-height:{{lhT}};color:${C.teal}">${name}</span></div>${added ? `<span style="font-size:12px;color:${C.teal}">${T('Added')}</span>` : ''}</div>`;
    const day = (n, items) => `<div style="display:${cls === 'p' ? 'flex;flex-direction:column;gap:8px' : 'grid;grid-template-columns:140px minmax(0,1fr);column-gap:24px'};padding:16px 0;border-top:1px solid ${C.line}"><div style="display:flex;flex-direction:column;gap:2px"><span style="font-family:{{fd}};font-size:20px;line-height:{{lhT}};color:${C.teal}">${k('Day ' + n, 'اليوم ' + n, 'Día ' + n)}</span>${bdiT('<span style="font-size:14px;color:' + C.muted + '">[DD/MM/YYYY]</span>')}</div><div style="display:flex;flex-direction:column;border-inline-start:2px solid ${C.tealTint};padding-inline-start:16px">${items.join('')}</div></div>`;
    const ACT = k('[Activity]', '[النشاط]', '[Actividad]'), SVC = k('Service', 'خدمة', 'Servicio'), EXP = T('Experience');
    const itin = `<section style="display:flex;flex-direction:column;gap:8px"><div style="display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap"><h2 style="margin:0;font-family:{{fd}};font-weight:400;font-size:${cls === 'p' ? 24 : 32}px;line-height:{{lh2}};color:${C.teal}">${k('Day by day', 'يومًا بيوم', 'Día a día')}</h2>${secBtn(k('Add experiences and services', 'أضف تجارب وخدمات', 'Añadir experiencias y servicios'))}</div><div style="background:${C.surface};border:1px solid ${C.line};padding:8px 24px 16px">${day(1, [item(SVC, ACT), item(SVC, ACT), item(SVC, ACT)])}${day(2, [item(EXP, T('Cartagena Heritage Tours'), B.heritage, true), item(SVC, ACT)])}${day(3, [item(EXP, T('Rosario Islands Escape'), B.rosario, true), item(SVC, ACT)])}</div></section>`;
    const line = (a2, v, bold) => `<div style="display:flex;justify-content:space-between;gap:12px;font-size:${bold ? 20 : 14}px;line-height:{{lhL}};color:${C.ink}${bold ? ';font-weight:700' : ''}"><span>${a2}</span><span>${v}</span></div>`;
    const pay = `<section style="background:${C.surface};border:1px solid ${C.line};border-top:2px solid ${C.gold};padding:24px;display:flex;flex-direction:column;gap:16px;box-sizing:border-box"><div style="display:flex;flex-direction:column;gap:4px"><span style="font-size:12px;line-height:{{lhC}};${UP}color:${C.muted}">${k('Balance due', 'الرصيد المستحق', 'Saldo pendiente')}</span><span style="font-family:{{fd}};font-size:32px;line-height:{{lh2}};color:${C.teal};font-variant-numeric:tabular-nums"><bdi>AED [AMOUNT]</bdi></span><span style="font-size:12px;line-height:{{lhC}};color:${C.muted}">${k('Balance due by', 'الرصيد مستحق قبل', 'Saldo pendiente antes del')} ${bdiT('[DD/MM/YYYY]')}</span></div>${primaryBtn(k('Pay balance', 'ادفع الرصيد', 'Pagar saldo'), 'height:56px;width:100%;box-sizing:border-box;')}<div style="display:flex;flex-direction:column;gap:12px;padding-top:12px;border-top:1px solid ${C.line}">${line(k('Subtotal', 'المجموع الفرعي', 'Subtotal'), AMT)}${line(k('VAT [RATE]%', 'ضريبة القيمة المضافة [RATE]٪', 'IVA [RATE]%'), AMT)}${line(k('Total', 'الإجمالي', 'Total'), AMT, true)}${line(k('Paid', 'المدفوع', 'Pagado'), AMT)}</div></section>`;
    const concierge = `<section style="background:${C.tealTint};padding:24px;display:flex;flex-direction:column;gap:12px"><span style="font-family:{{fd}};font-size:20px;line-height:{{lhT}};color:${C.teal}">${k('Your concierge', 'الكونسيرج الخاص بك', 'Tu conserje')}</span><span style="font-size:14px;line-height:{{lhL}};color:${C.teal}">${k('Message us about anything on this trip.', 'راسلنا بشأن أي شيء يخص هذه الرحلة.', 'Escríbenos sobre cualquier cosa de este viaje.')}</span>${wa}</section>`;
    const cancelL = `<span style="display:inline-flex;align-items:center;min-height:44px;font-size:14px;color:${C.error}">${k('Request cancellation and refund', 'اطلب الإلغاء والاسترداد', 'Solicitar cancelación y reembolso')}</span>`;
    const left = `<div style="display:flex;flex-direction:column;gap:32px;width:${cls === 'd' ? colW + 'px' : 'auto'};flex:none">${stayC}${itin}</div>`;
    const right = `<div style="display:flex;flex-direction:column;gap:24px;width:${cls === 'd' ? '400px' : 'auto'};flex:none">${pay}${concierge}${cancelL}</div>`;
    const layout = cls === 'd' ? `<div style="display:flex;gap:32px;align-items:flex-start">${left}${right}</div>` : `<div style="display:flex;flex-direction:column;gap:32px">${pay}${stayC}${itin}${concierge}${cancelL}</div>`;
    return `<div style="width:${W}px;height:${Hh}px;box-sizing:border-box;background:${C.ivory};border:1px solid ${C.line};overflow:hidden;display:flex;flex-direction:column">${hd.html}<div style="padding:24px ${i0}px 0;display:flex;flex-direction:column;gap:24px">${top}${rail}${layout}</div></div>`;
  };
  const tripFrameOld = (cls) => {
    const [W] = SIZE[cls]; const Hh = { d: 1700, t: 2300, p: 2900 }[cls]; const hd = siteHeader(cx, W, cls); const i0 = inset(cls); const cw = W - 2 * i0;
    const banner = `<div style="position:relative;height:${cls === 'p' ? 320 : 380}px;overflow:hidden;background:${C.teal};flex:none"><img src="${B.stay}" alt="${TRIP}" style="position:absolute;inset:0;width:100%;height:100%;object-fit:cover;display:block"><div style="position:absolute;inset:0;background:rgba(38,38,38,0.4)"></div><div style="position:absolute;left:${i0}px;right:${i0}px;top:24px;display:flex;align-items:center;gap:12px"><span style="display:inline-flex;align-items:center;height:44px;padding:0 16px;background:${C.ivory};font-size:14px;color:${C.teal}">‹ ${g('bookings')}</span></div><div style="position:absolute;left:${i0}px;right:${i0}px;bottom:32px;display:flex;flex-direction:column;gap:12px"><div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap">${st.confirmed()}${st.driver()}<bdi style="font-size:12px;font-variant-numeric:tabular-nums;color:${C.ivory}">ALMAR-000000</bdi></div><h1 style="margin:0;font-family:{{fd}};font-weight:400;font-size:${cls === 'p' ? 32 : 48}px;line-height:{{lh1}};letter-spacing:{{tk}};color:${C.ivory}">${TRIP}</h1></div></div>`;
    const fact = (l, v) => `<div style="display:flex;flex-direction:column;gap:4px;padding:16px 24px;background:${C.surface};border-inline-end:1px solid ${C.line}"><span style="font-size:12px;line-height:{{lhC}};${UP}color:${C.muted}">${l}</span><span style="font-size:16px;line-height:{{lhB}};color:${C.ink}">${v}</span></div>`;
    const facts = `<div style="display:grid;grid-template-columns:repeat(${cls === 'p' ? 2 : 4},minmax(0,1fr));border:1px solid ${C.line};margin-top:-1px">${fact(k('Arrive', 'وصول', 'Llegada'), bdiN('[DD/MM/YYYY]'))}${fact(k('Leave', 'مغادرة', 'Salida'), bdiN('[DD/MM/YYYY]'))}${fact(k('Guests', 'الضيوف', 'Huéspedes'), ADULTS)}${fact(k('Stay', 'الإقامة', 'Estancia'), k(H.en.stays[0].name, H.ar.stays[0].name, H.es.stays[0].name))}</div>`;
    const tab = (t, on) => `<span style="display:inline-flex;align-items:center;min-height:44px;padding:0 16px;font-size:14px;color:${on ? C.teal : C.muted};box-shadow:${on ? `inset 0 -3px 0 ${C.teal}` : 'none'};white-space:nowrap">${t}</span>`;
    const tabs = `<div role="tablist" style="display:flex;border-bottom:1px solid ${C.line};overflow:hidden">${tab(k('Overview', 'نظرة عامة', 'Resumen'), true)}${tab(T('Experiences and services'))}${tab(k('Payment', 'الدفع', 'Pago'))}</div>`;
    const timeline = `<div style="display:flex;flex-direction:column;gap:12px"><h2 style="margin:0;font-family:{{fd}};font-weight:400;font-size:20px;line-height:{{lhT}};color:${C.teal}">${k('Trip status', 'حالة الرحلة', 'Estado del viaje')}</h2><ol style="margin:0;padding:0;list-style:none;display:flex;flex-direction:column">${[['Deposit paid', 'تم دفع المقدّم', 'Depósito pagado', 'done'], ['Confirmed', 'مؤكد', 'Confirmado', 'cur'], ['In trip', 'في الرحلة', 'En viaje', 'up'], ['Completed', 'مكتمل', 'Completado', 'up']].map(([a2, b2, c2, sx], i) => `<li style="display:flex;align-items:center;gap:12px;min-height:44px"><span style="display:flex;align-items:center;justify-content:center;width:28px;height:28px;box-sizing:border-box;${sx === 'done' ? `background:${C.teal};color:${C.ivory}` : `border:1px solid ${sx === 'cur' ? C.teal : C.muted};color:${sx === 'cur' ? C.teal : C.muted}`};font-size:12px">${sx === 'done' ? icon('check', 14, C.ivory) : i + 1}</span><span style="font-size:14px;color:${sx === 'up' ? C.muted : C.teal}">${k(a2, b2, c2)}</span></li>`).join('')}</ol></div>`;
    const addRow = (name, img) => `<div style="display:flex;align-items:center;gap:12px;min-height:72px;border-bottom:1px solid ${C.line}"><img src="${img}" alt="${name}" style="width:96px;height:72px;object-fit:cover;display:block;flex:none"><span style="flex:1;min-width:0;font-family:{{fd}};font-size:16px;line-height:{{lhT}};color:${C.teal}">${name}<span style="color:${C.muted}"> × 2</span></span>${AMT}</div>`;
    const info = `<section style="background:${C.surface};border:1px solid ${C.line};padding:24px;display:flex;flex-direction:column;gap:24px">${timeline}<div style="display:flex;flex-direction:column;gap:8px"><h2 style="margin:0;font-family:{{fd}};font-weight:400;font-size:20px;line-height:{{lhT}};color:${C.teal}">${k('Arrival', 'الوصول', 'Llegada')}</h2><div style="display:flex;gap:8px;flex-wrap:wrap">${st.driver()}${st.flights()}</div><span style="font-size:14px;line-height:{{lhL}};color:${C.muted}">${k('Exact address after confirmation.', 'العنوان الدقيق بعد التأكيد.', 'Dirección exacta tras la confirmación.')}</span></div></section>`;
    const adds = `<section style="background:${C.surface};border:1px solid ${C.line};padding:24px;display:flex;flex-direction:column;gap:16px"><div style="display:flex;align-items:center;justify-content:space-between;gap:12px"><h2 style="margin:0;font-family:{{fd}};font-weight:400;font-size:20px;line-height:{{lhT}};color:${C.teal}">${T('Experiences and services')}</h2>${secBtn(k('Add', 'أضف', 'Añadir'))}</div><div style="display:flex;flex-direction:column">${addRow(T('Cartagena Heritage Tours'), B.heritage)}${addRow(T('Rosario Islands Escape'), B.rosario)}</div></section>`;
    const line = (a2, v, bold) => `<div style="display:flex;justify-content:space-between;gap:12px;font-size:${bold ? 20 : 14}px;line-height:{{lhL}};color:${C.ink}${bold ? ';font-weight:700' : ''}"><span>${a2}</span><span>${v}</span></div>`;
    const pay = `<aside style="background:${C.surface};border:1px solid ${C.line};padding:24px;display:flex;flex-direction:column;gap:16px;box-sizing:border-box;${cls === 'd' ? 'width:400px;flex:none;position:relative;top:-96px;' : ''}"><h2 style="margin:0;font-family:{{fd}};font-weight:400;font-size:20px;line-height:{{lhT}};color:${C.teal}">${k('Payment', 'الدفع', 'Pago')}</h2>${progress}<div style="display:flex;flex-direction:column;gap:12px;padding-top:12px;border-top:1px solid ${C.line}">${line(k('Subtotal', 'المجموع الفرعي', 'Subtotal'), AMT)}${line(k('VAT [RATE]%', 'ضريبة القيمة المضافة [RATE]٪', 'IVA [RATE]%'), AMT)}<div style="padding-top:12px;border-top:1px solid ${C.ink}">${line(k('Total', 'الإجمالي', 'Total'), AMT, true)}</div></div>${primaryBtn(k('Pay balance', 'ادفع الرصيد', 'Pagar saldo'), 'height:56px;width:100%;box-sizing:border-box;')}<div style="display:flex;align-items:center;gap:12px;padding-top:12px;border-top:1px solid ${C.line}"><span style="font-size:14px;color:${C.ink}">${HELPQ}</span>${wa}</div></aside>`;
    const cancelCard = `<section style="background:${C.surface};border:1px solid ${C.line};padding:24px;display:flex;flex-direction:column;gap:12px"><h2 style="margin:0;font-family:{{fd}};font-weight:400;font-size:20px;line-height:{{lhT}};color:${C.teal}">${k('Cancellation and refund', 'الإلغاء والاسترداد', 'Cancelación y reembolso')}</h2><span style="font-size:14px;line-height:{{lhL}};color:${C.muted}">${k('[Refund policy]', '[سياسة الاسترداد]', '[Política de reembolso]')}</span><span style="display:inline-flex;align-items:center;height:44px;padding:0 24px;box-sizing:border-box;border:1px solid ${C.error};color:${C.ink};font-size:14px;align-self:flex-start">${k('Request cancellation and refund', 'اطلب الإلغاء والاسترداد', 'Solicitar cancelación y reembolso')}</span></section>`;
    const main = `<div style="display:flex;flex-direction:column;gap:24px;flex:1;min-width:0">${info}${adds}${cancelCard}</div>`;
    const layout = cls === 'd' ? `<div style="display:flex;gap:24px;align-items:flex-start">${main}${pay}</div>` : `<div style="display:flex;flex-direction:column;gap:24px">${pay}${main}</div>`;
    return `<div style="width:${W}px;height:${Hh}px;box-sizing:border-box;background:${C.ivory};border:1px solid ${C.line};overflow:hidden;display:flex;flex-direction:column">${hd.html}${banner}<div style="padding:0 ${i0}px;display:flex;flex-direction:column;gap:24px">${facts}${tabs}${layout}</div></div>`;
  };

  // ---------- ACCOUNT ACCESS (header menu) ----------
  const menuItems = [[k('Bookings', 'الحجوزات', 'Reservas'), 'ticket'], [PERS, ''], [TRAV, ''], [SAVED, ''], [PREF, '']];
  const menuList = (w) => `<div role="menu" style="width:${w}px;background:${C.surface};box-shadow:0 28px 56px -16px rgb(10 9 7 / 0.28), 0 10px 20px -10px rgb(10 9 7 / 0.12);display:flex;flex-direction:column"><div style="display:flex;align-items:center;gap:12px;padding:16px;border-bottom:1px solid ${C.line}"><div style="display:flex;flex-direction:column;min-width:0"><span style="font-size:14px;color:${C.ink}">${GUEST}</span><span style="font-size:12px;line-height:{{lhC}};color:${C.muted}"><bdi>${EM}</bdi></span></div></div>${menuItems.map(([t2], i) => `<span role="menuitem" style="display:flex;align-items:center;min-height:44px;padding:0 16px;font-size:14px;color:${C.ink};background:${i === 0 ? C.ivory : C.surface}">${t2}</span>`).join('')}<div style="border-top:1px solid ${C.line}"><span role="menuitem" style="display:flex;align-items:center;min-height:44px;padding:0 16px;font-size:14px;color:${C.ink}">${HELPQ}</span><span role="menuitem" style="display:flex;align-items:center;min-height:44px;padding:0 16px;font-size:14px;color:${C.ink}">${g('signOut')}</span></div></div>`;
  const menuFrames = () => {
    const capL = (t2) => `<span style="font-size:12px;line-height:1.5;color:${C.muted}"><bdi>${t2}</bdi></span>`;
    const hdOut = (() => { const c2 = { ...cx, signedIn: false }; return siteHeader(c2, 1440, 'd').html; })();
    const hdIn = siteHeader({ ...cx, signedIn: true }, 1440, 'd').html;
    const hdOpen = siteHeader({ ...cx, signedIn: true, menuOpen: true }, 1440, 'd').html;
    const box = (inner, h2) => `<div style="width:1440px;height:${h2}px;box-sizing:border-box;background:${C.ivory};border:1px solid ${C.line};position:relative;overflow:hidden">${inner}</div>`;
    const d1 = `<div style="display:flex;flex-direction:column;gap:12px">${capL('Desktop · signed out: Login')}${box(hdOut, 96)}${capL('Desktop · signed in: your name replaces Login')}${box(hdIn, 96)}${capL('Desktop · menu open')}${box(`${hdOpen}<div style="position:absolute;top:88px;inset-inline-end:100px">${menuList(288)}</div>`, 480)}</div>`;
    const phoneHd = (open) => `<div style="height:72px;display:flex;align-items:center;justify-content:space-between;padding:0 16px;border-bottom:1px solid ${C.line}"><img src="${LOGO}" alt="ALMAR Private Journeys" style="width:112px;height:auto;display:block"><span style="display:inline-flex;align-items:center;height:44px;padding:0 16px;box-sizing:border-box;border:1px solid ${C.muted};font-size:14px;color:${C.ink}">${open ? T('Close') : T('Menu')}</span></div>`;
    const phoneOpen = `<div style="width:390px;height:844px;box-sizing:border-box;background:${C.ivory};border:1px solid ${C.line};display:flex;flex-direction:column;overflow:hidden">${phoneHd(true)}<div style="padding:16px;display:flex;flex-direction:column;gap:16px;flex:1;min-height:0"><div style="display:flex;align-items:center;gap:12px;padding:16px;background:${C.tealTint}"><div style="display:flex;flex-direction:column;min-width:0"><span style="font-size:14px;color:${C.teal}">${GUEST}</span><span style="font-size:12px;line-height:{{lhC}};color:${C.teal}"><bdi>${EM}</bdi></span></div></div><div style="display:flex;flex-direction:column">${menuItems.map(([t2]) => `<span style="display:flex;align-items:center;min-height:56px;border-bottom:1px solid ${C.line};font-size:14px;color:${C.ink}">${t2}</span>`).join('')}</div><div style="display:flex;flex-direction:column">${[cx.t3((x) => x.nav.destinations), cx.t3((x) => x.nav.experiences), cx.t3((x) => x.nav.about), cx.t3((x) => x.nav.contact)].map((t2) => `<span style="display:flex;align-items:center;min-height:56px;border-bottom:1px solid ${C.line};font-size:12px;${UP}color:${C.teal}">${t2}</span>`).join('')}</div><div style="display:flex;gap:12px">${trig('AED')}${trig('EN')}</div><span style="display:inline-flex;align-items:center;justify-content:center;height:44px;box-sizing:border-box;border:1px solid ${C.muted};font-size:14px;color:${C.ink};margin-top:auto">${g('signOut')}</span></div></div>`;
    const phoneOut = `<div style="width:390px;height:200px;box-sizing:border-box;background:${C.ivory};border:1px solid ${C.line};overflow:hidden">${phoneHd(false)}<div style="padding:16px;font-size:12px;color:${C.muted}">${k('Signed out: the Menu list ends with Login.', 'قبل تسجيل الدخول: تنتهي القائمة بزر «دخول».', 'Sin sesión: la lista del menú termina con Entrar.')}</div></div>`;
    const ph = `<div style="display:flex;flex-direction:column;gap:12px;flex:none">${capL('Phone · menu open, signed in')}${phoneOpen}${capL('Phone · signed out')}${phoneOut}</div>`;
    return { framesHtml: `<div style="display:flex;align-items:flex-start;gap:80px">${d1}${ph}</div>`, maxH: 1300 };
  };

  // ---------- DELETE ACCOUNT (all states) ----------
  const DEL_T = k('Delete your account?', 'هل تريد حذف حسابك؟', '¿Eliminar tu cuenta?');
  const DEL_B = k('This permanently removes your profile, saved travelers and saved stays.', 'يحذف هذا ملفك الشخصي والمسافرين والإقامات المحفوظة نهائيًا.', 'Esto elimina para siempre tu perfil, viajeros y estancias guardadas.');
  const DEL_K = k('[What ALMAR keeps for legal or accounting reasons]', '[ما تحتفظ به ألمار لأسباب قانونية أو محاسبية]', '[Lo que ALMAR conserva por motivos legales o contables]');
  const dlg = (title, inner, foot, w = 480) => `<div style="width:${w}px;max-width:100%;background:${C.surface};box-shadow:0 28px 56px -16px rgb(10 9 7 / 0.28), 0 10px 20px -10px rgb(10 9 7 / 0.12);padding:24px;box-sizing:border-box;display:flex;flex-direction:column;gap:16px"><div style="display:flex;align-items:flex-start;justify-content:space-between;gap:16px"><h3 style="margin:0;font-family:{{fd}};font-weight:400;font-size:20px;line-height:{{lhT}};color:${C.teal}">${title}</h3><span style="display:flex;width:44px;height:44px;align-items:center;justify-content:center;color:${C.teal};margin:-8px -8px 0 0">${icon('x', 20, C.teal)}</span></div>${inner}<div style="display:flex;justify-content:flex-end;gap:12px;flex-wrap:wrap">${foot}</div></div>`;
  const cancelB = ghost(k('Cancel', 'إلغاء', 'Cancelar'));
  const dangerB = (t2, mode) => `<span style="display:inline-flex;align-items:center;justify-content:center;gap:12px;height:44px;padding:0 24px;box-sizing:border-box;font-size:14px;${mode === 'disabled' ? `background:${C.ivory};border:1px solid ${C.line};color:${C.muted}` : `border:1px solid ${C.error};color:${C.ink}`}">${mode === 'busy' ? icon('spinner', 20, 'currentColor') : ''}${t2}</span>`;
  const scrim = (inner, h2 = 420, w = 640) => `<div style="width:${w}px;height:${h2}px;box-sizing:border-box;background:rgba(38,38,38,0.4);display:flex;align-items:center;justify-content:center;padding:24px">${inner}</div>`;
  const labF = (t2, inner) => `<div style="display:flex;flex-direction:column;gap:12px;flex:none"><span style="font-size:12px;line-height:1.5;color:${C.muted}"><bdi>${t2}</bdi></span>${inner}</div>`;
  const deleteFrames = () => {
    const s1 = scrim(dlg(DEL_T, `<p style="margin:0;font-size:14px;line-height:{{lhL}};color:${C.ink}">${DEL_B}</p><p style="margin:0;font-size:12px;line-height:{{lhC}};color:${C.muted}">${DEL_K}</p>`, `${cancelB}${dangerB(k('Continue', 'متابعة', 'Continuar'))}`));
    const conf = (mode, val, err) => scrim(dlg(k('Confirm with your email', 'أكّد ببريدك الإلكتروني', 'Confirma con tu correo'), `<p style="margin:0;font-size:14px;line-height:{{lhL}};color:${C.ink}">${k('Type your email address to confirm.', 'اكتب عنوان بريدك الإلكتروني للتأكيد.', 'Escribe tu correo electrónico para confirmar.')}</p>${field(g('email'), val, err ? { err: k('That email does not match your account.', 'هذا البريد لا يطابق حسابك.', 'Ese correo no coincide con tu cuenta.') } : {})}`, `${cancelB}${dangerB(DEL, mode)}`));
    const blocked = scrim(dlg(k('You have upcoming trips', 'لديك رحلات قادمة', 'Tienes viajes próximos'), `<p style="margin:0;font-size:14px;line-height:{{lhL}};color:${C.ink}">${k('Cancel or complete them before you delete your account.', 'ألغِ الرحلات أو أكملها قبل حذف حسابك.', 'Cancélalos o complétalos antes de eliminar tu cuenta.')}</p>`, `${ghost(k('Close', 'إغلاق', 'Cerrar'))}${secBtn(g('bookings'))}`));
    const sent = scrim(dlg(k('Check your email', 'تحقق من بريدك', 'Revisa tu correo'), `<p style="margin:0;font-size:14px;line-height:{{lhL}};color:${C.ink}">${k('We sent a confirmation link to', 'أرسلنا رابط تأكيد إلى', 'Enviamos un enlace de confirmación a')} <bdi style="color:${C.teal}">${EM}</bdi>. ${k('Your account is deleted when you open it.', 'يُحذف حسابك عند فتحه.', 'Tu cuenta se elimina cuando lo abras.')}</p>`, `${ghost(k('Close', 'إغلاق', 'Cerrar'))}`));
    const errD = scrim(dlg(DEL_T, `<div role="alert" style="display:flex;align-items:center;gap:8px;color:${C.error};font-size:14px;line-height:{{lhL}}">${icon('alert-circle', 20, C.error)}<span>${k('We could not delete your account. Try again.', 'تعذّر حذف حسابك. حاول مرة أخرى.', 'No pudimos eliminar tu cuenta. Inténtalo de nuevo.')}</span></div>`, `${cancelB}${dangerB(k('Try again', 'حاول مرة أخرى', 'Inténtalo de nuevo'))}`));
    const donePage = (W, Hh) => `<div style="width:${W}px;height:${Hh}px;box-sizing:border-box;background:${C.ivory};border:1px solid ${C.line};display:flex;flex-direction:column;overflow:hidden"><div style="height:${W < 800 ? 72 : 96}px;display:flex;align-items:center;padding:0 ${W < 800 ? 16 : 100}px;border-bottom:1px solid ${C.line};flex:none">${logo(W < 800 ? 112 : 150)}</div><div style="flex:1;padding:${W < 800 ? '48px 16px' : '96px 100px'};display:flex;flex-direction:column;gap:24px;align-items:flex-start"><span style="display:flex;align-items:center;justify-content:center;width:56px;height:56px;background:${C.tealTint}">${icon('check', 24, C.teal)}</span><h1 style="margin:0;font-family:{{fd}};font-weight:400;font-size:${W < 800 ? 32 : 48}px;line-height:{{lh1}};letter-spacing:{{tk}};color:${C.teal}">${k('Your account has been deleted', 'تم حذف حسابك', 'Tu cuenta ha sido eliminada')}</h1><p style="margin:0;font-size:16px;line-height:{{lhB}};color:${C.ink};max-width:65ch">${k('You can create a new account at any time.', 'يمكنك إنشاء حساب جديد في أي وقت.', 'Puedes crear una cuenta nueva cuando quieras.')}</p>${primaryBtn(k('Back to home', 'العودة إلى الرئيسية', 'Volver al inicio'))}</div></div>`;
    const row1 = `<div style="display:flex;gap:48px;align-items:flex-start">${labF('1 · Entry: Delete account card on Account (see 6b). Confirm dialog', s1)}${labF('2 · Confirm with email, button disabled until it matches', conf('disabled', ''))}${labF('3 · Email typed, button enabled', conf('rest', EM))}</div>`;
    const row2 = `<div style="display:flex;gap:48px;align-items:flex-start">${labF('4 · Email does not match', conf('disabled', k('[Email]', '[البريد]', '[Correo]') , true))}${labF('5 · Deleting (busy)', conf('busy', EM))}${labF('6 · Failed', errD)}</div>`;
    const row3 = `<div style="display:flex;gap:48px;align-items:flex-start">${labF('7 · Blocked by upcoming trips', blocked)}${labF('8 · Confirmation link sent', sent)}</div>`;
    const row4 = `<div style="display:flex;gap:80px;align-items:flex-start">${labF('9 · Deleted, desktop', donePage(1440, 640))}${labF('9 · Deleted, phone', donePage(390, 640))}${labF('10 · Confirm dialog, phone', `<div style="width:390px;height:640px;box-sizing:border-box;background:rgba(38,38,38,0.4);display:flex;align-items:flex-end">${dlg(DEL_T, `<p style="margin:0;font-size:14px;line-height:{{lhL}};color:${C.ink}">${DEL_B}</p><p style="margin:0;font-size:12px;line-height:{{lhC}};color:${C.muted}">${DEL_K}</p>`, `${cancelB}${dangerB(k('Continue', 'متابعة', 'Continuar'))}`, 390)}</div>`)}</div>`;
    return { framesHtml: `<div style="display:flex;flex-direction:column;gap:48px">${row1}${row2}${row3}${row4}</div>`, maxH: 3 * 470 + 700 + 4 * 48 };
  };

  if (stem === 'GuestMenu') return menuFrames();
  if (stem === 'GuestDelete') return deleteFrames();
  // ---------- CANCELLATION AND REFUND (all states) ----------
  const REQ_T = k('Request cancellation and refund', 'اطلب الإلغاء والاسترداد', 'Solicitar cancelación y reembolso');
  const line2 = (a2, v, bold) => `<div style="display:flex;justify-content:space-between;gap:12px;font-size:14px;line-height:{{lhL}};color:${C.ink}${bold ? ';font-weight:700' : ''}"><span>${a2}</span><span>${v}</span></div>`;
  const summary2 = `<div style="display:flex;flex-direction:column;gap:8px;padding:16px;background:${C.ivory}"><span style="font-size:14px;color:${C.teal}">${TRIP} · <bdi>ALMAR-000000</bdi></span>${line2(k('Paid', 'المدفوع', 'Pagado'), AMT)}${line2(k('Refundable under the policy', 'قابل للاسترداد وفق السياسة', 'Reembolsable según la política'), AMT, true)}${line2(k('Not refundable', 'غير قابل للاسترداد', 'No reembolsable'), AMT)}<span style="font-size:12px;line-height:{{lhC}};color:${C.muted}">${k('[Refund policy]', '[سياسة الاسترداد]', '[Política de reembolso]')}</span></div>`;
  const reason = `<div style="display:flex;flex-direction:column;gap:8px"><span style="font-size:14px;color:${C.ink}">${k('Reason (optional)', 'السبب (اختياري)', 'Motivo (opcional)')}</span>${trig(k('Choose a reason', 'اختر سببًا', 'Elige un motivo'), '100%')}</div><div style="display:flex;flex-direction:column;gap:8px"><span style="font-size:14px;color:${C.ink}">${k('Note to ALMAR (optional)', 'ملاحظة إلى ألمار (اختياري)', 'Nota para ALMAR (opcional)')}</span><span style="display:block;height:80px;box-sizing:border-box;background:${C.surface};border:1px solid ${C.ink}"></span></div>`;
  const keepB = ghost(k('Keep my trip', 'أبقِ رحلتي', 'Mantener mi viaje'));
  const reqBtn = (mode) => dangerB(REQ_T, mode);
  const reqDlg = (mode, err, w = 560) => dlg(REQ_T, `${summary2}${reason}${err ? `<div role="alert" style="display:flex;align-items:center;gap:8px;color:${C.error};font-size:14px;line-height:{{lhL}}">${icon('alert-circle', 20, C.error)}<span>${k('We could not send your request. Try again.', 'تعذّر إرسال طلبك. حاول مرة أخرى.', 'No pudimos enviar tu solicitud. Inténtalo de nuevo.')}</span></div>` : ''}`, `${keepB}${reqBtn(mode)}`, w);
  const sentDlg = dlg(k('Request sent', 'تم إرسال الطلب', 'Solicitud enviada'), `<p style="margin:0;font-size:14px;line-height:{{lhL}};color:${C.ink}">${k('We will reply to', 'سنرد على', 'Responderemos a')} <bdi style="color:${C.teal}">${EM}</bdi> ${k('within [n] days. Nothing is charged or refunded until we confirm.', 'خلال [n] أيام. لن يُحصَّل أو يُسترد أي مبلغ قبل التأكيد.', 'en [n] días. No se cobra ni se reembolsa nada hasta que confirmemos.')}</p>`, ghost(k('Close', 'إغلاق', 'Cerrar')), 560);
  const naDlg = dlg(REQ_T, `<p style="margin:0;font-size:14px;line-height:{{lhL}};color:${C.ink}">${k('Cancellation is not available once the trip has started.', 'الإلغاء غير متاح بعد بدء الرحلة.', 'La cancelación no está disponible una vez iniciado el viaje.')}</p>${wa}`, ghost(k('Close', 'إغلاق', 'Cerrar')), 560);
  const banner = (chip, title2, body2, extra) => `<div style="width:640px;box-sizing:border-box;background:${C.surface};border:1px solid ${C.line};padding:24px;display:flex;flex-direction:column;gap:12px"><div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap">${chip}<bdi style="font-size:12px;font-variant-numeric:tabular-nums;color:${C.muted}">ALMAR-000000</bdi></div><h3 style="margin:0;font-family:{{fd}};font-weight:400;font-size:20px;line-height:{{lhT}};color:${C.teal}">${title2}</h3><span style="font-size:14px;line-height:{{lhL}};color:${C.ink}">${body2}</span>${extra || ''}</div>`;
  const cancelFrames = () => {
    const sc = (inner, h2 = 640) => scrim(inner, h2, 640);
    const row1 = `<div style="display:flex;gap:48px;align-items:flex-start">${labF('1 · Request dialog', sc(reqDlg('rest', false)))}${labF('2 · Sending (busy)', sc(reqDlg('busy', false)))}${labF('3 · Failed', sc(reqDlg('rest', true)))}</div>`;
    const row2 = `<div style="display:flex;gap:48px;align-items:flex-start">${labF('4 · Request sent', sc(sentDlg, 420))}${labF('5 · Not available once the trip has started', sc(naDlg, 420))}${labF('6 · Phone sheet', `<div style="width:390px;height:640px;box-sizing:border-box;background:rgba(38,38,38,0.4);display:flex;align-items:flex-end;overflow:hidden">${reqDlg('rest', false, 390)}</div>`)}</div>`;
    const row3 = `<div style="display:flex;gap:48px;align-items:flex-start">${labF('7 · Status on the trip: requested', banner(chipReq(), k('Cancellation requested', 'تم طلب الإلغاء', 'Cancelación solicitada'), k('We are reviewing your request. Your trip stays as it is until we reply.', 'نراجع طلبك. تبقى رحلتك كما هي حتى نرد.', 'Estamos revisando tu solicitud. Tu viaje sigue igual hasta que respondamos.'), ghost(k('View request', 'عرض الطلب', 'Ver solicitud'))))}${labF('8 · Approved, refund pending', banner(chipS('Refund approved', 'تمت الموافقة على الاسترداد', 'Reembolso aprobado', false), k('Refund approved', 'تمت الموافقة على الاسترداد', 'Reembolso aprobado'), `${k('We will refund', 'سنستردّ', 'Reembolsaremos')} ${AMT} ${k('to your original payment method within [n] days.', 'إلى وسيلة الدفع الأصلية خلال [n] أيام.', 'a tu método de pago original en [n] días.')}`))}${labF('9 · Refunded, trip cancelled', banner(chipS('Refunded', 'تم الاسترداد', 'Reembolsado', false), k('Refunded', 'تم الاسترداد', 'Reembolsado'), `${AMT} ${k('was refunded to your original payment method on', 'استُرد إلى وسيلة الدفع الأصلية بتاريخ', 'se reembolsó a tu método de pago original el')} ${bdiN('[DD/MM/YYYY]')}. ${k('This trip is cancelled.', 'أُلغيت هذه الرحلة.', 'Este viaje está cancelado.')}`))}</div>`;
    return { framesHtml: `<div style="display:flex;flex-direction:column;gap:48px">${row1}${row2}${row3}</div>`, maxH: 640 + 30 + 420 + 30 + 260 + 30 + 96 + 100 };
  };

  if (stem === 'GuestCancel') return cancelFrames();
  const spec = {
    GuestLogin: { fn: loginFrame, rows: [['default', 'Empty'], ['error', 'Error'], ['typed', 'Typing'], ['sent', 'Link sent']], hs: { d: 900, t: 1000, p: 844 } },
    GuestAccount: { fn: accountFrame, rows: [['filled', 'Filled'], ['empty', 'Empty']], hs: { d: 1900, t: 2500, p: 2700 } },
    GuestBookings: { fn: bookingsFrame, rows: [['filled', 'Filled'], ['empty', 'Empty']], hs: { d: 1240, t: 1800, p: 2400 } },
    GuestTrip: { fn: tripFrame, rows: [['filled', 'Filled']], hs: { d: 1760, t: 2500, p: 2900 } },
  }[stem];
  const rowsHtml = spec.rows.map(([sst, lab]) => `<div style="display:flex;align-items:flex-start;gap:80px">${WIDTHS.map(([W, cls, label]) => `<div style="display:flex;flex-direction:column;gap:12px;flex:none"><span style="font-size:12px;line-height:1.5;color:${C.muted}"><bdi>${label} · ${lab}</bdi></span>${spec.fn(cls, sst)}</div>`).join('')}</div>`).join('');
  const rowH = Math.max(...Object.values(spec.hs)) + 30;
  return { framesHtml: `<div style="display:flex;flex-direction:column;gap:48px">${rowsHtml}</div>`, maxH: spec.rows.length * rowH + (spec.rows.length - 1) * 48 };
}
